<?php

/**
 * BaseAuditoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fechaactividad
 * @property date $proximafecha
 * @property boolean $ingresantes
 * @property boolean $reg7
 * @property boolean $docentes
 * @property boolean $desigdocentes
 * @property boolean $progplanif
 * @property boolean $asistenciadoc
 * @property boolean $diplomas
 * @property boolean $equival
 * @property boolean $certif
 * @property boolean $actividades
 * @property boolean $paseinterno
 * @property integer $idfacultad
 * @property integer $idsede
 * @property Facultades $Facultades
 * @property Sedes $Sedes
 * 
 * @method date       getFechaactividad() Returns the current record's "fechaactividad" value
 * @method date       getProximafecha()   Returns the current record's "proximafecha" value
 * @method boolean    getIngresantes()    Returns the current record's "ingresantes" value
 * @method boolean    getReg7()           Returns the current record's "reg7" value
 * @method boolean    getDocentes()       Returns the current record's "docentes" value
 * @method boolean    getDesigdocentes()  Returns the current record's "desigdocentes" value
 * @method boolean    getProgplanif()     Returns the current record's "progplanif" value
 * @method boolean    getAsistenciadoc()  Returns the current record's "asistenciadoc" value
 * @method boolean    getDiplomas()       Returns the current record's "diplomas" value
 * @method boolean    getEquival()        Returns the current record's "equival" value
 * @method boolean    getCertif()         Returns the current record's "certif" value
 * @method boolean    getActividades()    Returns the current record's "actividades" value
 * @method boolean    getPaseinterno()    Returns the current record's "paseinterno" value
 * @method integer    getIdfacultad()     Returns the current record's "idfacultad" value
 * @method integer    getIdsede()         Returns the current record's "idsede" value
 * @method Facultades getFacultades()     Returns the current record's "Facultades" value
 * @method Sedes      getSedes()          Returns the current record's "Sedes" value
 * @method Auditoria  setFechaactividad() Sets the current record's "fechaactividad" value
 * @method Auditoria  setProximafecha()   Sets the current record's "proximafecha" value
 * @method Auditoria  setIngresantes()    Sets the current record's "ingresantes" value
 * @method Auditoria  setReg7()           Sets the current record's "reg7" value
 * @method Auditoria  setDocentes()       Sets the current record's "docentes" value
 * @method Auditoria  setDesigdocentes()  Sets the current record's "desigdocentes" value
 * @method Auditoria  setProgplanif()     Sets the current record's "progplanif" value
 * @method Auditoria  setAsistenciadoc()  Sets the current record's "asistenciadoc" value
 * @method Auditoria  setDiplomas()       Sets the current record's "diplomas" value
 * @method Auditoria  setEquival()        Sets the current record's "equival" value
 * @method Auditoria  setCertif()         Sets the current record's "certif" value
 * @method Auditoria  setActividades()    Sets the current record's "actividades" value
 * @method Auditoria  setPaseinterno()    Sets the current record's "paseinterno" value
 * @method Auditoria  setIdfacultad()     Sets the current record's "idfacultad" value
 * @method Auditoria  setIdsede()         Sets the current record's "idsede" value
 * @method Auditoria  setFacultades()     Sets the current record's "Facultades" value
 * @method Auditoria  setSedes()          Sets the current record's "Sedes" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuditoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auditoria');
        $this->hasColumn('fechaactividad', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('proximafecha', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('ingresantes', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('reg7', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('docentes', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('desigdocentes', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('progplanif', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('asistenciadoc', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('diplomas', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('equival', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('certif', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('actividades', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('paseinterno', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('idfacultad', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idsede', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Facultades', array(
             'local' => 'idfacultad',
             'foreign' => 'idfacultad'));

        $this->hasOne('Sedes', array(
             'local' => 'idsede',
             'foreign' => 'idsede'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}