<?php

/**
 * BaseProfesiones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idprofesion
 * @property string $descripcion
 * @property Doctrine_Collection $Profesiones
 * 
 * @method integer             getIdprofesion() Returns the current record's "idprofesion" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getProfesiones() Returns the current record's "Profesiones" collection
 * @method Profesiones         setIdprofesion() Sets the current record's "idprofesion" value
 * @method Profesiones         setDescripcion() Sets the current record's "descripcion" value
 * @method Profesiones         setProfesiones() Sets the current record's "Profesiones" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesiones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesiones');
        $this->hasColumn('idprofesion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DocLaboral as Profesiones', array(
             'local' => 'idprofesion',
             'foreign' => 'idprofesion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}