<?php

/**
 * BaseInscripcionesMesas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idinscripcion
 * @property integer $idalumno
 * @property integer $idcatedra
 * @property integer $idllamado
 * @property integer $idcondicionmesa
 * @property integer $idmesaexamen
 * @property boolean $confirmado
 * @property boolean $transferido
 * @property string $comentario
 * @property Alumnos $Alumnos
 * @property Catedras $Catedras
 * @property LlamadosTurno $LlamadosTurno
 * 
 * @method integer            getIdinscripcion()   Returns the current record's "idinscripcion" value
 * @method integer            getIdalumno()        Returns the current record's "idalumno" value
 * @method integer            getIdcatedra()       Returns the current record's "idcatedra" value
 * @method integer            getIdllamado()       Returns the current record's "idllamado" value
 * @method integer            getIdcondicionmesa() Returns the current record's "idcondicionmesa" value
 * @method integer            getIdmesaexamen()    Returns the current record's "idmesaexamen" value
 * @method boolean            getConfirmado()      Returns the current record's "confirmado" value
 * @method boolean            getTransferido()     Returns the current record's "transferido" value
 * @method string             getComentario()      Returns the current record's "comentario" value
 * @method Alumnos            getAlumnos()         Returns the current record's "Alumnos" value
 * @method Catedras           getCatedras()        Returns the current record's "Catedras" value
 * @method LlamadosTurno      getLlamadosTurno()   Returns the current record's "LlamadosTurno" value
 * @method InscripcionesMesas setIdinscripcion()   Sets the current record's "idinscripcion" value
 * @method InscripcionesMesas setIdalumno()        Sets the current record's "idalumno" value
 * @method InscripcionesMesas setIdcatedra()       Sets the current record's "idcatedra" value
 * @method InscripcionesMesas setIdllamado()       Sets the current record's "idllamado" value
 * @method InscripcionesMesas setIdcondicionmesa() Sets the current record's "idcondicionmesa" value
 * @method InscripcionesMesas setIdmesaexamen()    Sets the current record's "idmesaexamen" value
 * @method InscripcionesMesas setConfirmado()      Sets the current record's "confirmado" value
 * @method InscripcionesMesas setTransferido()     Sets the current record's "transferido" value
 * @method InscripcionesMesas setComentario()      Sets the current record's "comentario" value
 * @method InscripcionesMesas setAlumnos()         Sets the current record's "Alumnos" value
 * @method InscripcionesMesas setCatedras()        Sets the current record's "Catedras" value
 * @method InscripcionesMesas setLlamadosTurno()   Sets the current record's "LlamadosTurno" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInscripcionesMesas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inscripciones_mesas');
        $this->hasColumn('idinscripcion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idcatedra', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idllamado', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idcondicionmesa', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idmesaexamen', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('confirmado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('transferido', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('comentario', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('owner_name', array(
             'fields' => 
             array(
              0 => 'idalumno',
              1 => 'idcatedra',
              2 => 'idllamado',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $this->hasOne('Catedras', array(
             'local' => 'idcatedra',
             'foreign' => 'idcatedra'));

        $this->hasOne('LlamadosTurno', array(
             'local' => 'idllamado',
             'foreign' => 'idllamado'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}