<?php

/**
 * BasePaises
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpais
 * @property string $descripcion
 * @property string $abreviacion
 * @property string $gentiliciom
 * @property string $gentiliciof
 * @property Doctrine_Collection $Paises
 * @property Doctrine_Collection $Provincias
 * 
 * @method integer             getIdpais()      Returns the current record's "idpais" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method string              getAbreviacion() Returns the current record's "abreviacion" value
 * @method string              getGentiliciom() Returns the current record's "gentiliciom" value
 * @method string              getGentiliciof() Returns the current record's "gentiliciof" value
 * @method Doctrine_Collection getPaises()      Returns the current record's "Paises" collection
 * @method Doctrine_Collection getProvincias()  Returns the current record's "Provincias" collection
 * @method Paises              setIdpais()      Sets the current record's "idpais" value
 * @method Paises              setDescripcion() Sets the current record's "descripcion" value
 * @method Paises              setAbreviacion() Sets the current record's "abreviacion" value
 * @method Paises              setGentiliciom() Sets the current record's "gentiliciom" value
 * @method Paises              setGentiliciof() Sets the current record's "gentiliciof" value
 * @method Paises              setPaises()      Sets the current record's "Paises" collection
 * @method Paises              setProvincias()  Sets the current record's "Provincias" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaises extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paises');
        $this->hasColumn('idpais', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 50,
             ));
        $this->hasColumn('abreviacion', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 5,
             ));
        $this->hasColumn('gentiliciom', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 50,
             ));
        $this->hasColumn('gentiliciof', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TiposDocumentos as Paises', array(
             'local' => 'idpais',
             'foreign' => 'idpais'));

        $this->hasMany('Provincias', array(
             'local' => 'idpais',
             'foreign' => 'idpais'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}