<?php

/**
 * BaseAsignacionesMesas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmesaexamen
 * @property MesasExamenes $MesasExamenes
 * 
 * @method integer           getIdmesaexamen()  Returns the current record's "idmesaexamen" value
 * @method MesasExamenes     getMesasExamenes() Returns the current record's "MesasExamenes" value
 * @method AsignacionesMesas setIdmesaexamen()  Sets the current record's "idmesaexamen" value
 * @method AsignacionesMesas setMesasExamenes() Sets the current record's "MesasExamenes" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsignacionesMesas extends Asignaciones
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('asignaciones_mesas');
        $this->hasColumn('idmesaexamen', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MesasExamenes', array(
             'local' => 'idmesaexamen',
             'foreign' => 'idmesaexamen'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}