<?php

/**
 * BaseTiposCorrelatividades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipocorrelatividad
 * @property string $descripcion
 * 
 * @method integer               getIdtipocorrelatividad() Returns the current record's "idtipocorrelatividad" value
 * @method string                getDescripcion()          Returns the current record's "descripcion" value
 * @method TiposCorrelatividades setIdtipocorrelatividad() Sets the current record's "idtipocorrelatividad" value
 * @method TiposCorrelatividades setDescripcion()          Sets the current record's "descripcion" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposCorrelatividades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_correlatividades');
        $this->hasColumn('idtipocorrelatividad', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}