<?php

/**
 * BaseEstadosSolicitudes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descripcion
 * @property Doctrine_Collection $EstadosSolicitudes
 * 
 * @method string              getDescripcion()        Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEstadosSolicitudes() Returns the current record's "EstadosSolicitudes" collection
 * @method EstadosSolicitudes  setDescripcion()        Sets the current record's "descripcion" value
 * @method EstadosSolicitudes  setEstadosSolicitudes() Sets the current record's "EstadosSolicitudes" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadosSolicitudes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estados_solicitudes');
        $this->hasColumn('descripcion', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SolicitudesLibredeuda as EstadosSolicitudes', array(
             'local' => 'id',
             'foreign' => 'idestadosolicitud'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}