<?php

/**
 * BaseModosEgreso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmodoegreso
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $ModosEgreso
 * 
 * @method integer             getIdmodoegreso() Returns the current record's "idmodoegreso" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method Doctrine_Collection getModosEgreso()  Returns the current record's "ModosEgreso" collection
 * @method ModosEgreso         setIdmodoegreso() Sets the current record's "idmodoegreso" value
 * @method ModosEgreso         setNombre()       Sets the current record's "nombre" value
 * @method ModosEgreso         setDescripcion()  Sets the current record's "descripcion" value
 * @method ModosEgreso         setModosEgreso()  Sets the current record's "ModosEgreso" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseModosEgreso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('modos_egreso');
        $this->hasColumn('idmodoegreso', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 40,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TitulosPlanes as ModosEgreso', array(
             'local' => 'idmodoegreso',
             'foreign' => 'idmodoegreso'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}