<?php

/**
 * BaseEstadosAlumno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idestadoalumno
 * @property string $descripcion
 * @property Doctrine_Collection $EstadosAlumno
 * 
 * @method integer             getIdestadoalumno() Returns the current record's "idestadoalumno" value
 * @method string              getDescripcion()    Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEstadosAlumno()  Returns the current record's "EstadosAlumno" collection
 * @method EstadosAlumno       setIdestadoalumno() Sets the current record's "idestadoalumno" value
 * @method EstadosAlumno       setDescripcion()    Sets the current record's "descripcion" value
 * @method EstadosAlumno       setEstadosAlumno()  Sets the current record's "EstadosAlumno" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadosAlumno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estados_alumno');
        $this->hasColumn('idestadoalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EstadosAlumnoHistorial as EstadosAlumno', array(
             'local' => 'idestadoalumno',
             'foreign' => 'idestadoalumno'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}