<?php

/**
 * BaseBajasAlumnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbaja
 * @property integer $idalumno
 * @property date $fecha
 * @property date $fechabaja
 * @property string $tiposolicitud
 * @property string $tipobaja
 * @property string $otromotivo
 * @property Alumnos $Alumnos
 * @property Doctrine_Collection $BajasAlumnos
 * 
 * @method integer             getIdbaja()        Returns the current record's "idbaja" value
 * @method integer             getIdalumno()      Returns the current record's "idalumno" value
 * @method date                getFecha()         Returns the current record's "fecha" value
 * @method date                getFechabaja()     Returns the current record's "fechabaja" value
 * @method string              getTiposolicitud() Returns the current record's "tiposolicitud" value
 * @method string              getTipobaja()      Returns the current record's "tipobaja" value
 * @method string              getOtromotivo()    Returns the current record's "otromotivo" value
 * @method Alumnos             getAlumnos()       Returns the current record's "Alumnos" value
 * @method Doctrine_Collection getBajasAlumnos()  Returns the current record's "BajasAlumnos" collection
 * @method BajasAlumnos        setIdbaja()        Sets the current record's "idbaja" value
 * @method BajasAlumnos        setIdalumno()      Sets the current record's "idalumno" value
 * @method BajasAlumnos        setFecha()         Sets the current record's "fecha" value
 * @method BajasAlumnos        setFechabaja()     Sets the current record's "fechabaja" value
 * @method BajasAlumnos        setTiposolicitud() Sets the current record's "tiposolicitud" value
 * @method BajasAlumnos        setTipobaja()      Sets the current record's "tipobaja" value
 * @method BajasAlumnos        setOtromotivo()    Sets the current record's "otromotivo" value
 * @method BajasAlumnos        setAlumnos()       Sets the current record's "Alumnos" value
 * @method BajasAlumnos        setBajasAlumnos()  Sets the current record's "BajasAlumnos" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBajasAlumnos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bajas_alumnos');
        $this->hasColumn('idbaja', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fechabaja', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tiposolicitud', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'O',
             'length' => 1,
             ));
        $this->hasColumn('tipobaja', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'P',
             'length' => 1,
             ));
        $this->hasColumn('otromotivo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $this->hasMany('MateriasBajas as BajasAlumnos', array(
             'local' => 'idbaja',
             'foreign' => 'idbaja'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}