<?php

/**
 * BasePeriodosCiclos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idfecha
 * @property integer $idciclo
 * @property FechasCalendario $FechasCalendario
 * @property CiclosLectivos $CiclosLectivos
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getIdfecha()          Returns the current record's "idfecha" value
 * @method integer          getIdciclo()          Returns the current record's "idciclo" value
 * @method FechasCalendario getFechasCalendario() Returns the current record's "FechasCalendario" value
 * @method CiclosLectivos   getCiclosLectivos()   Returns the current record's "CiclosLectivos" value
 * @method PeriodosCiclos   setId()               Sets the current record's "id" value
 * @method PeriodosCiclos   setIdfecha()          Sets the current record's "idfecha" value
 * @method PeriodosCiclos   setIdciclo()          Sets the current record's "idciclo" value
 * @method PeriodosCiclos   setFechasCalendario() Sets the current record's "FechasCalendario" value
 * @method PeriodosCiclos   setCiclosLectivos()   Sets the current record's "CiclosLectivos" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeriodosCiclos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periodos_ciclos');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idfecha', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idciclo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FechasCalendario', array(
             'local' => 'idfecha',
             'foreign' => 'idfecha'));

        $this->hasOne('CiclosLectivos', array(
             'local' => 'idciclo',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}