<?php

/**
 * BaseTiposAsignaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoasignacion
 * @property string $descripcion
 * @property Doctrine_Collection $TiposAsignaciones
 * 
 * @method integer             getIdtipoasignacion()  Returns the current record's "idtipoasignacion" value
 * @method string              getDescripcion()       Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTiposAsignaciones() Returns the current record's "TiposAsignaciones" collection
 * @method TiposAsignaciones   setIdtipoasignacion()  Sets the current record's "idtipoasignacion" value
 * @method TiposAsignaciones   setDescripcion()       Sets the current record's "descripcion" value
 * @method TiposAsignaciones   setTiposAsignaciones() Sets the current record's "TiposAsignaciones" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposAsignaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_asignaciones');
        $this->hasColumn('idtipoasignacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Asignaciones as TiposAsignaciones', array(
             'local' => 'idtipoasignacion',
             'foreign' => 'idtipoasignacion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}