<?php

/**
 * BaseMovimientosAlumnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmovimiento
 * @property integer $idestado
 * @property date $fecha
 * @property date $fechavencimiento
 * @property integer $idalumno
 * @property integer $idresponsable
 * @property Alumnos $Alumnos
 * 
 * @method integer            getIdmovimiento()     Returns the current record's "idmovimiento" value
 * @method integer            getIdestado()         Returns the current record's "idestado" value
 * @method date               getFecha()            Returns the current record's "fecha" value
 * @method date               getFechavencimiento() Returns the current record's "fechavencimiento" value
 * @method integer            getIdalumno()         Returns the current record's "idalumno" value
 * @method integer            getIdresponsable()    Returns the current record's "idresponsable" value
 * @method Alumnos            getAlumnos()          Returns the current record's "Alumnos" value
 * @method MovimientosAlumnos setIdmovimiento()     Sets the current record's "idmovimiento" value
 * @method MovimientosAlumnos setIdestado()         Sets the current record's "idestado" value
 * @method MovimientosAlumnos setFecha()            Sets the current record's "fecha" value
 * @method MovimientosAlumnos setFechavencimiento() Sets the current record's "fechavencimiento" value
 * @method MovimientosAlumnos setIdalumno()         Sets the current record's "idalumno" value
 * @method MovimientosAlumnos setIdresponsable()    Sets the current record's "idresponsable" value
 * @method MovimientosAlumnos setAlumnos()          Sets the current record's "Alumnos" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMovimientosAlumnos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movimientos_alumnos');
        $this->hasColumn('idmovimiento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idestado', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'default' => '2002-01-01',
             'length' => 25,
             ));
        $this->hasColumn('fechavencimiento', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'default' => '2002-01-01',
             'length' => 25,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idresponsable', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}