<?php

/**
 * BaseTiposResoluciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtiporesolucion
 * @property string $nombre
 * @property Doctrine_Collection $TiposResoluciones
 * 
 * @method integer             getIdtiporesolucion()  Returns the current record's "idtiporesolucion" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method Doctrine_Collection getTiposResoluciones() Returns the current record's "TiposResoluciones" collection
 * @method TiposResoluciones   setIdtiporesolucion()  Sets the current record's "idtiporesolucion" value
 * @method TiposResoluciones   setNombre()            Sets the current record's "nombre" value
 * @method TiposResoluciones   setTiposResoluciones() Sets the current record's "TiposResoluciones" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposResoluciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_resoluciones');
        $this->hasColumn('idtiporesolucion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PlanesEstudios as TiposResoluciones', array(
             'local' => 'idtiporesolucion',
             'foreign' => 'idtiporesolucion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}