<?php

/**
 * BaseEquivalenciasAlumnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idequivalencia
 * @property integer $idalumno
 * @property date $fecha
 * @property date $fecharesolucion
 * @property string $nroresolucion
 * @property string $observaciones
 * @property string $cantidadprogramas
 * @property string $nrorecibo1
 * @property string $nrorecibo2
 * @property Alumnos $Alumnos
 * @property Doctrine_Collection $EquivalenciasAlumnos
 * 
 * @method integer              getIdequivalencia()       Returns the current record's "idequivalencia" value
 * @method integer              getIdalumno()             Returns the current record's "idalumno" value
 * @method date                 getFecha()                Returns the current record's "fecha" value
 * @method date                 getFecharesolucion()      Returns the current record's "fecharesolucion" value
 * @method string               getNroresolucion()        Returns the current record's "nroresolucion" value
 * @method string               getObservaciones()        Returns the current record's "observaciones" value
 * @method string               getCantidadprogramas()    Returns the current record's "cantidadprogramas" value
 * @method string               getNrorecibo1()           Returns the current record's "nrorecibo1" value
 * @method string               getNrorecibo2()           Returns the current record's "nrorecibo2" value
 * @method Alumnos              getAlumnos()              Returns the current record's "Alumnos" value
 * @method Doctrine_Collection  getEquivalenciasAlumnos() Returns the current record's "EquivalenciasAlumnos" collection
 * @method EquivalenciasAlumnos setIdequivalencia()       Sets the current record's "idequivalencia" value
 * @method EquivalenciasAlumnos setIdalumno()             Sets the current record's "idalumno" value
 * @method EquivalenciasAlumnos setFecha()                Sets the current record's "fecha" value
 * @method EquivalenciasAlumnos setFecharesolucion()      Sets the current record's "fecharesolucion" value
 * @method EquivalenciasAlumnos setNroresolucion()        Sets the current record's "nroresolucion" value
 * @method EquivalenciasAlumnos setObservaciones()        Sets the current record's "observaciones" value
 * @method EquivalenciasAlumnos setCantidadprogramas()    Sets the current record's "cantidadprogramas" value
 * @method EquivalenciasAlumnos setNrorecibo1()           Sets the current record's "nrorecibo1" value
 * @method EquivalenciasAlumnos setNrorecibo2()           Sets the current record's "nrorecibo2" value
 * @method EquivalenciasAlumnos setAlumnos()              Sets the current record's "Alumnos" value
 * @method EquivalenciasAlumnos setEquivalenciasAlumnos() Sets the current record's "EquivalenciasAlumnos" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquivalenciasAlumnos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equivalencias_alumnos');
        $this->hasColumn('idequivalencia', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecharesolucion', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nroresolucion', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('observaciones', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cantidadprogramas', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '',
             'length' => 10,
             ));
        $this->hasColumn('nrorecibo1', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('nrorecibo2', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $this->hasMany('MateriasEquivalencias as EquivalenciasAlumnos', array(
             'local' => 'idequivalencia',
             'foreign' => 'idequivalencia'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}