<?php

/**
 * BaseAreas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idarea
 * @property integer $idtipoarea
 * @property integer $idareadependiente
 * @property string $descripcion
 * @property string $letralegajo
 * @property string $abreviacion
 * @property TiposAreas $TiposAreas
 * @property Doctrine_Collection $Areas
 * 
 * @method integer             getIdarea()            Returns the current record's "idarea" value
 * @method integer             getIdtipoarea()        Returns the current record's "idtipoarea" value
 * @method integer             getIdareadependiente() Returns the current record's "idareadependiente" value
 * @method string              getDescripcion()       Returns the current record's "descripcion" value
 * @method string              getLetralegajo()       Returns the current record's "letralegajo" value
 * @method string              getAbreviacion()       Returns the current record's "abreviacion" value
 * @method TiposAreas          getTiposAreas()        Returns the current record's "TiposAreas" value
 * @method Doctrine_Collection getAreas()             Returns the current record's "Areas" collection
 * @method Areas               setIdarea()            Sets the current record's "idarea" value
 * @method Areas               setIdtipoarea()        Sets the current record's "idtipoarea" value
 * @method Areas               setIdareadependiente() Sets the current record's "idareadependiente" value
 * @method Areas               setDescripcion()       Sets the current record's "descripcion" value
 * @method Areas               setLetralegajo()       Sets the current record's "letralegajo" value
 * @method Areas               setAbreviacion()       Sets the current record's "abreviacion" value
 * @method Areas               setTiposAreas()        Sets the current record's "TiposAreas" value
 * @method Areas               setAreas()             Sets the current record's "Areas" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('areas');
        $this->hasColumn('idarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idtipoarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idareadependiente', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('descripcion', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 80,
             ));
        $this->hasColumn('letralegajo', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 2,
             ));
        $this->hasColumn('abreviacion', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TiposAreas', array(
             'local' => 'idtipoarea',
             'foreign' => 'idtipoarea'));

        $this->hasMany('AreasCarrera as Areas', array(
             'local' => 'idarea',
             'foreign' => 'idarea'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}