<?php

/**
 * BaseFechasCalendario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idfecha
 * @property integer $idcalendario
 * @property integer $idtipo
 * @property string $descripcion
 * @property date $inicio
 * @property date $fin
 * @property Calendarios $Calendarios
 * @property TiposFechasCalendario $TiposFechasCalendario
 * @property Doctrine_Collection $FechasCalendario
 * 
 * @method integer               getIdfecha()               Returns the current record's "idfecha" value
 * @method integer               getIdcalendario()          Returns the current record's "idcalendario" value
 * @method integer               getIdtipo()                Returns the current record's "idtipo" value
 * @method string                getDescripcion()           Returns the current record's "descripcion" value
 * @method date                  getInicio()                Returns the current record's "inicio" value
 * @method date                  getFin()                   Returns the current record's "fin" value
 * @method Calendarios           getCalendarios()           Returns the current record's "Calendarios" value
 * @method TiposFechasCalendario getTiposFechasCalendario() Returns the current record's "TiposFechasCalendario" value
 * @method Doctrine_Collection   getFechasCalendario()      Returns the current record's "FechasCalendario" collection
 * @method FechasCalendario      setIdfecha()               Sets the current record's "idfecha" value
 * @method FechasCalendario      setIdcalendario()          Sets the current record's "idcalendario" value
 * @method FechasCalendario      setIdtipo()                Sets the current record's "idtipo" value
 * @method FechasCalendario      setDescripcion()           Sets the current record's "descripcion" value
 * @method FechasCalendario      setInicio()                Sets the current record's "inicio" value
 * @method FechasCalendario      setFin()                   Sets the current record's "fin" value
 * @method FechasCalendario      setCalendarios()           Sets the current record's "Calendarios" value
 * @method FechasCalendario      setTiposFechasCalendario() Sets the current record's "TiposFechasCalendario" value
 * @method FechasCalendario      setFechasCalendario()      Sets the current record's "FechasCalendario" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFechasCalendario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fechas_calendario');
        $this->hasColumn('idfecha', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idcalendario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idtipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('inicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fin', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Calendarios', array(
             'local' => 'idcalendario',
             'foreign' => 'idcalendario'));

        $this->hasOne('TiposFechasCalendario', array(
             'local' => 'idtipo',
             'foreign' => 'idtipo'));

        $this->hasMany('LlamadosTurno as FechasCalendario', array(
             'local' => 'idfecha',
             'foreign' => 'idfecha'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}