<?php

/**
 * BaseTiposDocumentacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipodocumentacion
 * @property string $nombre
 * @property string $nombrereducido
 * @property integer $aplicable
 * @property integer $orden
 * @property Doctrine_Collection $Documentacion
 * 
 * @method integer             getIdtipodocumentacion() Returns the current record's "idtipodocumentacion" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method string              getNombrereducido()      Returns the current record's "nombrereducido" value
 * @method integer             getAplicable()           Returns the current record's "aplicable" value
 * @method integer             getOrden()               Returns the current record's "orden" value
 * @method Doctrine_Collection getDocumentacion()       Returns the current record's "Documentacion" collection
 * @method TiposDocumentacion  setIdtipodocumentacion() Sets the current record's "idtipodocumentacion" value
 * @method TiposDocumentacion  setNombre()              Sets the current record's "nombre" value
 * @method TiposDocumentacion  setNombrereducido()      Sets the current record's "nombrereducido" value
 * @method TiposDocumentacion  setAplicable()           Sets the current record's "aplicable" value
 * @method TiposDocumentacion  setOrden()               Sets the current record's "orden" value
 * @method TiposDocumentacion  setDocumentacion()       Sets the current record's "Documentacion" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposDocumentacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_documentacion');
        $this->hasColumn('idtipodocumentacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('nombrereducido', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('aplicable', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('orden', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Documentacion', array(
             'local' => 'idtipodocumentacion',
             'foreign' => 'idtipodocumentacion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}