<?php

/**
 * BaseMotivosBajas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmotivo
 * @property integer $idbaja
 * @property Motivos $Motivos
 * @property BajasAlumnos $BajasAlumnos
 * 
 * @method integer      getIdmotivo()     Returns the current record's "idmotivo" value
 * @method integer      getIdbaja()       Returns the current record's "idbaja" value
 * @method Motivos      getMotivos()      Returns the current record's "Motivos" value
 * @method BajasAlumnos getBajasAlumnos() Returns the current record's "BajasAlumnos" value
 * @method MotivosBajas setIdmotivo()     Sets the current record's "idmotivo" value
 * @method MotivosBajas setIdbaja()       Sets the current record's "idbaja" value
 * @method MotivosBajas setMotivos()      Sets the current record's "Motivos" value
 * @method MotivosBajas setBajasAlumnos() Sets the current record's "BajasAlumnos" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotivosBajas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('motivos_bajas');
        $this->hasColumn('idmotivo', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idbaja', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Motivos', array(
             'local' => 'idmotivo',
             'foreign' => 'idmotivo'));

        $this->hasOne('BajasAlumnos', array(
             'local' => 'idbaja',
             'foreign' => 'idbaja'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}