<?php

/**
 * BaseClases
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idclase
 * @property integer $idasignacion
 * @property date $fecha
 * @property string $tema
 * @property string $temaplanificado
 * @property integer $horasdictadas
 * @property boolean $activo
 * @property AsignacionesClases $AsignacionesClases
 * 
 * @method integer            getIdclase()            Returns the current record's "idclase" value
 * @method integer            getIdasignacion()       Returns the current record's "idasignacion" value
 * @method date               getFecha()              Returns the current record's "fecha" value
 * @method string             getTema()               Returns the current record's "tema" value
 * @method string             getTemaplanificado()    Returns the current record's "temaplanificado" value
 * @method integer            getHorasdictadas()      Returns the current record's "horasdictadas" value
 * @method boolean            getActivo()             Returns the current record's "activo" value
 * @method AsignacionesClases getAsignacionesClases() Returns the current record's "AsignacionesClases" value
 * @method Clases             setIdclase()            Sets the current record's "idclase" value
 * @method Clases             setIdasignacion()       Sets the current record's "idasignacion" value
 * @method Clases             setFecha()              Sets the current record's "fecha" value
 * @method Clases             setTema()               Sets the current record's "tema" value
 * @method Clases             setTemaplanificado()    Sets the current record's "temaplanificado" value
 * @method Clases             setHorasdictadas()      Sets the current record's "horasdictadas" value
 * @method Clases             setActivo()             Sets the current record's "activo" value
 * @method Clases             setAsignacionesClases() Sets the current record's "AsignacionesClases" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClases extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clases');
        $this->hasColumn('idclase', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idasignacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('tema', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('temaplanificado', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('horasdictadas', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AsignacionesClases', array(
             'local' => 'idasignacion',
             'foreign' => 'idasignacion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}