<?php

/**
 * BaseEmpleadosSede
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idempleado
 * @property integer $idsede
 * @property Empleados $Empleados
 * @property Sedes $Sedes
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getIdempleado() Returns the current record's "idempleado" value
 * @method integer       getIdsede()     Returns the current record's "idsede" value
 * @method Empleados     getEmpleados()  Returns the current record's "Empleados" value
 * @method Sedes         getSedes()      Returns the current record's "Sedes" value
 * @method EmpleadosSede setId()         Sets the current record's "id" value
 * @method EmpleadosSede setIdempleado() Sets the current record's "idempleado" value
 * @method EmpleadosSede setIdsede()     Sets the current record's "idsede" value
 * @method EmpleadosSede setEmpleados()  Sets the current record's "Empleados" value
 * @method EmpleadosSede setSedes()      Sets the current record's "Sedes" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleadosSede extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleados_sede');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idempleado', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idsede', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empleados', array(
             'local' => 'idempleado',
             'foreign' => 'idempleado'));

        $this->hasOne('Sedes', array(
             'local' => 'idsede',
             'foreign' => 'idsede'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}