<?php

/**
 * BaseExpedientesEgresados
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idexpediente
 * @property integer $idtitulo
 * @property integer $idalumno
 * @property integer $idsede
 * @property date $fechaegreso
 * @property date $fechainformeauditoria
 * @property date $fechasolicitud
 * @property date $fechaentregatitulo
 * @property date $fechaenviome
 * @property date $fecharecibidome
 * @property integer $idderivacionbiblioteca
 * @property integer $idderivacionadministracion
 * @property integer $folio
 * @property string $otradocumentacion
 * @property string $observaciones
 * @property integer $activo
 * @property string $registrodiplomame
 * @property string $registrome
 * @property string $registrocertificadome
 * @property string $nrorecibo1
 * @property string $nrorecibo2
 * @property Titulos $Titulos
 * @property Alumnos $Alumnos
 * @property Sedes $Sedes
 * @property Doctrine_Collection $ExpedientesDerivaciones
 * 
 * @method integer              getIdexpediente()               Returns the current record's "idexpediente" value
 * @method integer              getIdtitulo()                   Returns the current record's "idtitulo" value
 * @method integer              getIdalumno()                   Returns the current record's "idalumno" value
 * @method integer              getIdsede()                     Returns the current record's "idsede" value
 * @method date                 getFechaegreso()                Returns the current record's "fechaegreso" value
 * @method date                 getFechainformeauditoria()      Returns the current record's "fechainformeauditoria" value
 * @method date                 getFechasolicitud()             Returns the current record's "fechasolicitud" value
 * @method date                 getFechaentregatitulo()         Returns the current record's "fechaentregatitulo" value
 * @method date                 getFechaenviome()               Returns the current record's "fechaenviome" value
 * @method date                 getFecharecibidome()            Returns the current record's "fecharecibidome" value
 * @method integer              getIdderivacionbiblioteca()     Returns the current record's "idderivacionbiblioteca" value
 * @method integer              getIdderivacionadministracion() Returns the current record's "idderivacionadministracion" value
 * @method integer              getFolio()                      Returns the current record's "folio" value
 * @method string               getOtradocumentacion()          Returns the current record's "otradocumentacion" value
 * @method string               getObservaciones()              Returns the current record's "observaciones" value
 * @method integer              getActivo()                     Returns the current record's "activo" value
 * @method string               getRegistrodiplomame()          Returns the current record's "registrodiplomame" value
 * @method string               getRegistrome()                 Returns the current record's "registrome" value
 * @method string               getRegistrocertificadome()      Returns the current record's "registrocertificadome" value
 * @method string               getNrorecibo1()                 Returns the current record's "nrorecibo1" value
 * @method string               getNrorecibo2()                 Returns the current record's "nrorecibo2" value
 * @method Titulos              getTitulos()                    Returns the current record's "Titulos" value
 * @method Alumnos              getAlumnos()                    Returns the current record's "Alumnos" value
 * @method Sedes                getSedes()                      Returns the current record's "Sedes" value
 * @method Doctrine_Collection  getExpedientesDerivaciones()    Returns the current record's "ExpedientesDerivaciones" collection
 * @method ExpedientesEgresados setIdexpediente()               Sets the current record's "idexpediente" value
 * @method ExpedientesEgresados setIdtitulo()                   Sets the current record's "idtitulo" value
 * @method ExpedientesEgresados setIdalumno()                   Sets the current record's "idalumno" value
 * @method ExpedientesEgresados setIdsede()                     Sets the current record's "idsede" value
 * @method ExpedientesEgresados setFechaegreso()                Sets the current record's "fechaegreso" value
 * @method ExpedientesEgresados setFechainformeauditoria()      Sets the current record's "fechainformeauditoria" value
 * @method ExpedientesEgresados setFechasolicitud()             Sets the current record's "fechasolicitud" value
 * @method ExpedientesEgresados setFechaentregatitulo()         Sets the current record's "fechaentregatitulo" value
 * @method ExpedientesEgresados setFechaenviome()               Sets the current record's "fechaenviome" value
 * @method ExpedientesEgresados setFecharecibidome()            Sets the current record's "fecharecibidome" value
 * @method ExpedientesEgresados setIdderivacionbiblioteca()     Sets the current record's "idderivacionbiblioteca" value
 * @method ExpedientesEgresados setIdderivacionadministracion() Sets the current record's "idderivacionadministracion" value
 * @method ExpedientesEgresados setFolio()                      Sets the current record's "folio" value
 * @method ExpedientesEgresados setOtradocumentacion()          Sets the current record's "otradocumentacion" value
 * @method ExpedientesEgresados setObservaciones()              Sets the current record's "observaciones" value
 * @method ExpedientesEgresados setActivo()                     Sets the current record's "activo" value
 * @method ExpedientesEgresados setRegistrodiplomame()          Sets the current record's "registrodiplomame" value
 * @method ExpedientesEgresados setRegistrome()                 Sets the current record's "registrome" value
 * @method ExpedientesEgresados setRegistrocertificadome()      Sets the current record's "registrocertificadome" value
 * @method ExpedientesEgresados setNrorecibo1()                 Sets the current record's "nrorecibo1" value
 * @method ExpedientesEgresados setNrorecibo2()                 Sets the current record's "nrorecibo2" value
 * @method ExpedientesEgresados setTitulos()                    Sets the current record's "Titulos" value
 * @method ExpedientesEgresados setAlumnos()                    Sets the current record's "Alumnos" value
 * @method ExpedientesEgresados setSedes()                      Sets the current record's "Sedes" value
 * @method ExpedientesEgresados setExpedientesDerivaciones()    Sets the current record's "ExpedientesDerivaciones" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpedientesEgresados extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expedientes_egresados');
        $this->hasColumn('idexpediente', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idtitulo', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idsede', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fechaegreso', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fechainformeauditoria', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fechasolicitud', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fechaentregatitulo', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fechaenviome', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fecharecibidome', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('idderivacionbiblioteca', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idderivacionadministracion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('folio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('otradocumentacion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('observaciones', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('activo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             ));
        $this->hasColumn('registrodiplomame', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('registrome', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('registrocertificadome', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('nrorecibo1', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('nrorecibo2', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Titulos', array(
             'local' => 'idtitulo',
             'foreign' => 'idtitulo'));

        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $this->hasOne('Sedes', array(
             'local' => 'idsede',
             'foreign' => 'idsede'));

        $this->hasMany('ExpedientesDerivaciones', array(
             'local' => 'idexpediente',
             'foreign' => 'idexpediente'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}