<?php

/**
 * BaseMeses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mes
 * @property string $descripcion
 * 
 * @method integer getMes()         Returns the current record's "mes" value
 * @method string  getDescripcion() Returns the current record's "descripcion" value
 * @method Meses   setMes()         Sets the current record's "mes" value
 * @method Meses   setDescripcion() Sets the current record's "descripcion" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMeses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meses');
        $this->hasColumn('mes', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}