<?php

/**
 * BaseInscripcionesCicloLectivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idalumno
 * @property integer $idciclolectivo
 * @property date $fecha
 * @property time $hora
 * @property CiclosLectivos $CiclosLectivos
 * @property Alumnos $Alumnos
 * 
 * @method integer                   getIdalumno()       Returns the current record's "idalumno" value
 * @method integer                   getIdciclolectivo() Returns the current record's "idciclolectivo" value
 * @method date                      getFecha()          Returns the current record's "fecha" value
 * @method time                      getHora()           Returns the current record's "hora" value
 * @method CiclosLectivos            getCiclosLectivos() Returns the current record's "CiclosLectivos" value
 * @method Alumnos                   getAlumnos()        Returns the current record's "Alumnos" value
 * @method InscripcionesCicloLectivo setIdalumno()       Sets the current record's "idalumno" value
 * @method InscripcionesCicloLectivo setIdciclolectivo() Sets the current record's "idciclolectivo" value
 * @method InscripcionesCicloLectivo setFecha()          Sets the current record's "fecha" value
 * @method InscripcionesCicloLectivo setHora()           Sets the current record's "hora" value
 * @method InscripcionesCicloLectivo setCiclosLectivos() Sets the current record's "CiclosLectivos" value
 * @method InscripcionesCicloLectivo setAlumnos()        Sets the current record's "Alumnos" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInscripcionesCicloLectivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inscripciones_ciclo_lectivo');
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('idciclolectivo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CiclosLectivos', array(
             'local' => 'idciclolectivo',
             'foreign' => 'id'));

        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}