<?php

/**
 * BasePeriodosCursadas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idfecha
 * @property integer $periododecursada
 * @property FechasCalendario $FechasCalendario
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getIdfecha()          Returns the current record's "idfecha" value
 * @method integer          getPeriododecursada() Returns the current record's "periododecursada" value
 * @method FechasCalendario getFechasCalendario() Returns the current record's "FechasCalendario" value
 * @method PeriodosCursadas setId()               Sets the current record's "id" value
 * @method PeriodosCursadas setIdfecha()          Sets the current record's "idfecha" value
 * @method PeriodosCursadas setPeriododecursada() Sets the current record's "periododecursada" value
 * @method PeriodosCursadas setFechasCalendario() Sets the current record's "FechasCalendario" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeriodosCursadas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periodos_cursadas');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idfecha', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('periododecursada', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FechasCalendario', array(
             'local' => 'idfecha',
             'foreign' => 'idfecha'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}