<?php

/**
 * BaseHistoricoConsultas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $persona
 * @property string $carrera
 * @property string $mensaje
 * @property string $usuario
 * 
 * @method string             getPersona() Returns the current record's "persona" value
 * @method string             getCarrera() Returns the current record's "carrera" value
 * @method string             getMensaje() Returns the current record's "mensaje" value
 * @method string             getUsuario() Returns the current record's "usuario" value
 * @method HistoricoConsultas setPersona() Sets the current record's "persona" value
 * @method HistoricoConsultas setCarrera() Sets the current record's "carrera" value
 * @method HistoricoConsultas setMensaje() Sets the current record's "mensaje" value
 * @method HistoricoConsultas setUsuario() Sets the current record's "usuario" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHistoricoConsultas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('historico_consultas');
        $this->hasColumn('persona', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('carrera', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('mensaje', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('usuario', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}