<?php

/**
 * BaseSolicitudes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcarrera
 * @property integer $idusuario
 * @property integer $idsede
 * @property string $descripcion
 * @property boolean $resuelta
 * @property string $respuesta
 * @property boolean $is_active
 * 
 * @method integer     getIdcarrera()   Returns the current record's "idcarrera" value
 * @method integer     getIdusuario()   Returns the current record's "idusuario" value
 * @method integer     getIdsede()      Returns the current record's "idsede" value
 * @method string      getDescripcion() Returns the current record's "descripcion" value
 * @method boolean     getResuelta()    Returns the current record's "resuelta" value
 * @method string      getRespuesta()   Returns the current record's "respuesta" value
 * @method boolean     getIsActive()    Returns the current record's "is_active" value
 * @method Solicitudes setIdcarrera()   Sets the current record's "idcarrera" value
 * @method Solicitudes setIdusuario()   Sets the current record's "idusuario" value
 * @method Solicitudes setIdsede()      Sets the current record's "idsede" value
 * @method Solicitudes setDescripcion() Sets the current record's "descripcion" value
 * @method Solicitudes setResuelta()    Sets the current record's "resuelta" value
 * @method Solicitudes setRespuesta()   Sets the current record's "respuesta" value
 * @method Solicitudes setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSolicitudes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('solicitudes');
        $this->hasColumn('idcarrera', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idusuario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idsede', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('resuelta', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('respuesta', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}