<?php

/**
 * BaseTiposMaterias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipomateria
 * @property string $descripcion
 * @property Doctrine_Collection $TiposMaterias
 * 
 * @method integer             getIdtipomateria() Returns the current record's "idtipomateria" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTiposMaterias() Returns the current record's "TiposMaterias" collection
 * @method TiposMaterias       setIdtipomateria() Sets the current record's "idtipomateria" value
 * @method TiposMaterias       setDescripcion()   Sets the current record's "descripcion" value
 * @method TiposMaterias       setTiposMaterias() Sets the current record's "TiposMaterias" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposMaterias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_materias');
        $this->hasColumn('idtipomateria', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MateriasPlanes as TiposMaterias', array(
             'local' => 'idtipomateria',
             'foreign' => 'idtipomateria'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}