<?php

/**
 * BaseFacultades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idfacultad
 * @property string $nombre
 * @property string $decano
 * @property string $nombreabrev
 * @property Doctrine_Collection $Facultades
 * 
 * @method integer             getIdfacultad()  Returns the current record's "idfacultad" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDecano()      Returns the current record's "decano" value
 * @method string              getNombreabrev() Returns the current record's "nombreabrev" value
 * @method Doctrine_Collection getFacultades()  Returns the current record's "Facultades" collection
 * @method Facultades          setIdfacultad()  Sets the current record's "idfacultad" value
 * @method Facultades          setNombre()      Sets the current record's "nombre" value
 * @method Facultades          setDecano()      Sets the current record's "decano" value
 * @method Facultades          setNombreabrev() Sets the current record's "nombreabrev" value
 * @method Facultades          setFacultades()  Sets the current record's "Facultades" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacultades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facultades');
        $this->hasColumn('idfacultad', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('decano', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('nombreabrev', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Carreras as Facultades', array(
             'local' => 'idfacultad',
             'foreign' => 'idfacultad'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}