<?php

/**
 * BaseMaterias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmateria
 * @property string $nombre
 * @property string $nombrereducido
 * @property string $contenidominimo
 * @property Doctrine_Collection $Materias
 * 
 * @method integer             getIdmateria()       Returns the current record's "idmateria" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getNombrereducido()  Returns the current record's "nombrereducido" value
 * @method string              getContenidominimo() Returns the current record's "contenidominimo" value
 * @method Doctrine_Collection getMaterias()        Returns the current record's "Materias" collection
 * @method Materias            setIdmateria()       Sets the current record's "idmateria" value
 * @method Materias            setNombre()          Sets the current record's "nombre" value
 * @method Materias            setNombrereducido()  Sets the current record's "nombrereducido" value
 * @method Materias            setContenidominimo() Sets the current record's "contenidominimo" value
 * @method Materias            setMaterias()        Sets the current record's "Materias" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaterias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materias');
        $this->hasColumn('idmateria', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('nombrereducido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('contenidominimo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MateriasPlanes as Materias', array(
             'local' => 'idmateria',
             'foreign' => 'idmateria'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}