<?php

/**
 * BaseLibrosActas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idlibroacta
 * @property string $descripcion
 * @property integer $idarea
 * @property Areas $Areas
 * @property Doctrine_Collection $LibrosActas
 * 
 * @method integer             getIdlibroacta() Returns the current record's "idlibroacta" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method integer             getIdarea()      Returns the current record's "idarea" value
 * @method Areas               getAreas()       Returns the current record's "Areas" value
 * @method Doctrine_Collection getLibrosActas() Returns the current record's "LibrosActas" collection
 * @method LibrosActas         setIdlibroacta() Sets the current record's "idlibroacta" value
 * @method LibrosActas         setDescripcion() Sets the current record's "descripcion" value
 * @method LibrosActas         setIdarea()      Sets the current record's "idarea" value
 * @method LibrosActas         setAreas()       Sets the current record's "Areas" value
 * @method LibrosActas         setLibrosActas() Sets the current record's "LibrosActas" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibrosActas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('libros_actas');
        $this->hasColumn('idlibroacta', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('idarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Areas', array(
             'local' => 'idarea',
             'foreign' => 'idarea'));

        $this->hasMany('MesasExamenes as LibrosActas', array(
             'local' => 'idlibroacta',
             'foreign' => 'idlibroacta'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}