<?php

/**
 * BaseLogEventosDesignaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $sede
 * @property string $facultad
 * @property integer $idfacultad
 * @property integer $idsede
 * @property string $estado
 * @property string $observaciones
 * @property string $origen
 * @property string $destinatario
 * 
 * @method integer                 getId()            Returns the current record's "id" value
 * @method string                  getSede()          Returns the current record's "sede" value
 * @method string                  getFacultad()      Returns the current record's "facultad" value
 * @method integer                 getIdfacultad()    Returns the current record's "idfacultad" value
 * @method integer                 getIdsede()        Returns the current record's "idsede" value
 * @method string                  getEstado()        Returns the current record's "estado" value
 * @method string                  getObservaciones() Returns the current record's "observaciones" value
 * @method string                  getOrigen()        Returns the current record's "origen" value
 * @method string                  getDestinatario()  Returns the current record's "destinatario" value
 * @method LogEventosDesignaciones setId()            Sets the current record's "id" value
 * @method LogEventosDesignaciones setSede()          Sets the current record's "sede" value
 * @method LogEventosDesignaciones setFacultad()      Sets the current record's "facultad" value
 * @method LogEventosDesignaciones setIdfacultad()    Sets the current record's "idfacultad" value
 * @method LogEventosDesignaciones setIdsede()        Sets the current record's "idsede" value
 * @method LogEventosDesignaciones setEstado()        Sets the current record's "estado" value
 * @method LogEventosDesignaciones setObservaciones() Sets the current record's "observaciones" value
 * @method LogEventosDesignaciones setOrigen()        Sets the current record's "origen" value
 * @method LogEventosDesignaciones setDestinatario()  Sets the current record's "destinatario" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogEventosDesignaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log_eventos_designaciones');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sede', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('facultad', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('idfacultad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idsede', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('estado', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('observaciones', 'string', 1000, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 1000,
             ));
        $this->hasColumn('origen', 'string', 200, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('destinatario', 'string', 200, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}