<?php

/**
 * BaseTransicionesMaterias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtransicionmateria
 * @property integer $idtransicionplan
 * @property integer $idmateriaorigen
 * @property integer $idmateriadestino
 * @property integer $valormateria
 * @property TransicionesPlanes $TransicionesPlanes
 * 
 * @method integer              getIdtransicionmateria() Returns the current record's "idtransicionmateria" value
 * @method integer              getIdtransicionplan()    Returns the current record's "idtransicionplan" value
 * @method integer              getIdmateriaorigen()     Returns the current record's "idmateriaorigen" value
 * @method integer              getIdmateriadestino()    Returns the current record's "idmateriadestino" value
 * @method integer              getValormateria()        Returns the current record's "valormateria" value
 * @method TransicionesPlanes   getTransicionesPlanes()  Returns the current record's "TransicionesPlanes" value
 * @method TransicionesMaterias setIdtransicionmateria() Sets the current record's "idtransicionmateria" value
 * @method TransicionesMaterias setIdtransicionplan()    Sets the current record's "idtransicionplan" value
 * @method TransicionesMaterias setIdmateriaorigen()     Sets the current record's "idmateriaorigen" value
 * @method TransicionesMaterias setIdmateriadestino()    Sets the current record's "idmateriadestino" value
 * @method TransicionesMaterias setValormateria()        Sets the current record's "valormateria" value
 * @method TransicionesMaterias setTransicionesPlanes()  Sets the current record's "TransicionesPlanes" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransicionesMaterias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transiciones_materias');
        $this->hasColumn('idtransicionmateria', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idtransicionplan', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idmateriaorigen', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idmateriadestino', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('valormateria', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TransicionesPlanes', array(
             'local' => 'idtransicionplan',
             'foreign' => 'idtransicionplan'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}