<?php

/**
 * BaseTiposClases
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoclase
 * @property string $descripcion
 * @property Doctrine_Collection $TiposClases
 * 
 * @method integer             getIdtipoclase() Returns the current record's "idtipoclase" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTiposClases() Returns the current record's "TiposClases" collection
 * @method TiposClases         setIdtipoclase() Sets the current record's "idtipoclase" value
 * @method TiposClases         setDescripcion() Sets the current record's "descripcion" value
 * @method TiposClases         setTiposClases() Sets the current record's "TiposClases" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposClases extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_clases');
        $this->hasColumn('idtipoclase', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AsignacionesClases as TiposClases', array(
             'local' => 'idtipoclase',
             'foreign' => 'idtipoclase'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}