<?php

/**
 * BaseEscalasNotas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idescalanota
 * @property string $nombre
 * @property boolean $activo
 * @property Doctrine_Collection $EscalasNotas
 * 
 * @method integer             getIdescalanota() Returns the current record's "idescalanota" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method boolean             getActivo()       Returns the current record's "activo" value
 * @method Doctrine_Collection getEscalasNotas() Returns the current record's "EscalasNotas" collection
 * @method EscalasNotas        setIdescalanota() Sets the current record's "idescalanota" value
 * @method EscalasNotas        setNombre()       Sets the current record's "nombre" value
 * @method EscalasNotas        setActivo()       Sets the current record's "activo" value
 * @method EscalasNotas        setEscalasNotas() Sets the current record's "EscalasNotas" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEscalasNotas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('escalas_notas');
        $this->hasColumn('idescalanota', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'primary' => false,
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PlanesEstudios as EscalasNotas', array(
             'local' => 'idescalanota',
             'foreign' => 'idescalanota'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}