<?php

/**
 * BaseEstadosEquivalencias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idestadoequivalencia
 * @property string $descripcion
 * @property Doctrine_Collection $EstadosEquivalencias
 * 
 * @method integer              getIdestadoequivalencia() Returns the current record's "idestadoequivalencia" value
 * @method string               getDescripcion()          Returns the current record's "descripcion" value
 * @method Doctrine_Collection  getEstadosEquivalencias() Returns the current record's "EstadosEquivalencias" collection
 * @method EstadosEquivalencias setIdestadoequivalencia() Sets the current record's "idestadoequivalencia" value
 * @method EstadosEquivalencias setDescripcion()          Sets the current record's "descripcion" value
 * @method EstadosEquivalencias setEstadosEquivalencias() Sets the current record's "EstadosEquivalencias" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadosEquivalencias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estados_equivalencias');
        $this->hasColumn('idestadoequivalencia', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MateriasEquivalencias as EstadosEquivalencias', array(
             'local' => 'idestadoequivalencia',
             'foreign' => 'idestadoequivalencia'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}