<?php

/**
 * BaseHorarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpersona
 * @property boolean $anulado
 * @property string $tiporegistro
 * @property string $observaciones
 * @property Personas $Personas
 * 
 * @method integer  getIdpersona()     Returns the current record's "idpersona" value
 * @method boolean  getAnulado()       Returns the current record's "anulado" value
 * @method string   getTiporegistro()  Returns the current record's "tiporegistro" value
 * @method string   getObservaciones() Returns the current record's "observaciones" value
 * @method Personas getPersonas()      Returns the current record's "Personas" value
 * @method Horarios setIdpersona()     Sets the current record's "idpersona" value
 * @method Horarios setAnulado()       Sets the current record's "anulado" value
 * @method Horarios setTiporegistro()  Sets the current record's "tiporegistro" value
 * @method Horarios setObservaciones() Sets the current record's "observaciones" value
 * @method Horarios setPersonas()      Sets the current record's "Personas" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHorarios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('horarios');
        $this->hasColumn('idpersona', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             'default' => '1',
             ));
        $this->hasColumn('anulado', 'boolean', null, array(
             'type' => 'boolean',
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('tiporegistro', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('observaciones', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Personas', array(
             'local' => 'idpersona',
             'foreign' => 'idpersona'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}