<?php

/**
 * BaseNoticiasCarrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idnoticia
 * @property integer $idcarrera
 * @property Noticias $Noticias
 * @property Carreras $Carreras
 * 
 * @method integer         getIdnoticia() Returns the current record's "idnoticia" value
 * @method integer         getIdcarrera() Returns the current record's "idcarrera" value
 * @method Noticias        getNoticias()  Returns the current record's "Noticias" value
 * @method Carreras        getCarreras()  Returns the current record's "Carreras" value
 * @method NoticiasCarrera setIdnoticia() Sets the current record's "idnoticia" value
 * @method NoticiasCarrera setIdcarrera() Sets the current record's "idcarrera" value
 * @method NoticiasCarrera setNoticias()  Sets the current record's "Noticias" value
 * @method NoticiasCarrera setCarreras()  Sets the current record's "Carreras" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticiasCarrera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticias_carrera');
        $this->hasColumn('idnoticia', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idcarrera', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Noticias', array(
             'local' => 'idnoticia',
             'foreign' => 'id'));

        $this->hasOne('Carreras', array(
             'local' => 'idcarrera',
             'foreign' => 'idcarrera'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}