<?php

/**
 * BaseMateriasEquivalencias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idequivalencia
 * @property integer $idmateriaplan
 * @property integer $idestadoequivalencia
 * @property date $fecha
 * @property EquivalenciasAlumnos $EquivalenciasAlumnos
 * @property MateriasPlanes $MateriasPlanes
 * @property EstadosEquivalencias $EstadosEquivalencias
 * 
 * @method integer               getId()                   Returns the current record's "id" value
 * @method integer               getIdequivalencia()       Returns the current record's "idequivalencia" value
 * @method integer               getIdmateriaplan()        Returns the current record's "idmateriaplan" value
 * @method integer               getIdestadoequivalencia() Returns the current record's "idestadoequivalencia" value
 * @method date                  getFecha()                Returns the current record's "fecha" value
 * @method EquivalenciasAlumnos  getEquivalenciasAlumnos() Returns the current record's "EquivalenciasAlumnos" value
 * @method MateriasPlanes        getMateriasPlanes()       Returns the current record's "MateriasPlanes" value
 * @method EstadosEquivalencias  getEstadosEquivalencias() Returns the current record's "EstadosEquivalencias" value
 * @method MateriasEquivalencias setId()                   Sets the current record's "id" value
 * @method MateriasEquivalencias setIdequivalencia()       Sets the current record's "idequivalencia" value
 * @method MateriasEquivalencias setIdmateriaplan()        Sets the current record's "idmateriaplan" value
 * @method MateriasEquivalencias setIdestadoequivalencia() Sets the current record's "idestadoequivalencia" value
 * @method MateriasEquivalencias setFecha()                Sets the current record's "fecha" value
 * @method MateriasEquivalencias setEquivalenciasAlumnos() Sets the current record's "EquivalenciasAlumnos" value
 * @method MateriasEquivalencias setMateriasPlanes()       Sets the current record's "MateriasPlanes" value
 * @method MateriasEquivalencias setEstadosEquivalencias() Sets the current record's "EstadosEquivalencias" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMateriasEquivalencias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materias_equivalencias');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idequivalencia', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idmateriaplan', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idestadoequivalencia', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EquivalenciasAlumnos', array(
             'local' => 'idequivalencia',
             'foreign' => 'idequivalencia'));

        $this->hasOne('MateriasPlanes', array(
             'local' => 'idmateriaplan',
             'foreign' => 'idmateriaplan'));

        $this->hasOne('EstadosEquivalencias', array(
             'local' => 'idestadoequivalencia',
             'foreign' => 'idestadoequivalencia'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}