<?php

/**
 * BaseSexo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idsexo
 * @property string $nombre
 * @property Doctrine_Collection $Sexo
 * 
 * @method integer             getIdsexo() Returns the current record's "idsexo" value
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getSexo()   Returns the current record's "Sexo" collection
 * @method Sexo                setIdsexo() Sets the current record's "idsexo" value
 * @method Sexo                setNombre() Sets the current record's "nombre" value
 * @method Sexo                setSexo()   Sets the current record's "Sexo" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSexo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sexo');
        $this->hasColumn('idsexo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Personas as Sexo', array(
             'local' => 'idsexo',
             'foreign' => 'idsexo'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}