<?php

/**
 * BaseMotivos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmotivo
 * @property string $descripcion
 * @property Doctrine_Collection $Motivos
 * 
 * @method integer             getIdmotivo()    Returns the current record's "idmotivo" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getMotivos()     Returns the current record's "Motivos" collection
 * @method Motivos             setIdmotivo()    Sets the current record's "idmotivo" value
 * @method Motivos             setDescripcion() Sets the current record's "descripcion" value
 * @method Motivos             setMotivos()     Sets the current record's "Motivos" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotivos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('motivos');
        $this->hasColumn('idmotivo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MotivosBajas as Motivos', array(
             'local' => 'idmotivo',
             'foreign' => 'idmotivo'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}