<?php

/**
 * BaseFichaCarga
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idficha
 * @property integer $idalumno
 * @property integer $idmateriaplan
 * @property integer $idlibroacta
 * @property date $fecha
 * @property string $folio
 * @property string $promedio
 * @property integer $idestadomateria
 * @property date $fechavencimiento
 * @property boolean $controlado
 * @property boolean $transferido
 * @property string $comentarios
 * @property MateriasPlanes $MateriasPlanes
 * @property LibrosActas $LibrosActas
 * @property EstadosMateria $EstadosMateria
 * 
 * @method integer        getIdficha()          Returns the current record's "idficha" value
 * @method integer        getIdalumno()         Returns the current record's "idalumno" value
 * @method integer        getIdmateriaplan()    Returns the current record's "idmateriaplan" value
 * @method integer        getIdlibroacta()      Returns the current record's "idlibroacta" value
 * @method date           getFecha()            Returns the current record's "fecha" value
 * @method string         getFolio()            Returns the current record's "folio" value
 * @method string         getPromedio()         Returns the current record's "promedio" value
 * @method integer        getIdestadomateria()  Returns the current record's "idestadomateria" value
 * @method date           getFechavencimiento() Returns the current record's "fechavencimiento" value
 * @method boolean        getControlado()       Returns the current record's "controlado" value
 * @method boolean        getTransferido()      Returns the current record's "transferido" value
 * @method string         getComentarios()      Returns the current record's "comentarios" value
 * @method MateriasPlanes getMateriasPlanes()   Returns the current record's "MateriasPlanes" value
 * @method LibrosActas    getLibrosActas()      Returns the current record's "LibrosActas" value
 * @method EstadosMateria getEstadosMateria()   Returns the current record's "EstadosMateria" value
 * @method FichaCarga     setIdficha()          Sets the current record's "idficha" value
 * @method FichaCarga     setIdalumno()         Sets the current record's "idalumno" value
 * @method FichaCarga     setIdmateriaplan()    Sets the current record's "idmateriaplan" value
 * @method FichaCarga     setIdlibroacta()      Sets the current record's "idlibroacta" value
 * @method FichaCarga     setFecha()            Sets the current record's "fecha" value
 * @method FichaCarga     setFolio()            Sets the current record's "folio" value
 * @method FichaCarga     setPromedio()         Sets the current record's "promedio" value
 * @method FichaCarga     setIdestadomateria()  Sets the current record's "idestadomateria" value
 * @method FichaCarga     setFechavencimiento() Sets the current record's "fechavencimiento" value
 * @method FichaCarga     setControlado()       Sets the current record's "controlado" value
 * @method FichaCarga     setTransferido()      Sets the current record's "transferido" value
 * @method FichaCarga     setComentarios()      Sets the current record's "comentarios" value
 * @method FichaCarga     setMateriasPlanes()   Sets the current record's "MateriasPlanes" value
 * @method FichaCarga     setLibrosActas()      Sets the current record's "LibrosActas" value
 * @method FichaCarga     setEstadosMateria()   Sets the current record's "EstadosMateria" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFichaCarga extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ficha_carga');
        $this->hasColumn('idficha', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('idmateriaplan', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('idlibroacta', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('folio', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('promedio', 'string', 10, array(
             'type' => 'string',
             'default' => '',
             'length' => 10,
             ));
        $this->hasColumn('idestadomateria', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fechavencimiento', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('controlado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('transferido', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('comentarios', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 200,
             ));


        $this->index('uc_aprobadas', array(
             'fields' => 
             array(
              0 => 'idalumno',
              1 => 'idmateriaplan',
              2 => 'idestadomateria',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MateriasPlanes', array(
             'local' => 'idmateriaplan',
             'foreign' => 'idmateriaplan'));

        $this->hasOne('LibrosActas', array(
             'local' => 'idlibroacta',
             'foreign' => 'idlibroacta'));

        $this->hasOne('EstadosMateria', array(
             'local' => 'idestadomateria',
             'foreign' => 'idestadomateria'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}