<?php

/**
 * BaseDocumentacionAlumnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddocumentacion
 * @property integer $idalumno
 * @property boolean $activo
 * @property Documentacion $Documentacion
 * @property Alumnos $Alumnos
 * 
 * @method integer              getIddocumentacion() Returns the current record's "iddocumentacion" value
 * @method integer              getIdalumno()        Returns the current record's "idalumno" value
 * @method boolean              getActivo()          Returns the current record's "activo" value
 * @method Documentacion        getDocumentacion()   Returns the current record's "Documentacion" value
 * @method Alumnos              getAlumnos()         Returns the current record's "Alumnos" value
 * @method DocumentacionAlumnos setIddocumentacion() Sets the current record's "iddocumentacion" value
 * @method DocumentacionAlumnos setIdalumno()        Sets the current record's "idalumno" value
 * @method DocumentacionAlumnos setActivo()          Sets the current record's "activo" value
 * @method DocumentacionAlumnos setDocumentacion()   Sets the current record's "Documentacion" value
 * @method DocumentacionAlumnos setAlumnos()         Sets the current record's "Alumnos" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentacionAlumnos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentacion_alumnos');
        $this->hasColumn('iddocumentacion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Documentacion', array(
             'local' => 'iddocumentacion',
             'foreign' => 'iddocumentacion'));

        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}