<?php

/**
 * BaseEstadosMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idestadomateria
 * @property string $descripcion
 * @property Doctrine_Collection $EstadosMateria
 * 
 * @method integer             getIdestadomateria() Returns the current record's "idestadomateria" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEstadosMateria()  Returns the current record's "EstadosMateria" collection
 * @method EstadosMateria      setIdestadomateria() Sets the current record's "idestadomateria" value
 * @method EstadosMateria      setDescripcion()     Sets the current record's "descripcion" value
 * @method EstadosMateria      setEstadosMateria()  Sets the current record's "EstadosMateria" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadosMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estados_materia');
        $this->hasColumn('idestadomateria', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AluMat as EstadosMateria', array(
             'local' => 'idestadomateria',
             'foreign' => 'idestadomateria'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}