<?php

/**
 * BaseCarreras
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcarrera
 * @property string $nombre
 * @property string $nombrereducido
 * @property integer $idfacultad
 * @property string $letra
 * @property string $titulo
 * @property integer $idtipocarrera
 * @property integer $idmodalidad
 * @property integer $termino
 * @property date $fechacreacion
 * @property date $fechabaja
 * @property string $nroresolucion
 * @property string $nroresolucionhcd
 * @property string $nroresolucioncsu
 * @property string $nroresolucionconeau
 * @property string $nroresolucionbaja
 * @property string $nroexpediente
 * @property integer $anioinicio
 * @property integer $idestadocarrera
 * @property Facultades $Facultades
 * @property AreasCarrera $AreasCarrera
 * @property TiposCarreras $TiposCarreras
 * @property ModalidadesCarreras $ModalidadesCarreras
 * @property EstadosCarreras $EstadosCarreras
 * @property Doctrine_Collection $Carreras
 * 
 * @method integer             getIdcarrera()           Returns the current record's "idcarrera" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method string              getNombrereducido()      Returns the current record's "nombrereducido" value
 * @method integer             getIdfacultad()          Returns the current record's "idfacultad" value
 * @method string              getLetra()               Returns the current record's "letra" value
 * @method string              getTitulo()              Returns the current record's "titulo" value
 * @method integer             getIdtipocarrera()       Returns the current record's "idtipocarrera" value
 * @method integer             getIdmodalidad()         Returns the current record's "idmodalidad" value
 * @method integer             getTermino()             Returns the current record's "termino" value
 * @method date                getFechacreacion()       Returns the current record's "fechacreacion" value
 * @method date                getFechabaja()           Returns the current record's "fechabaja" value
 * @method string              getNroresolucion()       Returns the current record's "nroresolucion" value
 * @method string              getNroresolucionhcd()    Returns the current record's "nroresolucionhcd" value
 * @method string              getNroresolucioncsu()    Returns the current record's "nroresolucioncsu" value
 * @method string              getNroresolucionconeau() Returns the current record's "nroresolucionconeau" value
 * @method string              getNroresolucionbaja()   Returns the current record's "nroresolucionbaja" value
 * @method string              getNroexpediente()       Returns the current record's "nroexpediente" value
 * @method integer             getAnioinicio()          Returns the current record's "anioinicio" value
 * @method integer             getIdestadocarrera()     Returns the current record's "idestadocarrera" value
 * @method Facultades          getFacultades()          Returns the current record's "Facultades" value
 * @method AreasCarrera        getAreasCarrera()        Returns the current record's "AreasCarrera" value
 * @method TiposCarreras       getTiposCarreras()       Returns the current record's "TiposCarreras" value
 * @method ModalidadesCarreras getModalidadesCarreras() Returns the current record's "ModalidadesCarreras" value
 * @method EstadosCarreras     getEstadosCarreras()     Returns the current record's "EstadosCarreras" value
 * @method Doctrine_Collection getCarreras()            Returns the current record's "Carreras" collection
 * @method Carreras            setIdcarrera()           Sets the current record's "idcarrera" value
 * @method Carreras            setNombre()              Sets the current record's "nombre" value
 * @method Carreras            setNombrereducido()      Sets the current record's "nombrereducido" value
 * @method Carreras            setIdfacultad()          Sets the current record's "idfacultad" value
 * @method Carreras            setLetra()               Sets the current record's "letra" value
 * @method Carreras            setTitulo()              Sets the current record's "titulo" value
 * @method Carreras            setIdtipocarrera()       Sets the current record's "idtipocarrera" value
 * @method Carreras            setIdmodalidad()         Sets the current record's "idmodalidad" value
 * @method Carreras            setTermino()             Sets the current record's "termino" value
 * @method Carreras            setFechacreacion()       Sets the current record's "fechacreacion" value
 * @method Carreras            setFechabaja()           Sets the current record's "fechabaja" value
 * @method Carreras            setNroresolucion()       Sets the current record's "nroresolucion" value
 * @method Carreras            setNroresolucionhcd()    Sets the current record's "nroresolucionhcd" value
 * @method Carreras            setNroresolucioncsu()    Sets the current record's "nroresolucioncsu" value
 * @method Carreras            setNroresolucionconeau() Sets the current record's "nroresolucionconeau" value
 * @method Carreras            setNroresolucionbaja()   Sets the current record's "nroresolucionbaja" value
 * @method Carreras            setNroexpediente()       Sets the current record's "nroexpediente" value
 * @method Carreras            setAnioinicio()          Sets the current record's "anioinicio" value
 * @method Carreras            setIdestadocarrera()     Sets the current record's "idestadocarrera" value
 * @method Carreras            setFacultades()          Sets the current record's "Facultades" value
 * @method Carreras            setAreasCarrera()        Sets the current record's "AreasCarrera" value
 * @method Carreras            setTiposCarreras()       Sets the current record's "TiposCarreras" value
 * @method Carreras            setModalidadesCarreras() Sets the current record's "ModalidadesCarreras" value
 * @method Carreras            setEstadosCarreras()     Sets the current record's "EstadosCarreras" value
 * @method Carreras            setCarreras()            Sets the current record's "Carreras" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarreras extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carreras');
        $this->hasColumn('idcarrera', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nombrereducido', 'string', 200, array(
             'type' => 'string',
             'primary' => false,
             'length' => 200,
             ));
        $this->hasColumn('idfacultad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('letra', 'string', 2, array(
             'type' => 'string',
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('titulo', 'string', 200, array(
             'type' => 'string',
             'primary' => false,
             'length' => 200,
             ));
        $this->hasColumn('idtipocarrera', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('idmodalidad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('termino', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             ));
        $this->hasColumn('fechacreacion', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'default' => '2002-01-01',
             'length' => 25,
             ));
        $this->hasColumn('fechabaja', 'date', 25, array(
             'type' => 'date',
             'primary' => false,
             'notnull' => true,
             'default' => '2002-01-01',
             'length' => 25,
             ));
        $this->hasColumn('nroresolucion', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('nroresolucionhcd', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('nroresolucioncsu', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('nroresolucionconeau', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('nroresolucionbaja', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('nroexpediente', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('anioinicio', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idestadocarrera', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Facultades', array(
             'local' => 'idfacultad',
             'foreign' => 'idfacultad'));

        $this->hasOne('AreasCarrera', array(
             'local' => 'idcarrera',
             'foreign' => 'idcarrera'));

        $this->hasOne('TiposCarreras', array(
             'local' => 'idtipocarrera',
             'foreign' => 'idtipocarrera'));

        $this->hasOne('ModalidadesCarreras', array(
             'local' => 'idmodalidad',
             'foreign' => 'idmodalidad'));

        $this->hasOne('EstadosCarreras', array(
             'local' => 'idestadocarrera',
             'foreign' => 'idestadocarrera'));

        $this->hasMany('PlanesEstudios as Carreras', array(
             'local' => 'idcarrera',
             'foreign' => 'idcarrera'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}