<?php

/**
 * BaseEstadoAlumnoHistorial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idestadoalumno
 * @property integer $idalumno
 * @property date $fecha
 * @property EstadosAlumno $EstadosAlumno
 * @property Alumnos $Alumnos
 * 
 * @method integer               getIdestadoalumno() Returns the current record's "idestadoalumno" value
 * @method integer               getIdalumno()       Returns the current record's "idalumno" value
 * @method date                  getFecha()          Returns the current record's "fecha" value
 * @method EstadosAlumno         getEstadosAlumno()  Returns the current record's "EstadosAlumno" value
 * @method Alumnos               getAlumnos()        Returns the current record's "Alumnos" value
 * @method EstadoAlumnoHistorial setIdestadoalumno() Sets the current record's "idestadoalumno" value
 * @method EstadoAlumnoHistorial setIdalumno()       Sets the current record's "idalumno" value
 * @method EstadoAlumnoHistorial setFecha()          Sets the current record's "fecha" value
 * @method EstadoAlumnoHistorial setEstadosAlumno()  Sets the current record's "EstadosAlumno" value
 * @method EstadoAlumnoHistorial setAlumnos()        Sets the current record's "Alumnos" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoAlumnoHistorial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_alumno_historial');
        $this->hasColumn('idestadoalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idalumno', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EstadosAlumno', array(
             'local' => 'idestadoalumno',
             'foreign' => 'idestadoalumno'));

        $this->hasOne('Alumnos', array(
             'local' => 'idalumno',
             'foreign' => 'idalumno'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}