<?php

/**
 * BaseExpedientesDerivaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idderivacion
 * @property integer $idexpediente
 * @property integer $idareaorigen
 * @property integer $idareadestino
 * @property string $observaciones
 * @property boolean $activo
 * @property boolean $leido
 * @property ExpedientesEgresados $ExpedientesEgresados
 * 
 * @method integer                 getIdderivacion()         Returns the current record's "idderivacion" value
 * @method integer                 getIdexpediente()         Returns the current record's "idexpediente" value
 * @method integer                 getIdareaorigen()         Returns the current record's "idareaorigen" value
 * @method integer                 getIdareadestino()        Returns the current record's "idareadestino" value
 * @method string                  getObservaciones()        Returns the current record's "observaciones" value
 * @method boolean                 getActivo()               Returns the current record's "activo" value
 * @method boolean                 getLeido()                Returns the current record's "leido" value
 * @method ExpedientesEgresados    getExpedientesEgresados() Returns the current record's "ExpedientesEgresados" value
 * @method ExpedientesDerivaciones setIdderivacion()         Sets the current record's "idderivacion" value
 * @method ExpedientesDerivaciones setIdexpediente()         Sets the current record's "idexpediente" value
 * @method ExpedientesDerivaciones setIdareaorigen()         Sets the current record's "idareaorigen" value
 * @method ExpedientesDerivaciones setIdareadestino()        Sets the current record's "idareadestino" value
 * @method ExpedientesDerivaciones setObservaciones()        Sets the current record's "observaciones" value
 * @method ExpedientesDerivaciones setActivo()               Sets the current record's "activo" value
 * @method ExpedientesDerivaciones setLeido()                Sets the current record's "leido" value
 * @method ExpedientesDerivaciones setExpedientesEgresados() Sets the current record's "ExpedientesEgresados" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpedientesDerivaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expedientes_derivaciones');
        $this->hasColumn('idderivacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idexpediente', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idareaorigen', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idareadestino', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('observaciones', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('leido', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExpedientesEgresados', array(
             'local' => 'idexpediente',
             'foreign' => 'idexpediente'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}