<?php

/**
 * BaseDocumentacionExpedientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddocumentacion
 * @property integer $idexpediente
 * @property boolean $activo
 * @property Documentacion $Documentacion
 * 
 * @method integer                  getIddocumentacion() Returns the current record's "iddocumentacion" value
 * @method integer                  getIdexpediente()    Returns the current record's "idexpediente" value
 * @method boolean                  getActivo()          Returns the current record's "activo" value
 * @method Documentacion            getDocumentacion()   Returns the current record's "Documentacion" value
 * @method DocumentacionExpedientes setIddocumentacion() Sets the current record's "iddocumentacion" value
 * @method DocumentacionExpedientes setIdexpediente()    Sets the current record's "idexpediente" value
 * @method DocumentacionExpedientes setActivo()          Sets the current record's "activo" value
 * @method DocumentacionExpedientes setDocumentacion()   Sets the current record's "Documentacion" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentacionExpedientes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentacion_expedientes');
        $this->hasColumn('iddocumentacion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idexpediente', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Documentacion', array(
             'local' => 'iddocumentacion',
             'foreign' => 'iddocumentacion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}