<?php

/**
 * BaseDepartamentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddepartamento
 * @property string $descripcion
 * @property integer $idprovincia
 * @property Provincias $Provincias
 * @property Doctrine_Collection $Departamentos
 * 
 * @method integer             getIddepartamento() Returns the current record's "iddepartamento" value
 * @method string              getDescripcion()    Returns the current record's "descripcion" value
 * @method integer             getIdprovincia()    Returns the current record's "idprovincia" value
 * @method Provincias          getProvincias()     Returns the current record's "Provincias" value
 * @method Doctrine_Collection getDepartamentos()  Returns the current record's "Departamentos" collection
 * @method Departamentos       setIddepartamento() Sets the current record's "iddepartamento" value
 * @method Departamentos       setDescripcion()    Sets the current record's "descripcion" value
 * @method Departamentos       setIdprovincia()    Sets the current record's "idprovincia" value
 * @method Departamentos       setProvincias()     Sets the current record's "Provincias" value
 * @method Departamentos       setDepartamentos()  Sets the current record's "Departamentos" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartamentos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('departamentos');
        $this->hasColumn('iddepartamento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin informacion',
             'length' => 80,
             ));
        $this->hasColumn('idprovincia', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Provincias', array(
             'local' => 'idprovincia',
             'foreign' => 'idprovincia'));

        $this->hasMany('Ciudades as Departamentos', array(
             'local' => 'iddepartamento',
             'foreign' => 'iddepartamento'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}