<?php

/**
 * BaseTiposAreas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoarea
 * @property string $descripcion
 * @property Doctrine_Collection $TiposAreas
 * 
 * @method integer             getIdtipoarea()  Returns the current record's "idtipoarea" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTiposAreas()  Returns the current record's "TiposAreas" collection
 * @method TiposAreas          setIdtipoarea()  Sets the current record's "idtipoarea" value
 * @method TiposAreas          setDescripcion() Sets the current record's "descripcion" value
 * @method TiposAreas          setTiposAreas()  Sets the current record's "TiposAreas" collection
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiposAreas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipos_areas');
        $this->hasColumn('idtipoarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Areas as TiposAreas', array(
             'local' => 'idtipoarea',
             'foreign' => 'idtipoarea'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzblameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}