<?php

/**
 * Acta Volante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActaVolante extends PDF 
{
  //********** Funcion Esquema Acta Volante*************
  public function EsquemaActaVolante($bucles)
  {
	//  ESQUEMA GRÁFICO
	// Define un alias para el número de páginas del documento pdf
	$this->AliasNbPages();
	//Asigna el ancho de la linea
	$this->SetLineWidth(0);
	// Linea horizontal que separa la Asignatura
	$this->Line(10,45,200,45);
	// Linea horizontal que separa la Fecha
	$this->Line(10,60,200,60);
	//Asigna el ancho de la linea
	$this->SetLineWidth(1);
	// Linea horizontal que separa el encabezado del listado
	$this->Line(11,64,199,64);
	
	//	ESQUEMA DE CONTENIDO
	// Muestra la Asignatura
	$this->SetFont('Times','',10);
	$this->SetXY(11,36.5);
	$this->Cell(190,5,"MATERIA:",0,1,'L');
	$this->SetFont('Times','',11);
	// Muestra el Curso y la Comisión
	$this->SetFont('Times','',10);
	$this->SetXY(11,46);
	// Muestra la cabecera de la lista
	$this->SetFont('Times','',9);
	$this->SetXY(11,57);
	$this->Cell(6,10,"Nro.",0,1,'C');
	$this->SetXY(17,57);
	$this->Cell(23,10,"Legajo",0,1,'C');
	$this->SetXY(40,57);
	$this->Cell(22.5,10,"Documento",0,1,'C');
	$this->SetXY(62.5,57);
	$this->Cell(70.5,10,"ALUMNO",0,1,'C');
	$this->SetXY(133,57);
	$this->Cell(22.5,10,"Examen Escrito",0,1,'C');
	$this->SetXY(155.5,57);
	$this->Cell(22.5,10,"Examen Oral",0,1,'C');
	$this->SetXY(178,57);
	$this->Cell(22.5,10,"Calif. Definitiva",0,1,'C');
  }
}