<?php

/**
 * AreasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AreasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Areas');
    }

  // Obtiene todas las carreras de una sede
  public function obtenerCarrerasArea($idarea) 
    {
	    $q = Doctrine_Query::create()
	  		->select('c.*')
	 		->from('Carreras c')
	 		->innerjoin('c.AreasCarrera ac')
	    	->where('ac.idarea = '.$idarea)
	    	->orderBy('c.nombre ASC');
	    	
		return $q->execute();
    }	

}
