<?php

/**
 * AreasCargosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AreasCargosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreasCargosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AreasCargos');
    }
}