<?php

/**
 * AsignacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Asignaciones');
    }
}