<?php

/**
 * AsignacionesClasesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionesClasesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionesClasesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignacionesClases');
    }


    // Obtiene horarios comisiones ciclo
    public static function obtenerHorariosComisionCiclo($idcomision)
    {
		$q = Doctrine_Query::create()
  			->select('a.*')
    		->from('AsignacionesClases a')
    		->where('a.idcomision = '.$idcomision)
		->andWhere('a.fin > "'.date('Y-m-d H:i:s').'"');

		return $q->execute();

    }
}
