<?php

/**
 * AsignacionesMesasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionesMesasTable extends AsignacionesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionesMesasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignacionesMesas');
    }
}