<?php

/**
 * AulasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AulasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AulasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Aulas');
    }
}