<?php

/**
 * BajasAlumnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BajasAlumnos extends BaseBajasAlumnos
{
	// Obtiene todos los motivos de una baja
	public function obtenerMotivosPorBaja()
	{
		$q = Doctrine_Query::create()
		->select('m.*, b.idbaja')
		->from('MotivosBajas b')
		->innerjoin('b.Motivos m on b.idmotivo=m.idmotivo')
		->where('b.idbaja = '.$this->idbaja);
	
		return $q->execute();
	}	
	
	// Obtiene todos las materias de una baja
	public function obtenerMateriasPorBaja()
	{
		$q = Doctrine_Query::create()
		->select('m.*, b.idbaja')
		->from('MateriasBajas b')
		->innerjoin('b.MateriasPlanes m on b.idmateriaplan=m.idmateriaplan')
		->where('b.idbaja = '.$this->idbaja);
	
		return $q->execute();
	}	
}
