<?php

/**
 * Calendarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Calendarios extends BaseCalendarios
{   
    // Obtiene los periodos de inscripcion a ciclo que tiene un calendario
    public function obtenerPeriodosCiclos()
    {
    	$q = Doctrine_Query::create()
  			->select('p.*, f.inicio as inicio, f.fin as fin, p.idciclo as idciclo')
    		->from('PeriodosCiclos p')
    		->innerJoin('p.FechasCalendario f ON p.idfecha = f.idfecha')
    		->where('f.idcalendario = '.$this->getIdCalendario())
    		->andWhere('f.idtipo = 6');

		return $q->execute();
    } 	 
    
    // Obtiene las fechas por tipo que tiene un calendario
    public function obtenerFechasPorTipo($idtipo)
    {
    	$q = Doctrine_Query::create()
  			->select('f.*')
    		->from('FechasCalendario f')
    		->where('f.idcalendario = '.$this->getIdCalendario())
    		->andWhere('f.idtipo = '.$idtipo);
		
		return $q->execute();
    } 	

    // Obtiene si la fecha ingresada es feriado
    public function esFeriado($fecha)
    {
    	
    	$q = Doctrine_Query::create()
	  		->select('fc.*')
	 		->from('FechasCalendario fc')
	 		->where('fc.idcalendario='.$this->getIdCalendario())
	 		->andWhere('fc.idtipo=1')
	 		->andWhere('fc.inicio<="'.$fecha.'"')
	 		->andWhere('fc.fin>="'.$fecha.'"')
	    	->fetchOne();
    	    	
    	if($q){
	    	return $q['inicio'];
	    } else {
	    	return 0;
	    }
    }
}
