<?php

/**
 * Carreras
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Carreras extends BaseCarreras
{
    public function __toString() {
        return $this->getNombre();
    }
    
  	// Obtiene si la carrera es exploratoria o no en la sede 
  	public function esExploratoria($idsede) 
    {
	    $q = Doctrine_Query::create()
	  		->select('cs.*')
	 		->from('CarrerasSede cs')
	    	->where('cs.idcarrera = '.$this->getIdcarrera())
	    	->andWhere('cs.idsede = '.$idsede);
	    	
		return $q->fetchOne();
    }	
        
  	// Obtiene el plan de estudio vigente de la carrera 
  	public function obtenerPlanesEstudiosActivos() 
    {
	    $q = Doctrine_Query::create()
	  		->select('p.*')
	 		->from('PlanesEstudios p')
	    	->where('p.idcarrera = '.$this->getIdcarrera())
	    	->andWhere('(p.idestadoplan = 2) or (p.idestadoplan = 4)')
	    	->orderBy('p.nombre ASC');
	    	
		return $q->execute();
    }	
        
  	// Obtiene el plan de estudio vigente de la carrera 
  	public function obtenerPlanEstudioVigente() 
    {
	    $q = Doctrine_Query::create()
	  		->select('p.*')
	 		->from('PlanesEstudios p')
	    	->where('p.idcarrera = '.$this->getIdcarrera())
	    	->andWhere('p.idestadoplan = 2')
	    	->orderBy('p.nombre ASC');
	    	
		return $q->fetchOne();
    }	    
    public function getArregloSedes() {
		//datos seteados
		$idcarrera=$this->getIdcarrera();

  		$q = Doctrine_Query::create()
			->select('cs.*')
	 		->from("CarrerasSede cs")
	    	->where("cs.idcarrera=".$idcarrera);
                        
		return $q->execute();
    }


    public function getUltimoLegajo() {
	$q = Doctrine_Query::create()
		->select('MAX(a.legajo) as leg')
		->from('Alumnos a');

	$plan = $q->createSubquery()
		->select('pe.idplanestudio')
		->from('PlanesEstudios pe')
		->where('pe.idcarrera = '.$this->getIdcarrera());
	$q->where('a.idplanestudio IN (' . $plan->getDql() . ')');   

        $obj= $q->execute();
        
		foreach($obj as $v){
			return $v['leg'];
		}    
    }

  	// Obtiene el plan de estudio vigente de la carrera 
  	public function obtenerMaterias() 
    {
	    $q = Doctrine_Query::create()
	  		->select('mp.idmateria, m.nombre AS nombre')
	 		->from('MateriasPlanes mp')
	 		->innerjoin('mp.Materias m on mp.idmateria=m.idmateria')
	 		->innerjoin('mp.PlanesEstudios p on p.idplanestudio=mp.idplanestudio')
	    	->where('p.idcarrera = '.$this->getIdcarrera())
	    	->orderBy('m.nombre ASC')
	    	->groupBy('mp.idmateria');
	    	
		return $q->execute();
    }	    

    public function getCantidadAlumnosSinLegajo() {
               
    }
}
