<?php

/**
 * CarrerasSedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarrerasSedeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarrerasSedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CarrerasSede');
    }
    
    // Obtener los datos especificos de una carrera y sede
    public function obtenerCarrerasSede($idcarrera, $idsede)
    {
    	$q = Doctrine_Query::create()
    	->select('cs.*')
    	->from('CarrerasSede cs')
    	->where('cs.idsede = '.$idsede)
    	->andWhere('cs.idcarrera = '.$idcarrera);
    
    	return $q->fetchOne();
    }


    // Obtener los datos especificos de una carrera y sede
    public function cursandopierderegularidad($idcarrera, $idsede)
    {
    	$q = Doctrine_Query::create()
    	->select('cs.*')
    	->from('CarrerasSede cs')
    	->where('cs.idsede = '.$idsede)
    	->andWhere('cs.idcarrera = '.$idcarrera);
    	//->andWhere('cs.cursapierderegular = 1');

    	return $q->fetchOne();

    	//return $q->execute();	
    }
        

}
