<?php

/**
 * CicloLectivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CicloLectivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CicloLectivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CicloLectivo');
    }

    public static function getCicloActual()
    {
    	$resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
    		"SELECT id FROM ciclo_lectivo where inicio <= NOW() and fin>=NOW()"
    	);
    			
		return $resultado;			    
	}				            
}