<?php

/**
 * ComisionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComisionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComisionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comisiones');
    }
}