<?php

/**
 * CondicionesExpedientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicionesExpedientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicionesExpedientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CondicionesExpedientes');
    }
    
    // Return CondicionesExpedientes
  	public static function getCondicionesExpediente($idexpediente, $idcondicion)
	{
		$q = Doctrine_Query::create()
			->select('c.*')
			->from('CondicionesExpedientes c')
			->where('c.idexpediente=?', $idexpediente)
			->andWhere('c.idcondicion=?', $idcondicion);

		return $q->fetchOne();
	}        
}