<?php

/**
 * CondicionesMesasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicionesMesasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicionesMesasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CondicionesMesas');
    }
}