<?php

/**
 * Contactos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contactos extends BaseContactos
{
	// Obtiene el telefono movil
	public function getTelefonoMovil() {
		return $this->getTelefonofijocar()." - ".$this->getTelefonofijonum();
	}	
	
	
	// Obtiene el telefono fijo
	public function getTelefonoFijo() {
		return $this->getCelularcar()." - ".$this->getCelularnum();
	}
	
}
