<?php

/**
 * CorrelatividadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorrelatividadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorrelatividadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Correlatividades');
    }



    public static function controlAnioCompleto($idalumno, $idplanestudio, $idmateriaplan)
    {
        $max_anio_aprobado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT IF(r.idciclolectivo NOT IN (12,1,14,44), 6 , 
                IF(r.quinto AND r.cuarto AND r.tercero AND r.segundo AND r.primero, 5, 
                  IF( r.cuarto AND r.tercero AND r.segundo AND r.primero, 4, 
                     IF( r.tercero AND r.segundo AND r.primero, 3, 
                       IF( r.segundo AND r.primero, 2, 
                         IF( r.primero, 1, 0 )))))
       ) as tieneaprobado         
        FROM
        (
        SELECT  
              MAX(IF(mp_quinto_aprobadas= mp_quinto AND mp_quinto > 0, true, false)) as quinto,
              MAX(IF(mp_cuarto_aprobadas= mp_cuarto AND mp_cuarto > 0, true, false)) as cuarto,
              MAX(IF(mp_tercero_aprobadas= mp_tercero AND mp_tercero > 0, true, false)) as tercero,
              MAX(IF(mp_segundo_aprobadas= mp_segundo AND mp_segundo > 0, true, false)) as segundo, 
              MAX(IF(mp_primero_aprobadas= mp_primero AND mp_primero > 0, true, false)) as primero,
              info.idciclolectivo
                    FROM
                    (
                        SELECT MAX(IF(a.idalumno = ".$idalumno.",a.idciclolectivo,NULL)) as idciclolectivo, mp.anodecursada, t.descripcion as tipodoc
                            , COUNT(DISTINCT IF(mp.anodecursada=1, mp.idmateriaplan, NULL)) as mp_primero
                            , COUNT(DISTINCT IF( mp.anodecursada=1 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_primero_aprobadas
                            , COUNT(DISTINCT IF(mp.anodecursada=2, mp.idmateriaplan, NULL)) as mp_segundo
                            , COUNT(DISTINCT IF( mp.anodecursada=2 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_segundo_aprobadas
                            , COUNT(DISTINCT IF(mp.anodecursada=3, mp.idmateriaplan, NULL)) as mp_tercero
                            , COUNT(DISTINCT IF( mp.anodecursada=3 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_tercero_aprobadas
                            , COUNT(DISTINCT IF(mp.anodecursada=4, mp.idmateriaplan, NULL)) as mp_cuarto
                            , COUNT(DISTINCT IF( mp.anodecursada=4 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_cuarto_aprobadas
                            , COUNT(DISTINCT IF(mp.anodecursada=5, mp.idmateriaplan, NULL)) as mp_quinto
                            , COUNT(DISTINCT IF( mp.anodecursada=5 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_quinto_aprobadas
                        FROM materias_planes mp
                        JOIN catedras cat ON mp.idmateriaplan = cat.idmateriaplan
                        LEFT JOIN mesas_examenes me ON me.idcatedra = cat.idcatedra
                        LEFT JOIN examenes e on me.idmesaexamen = e.idmesaexamen
                        LEFT JOIN alumnos a on e.idalumno = a.idalumno
                        LEFT JOIN personas p on a.idpersona = p.idpersona
                        LEFT JOIN tipos_documentos t on p.idtipodoc = t.idtipodoc
                        WHERE 
                            mp.idplanestudio = ".$idplanestudio." AND 
                            mp.anodecursada > 0 AND 
                            mp.obligatoria = 1  
                        GROUP BY mp.anodecursada 
                    ) as info  
                ) AS r    
                    ;"
        );

        $max_anio_materia = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT mp.anodecursada FROM materias_planes mp WHERE mp.idmateriaplan = ".$idmateriaplan.";");

        return (($max_anio_materia[0]["anodecursada"] - $max_anio_aprobado[0]["tieneaprobado"])<=2 ? true : false);              
    }   

    // parameters: idalumno, idplanestudio, idmateriaplan
/*    public static function controlAnioCompleto($idalumno, $idplanestudio, $idmateriaplan)
    {
        $max_anio_aprobado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT IF(info.idciclolectivo NOT IN (12,1,14), 6 , MAX(
                IF(mp_quinto_aprobadas= mp_quinto AND mp_quinto > 0, 5,
                IF(mp_cuarto_aprobadas= mp_cuarto AND mp_cuarto > 0 AND mp_tercero_aprobadas= mp_tercero AND mp_tercero > 0 AND mp_segundo_aprobadas= mp_segundo AND mp_segundo > 0 AND mp_primero_aprobadas= mp_primero AND mp_primero > 0, 4,
                IF(mp_tercero_aprobadas= mp_tercero AND mp_tercero > 0 AND mp_segundo_aprobadas= mp_segundo AND mp_segundo > 0 AND mp_primero_aprobadas= mp_primero AND mp_primero > 0, 3,
                IF(mp_segundo_aprobadas= mp_segundo AND mp_segundo > 0 AND mp_primero_aprobadas= mp_primero AND mp_primero > 0, 2,
                IF(mp_primero_aprobadas= mp_primero AND mp_primero > 0, 1,0 ))))))) as tieneaprobado
            FROM
            (
                SELECT MAX(IF(a.idalumno = ".$idalumno.",a.idciclolectivo,NULL)) as idciclolectivo, a.idalumno, a.fechaingreso, mp.anodecursada, p.nombre, p.apellido, p.nrodoc, t.descripcion as tipodoc
                    , COUNT(DISTINCT IF(mp.anodecursada=1, mp.idmateriaplan, NULL)) as mp_primero
                    , COUNT(DISTINCT IF( mp.anodecursada=1 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_primero_aprobadas
                    , COUNT(DISTINCT IF(mp.anodecursada=2, mp.idmateriaplan, NULL)) as mp_segundo
                    , COUNT(DISTINCT IF( mp.anodecursada=2 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_segundo_aprobadas
                    , COUNT(DISTINCT IF(mp.anodecursada=3, mp.idmateriaplan, NULL)) as mp_tercero
                    , COUNT(DISTINCT IF( mp.anodecursada=3 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_tercero_aprobadas
                    , COUNT(DISTINCT IF(mp.anodecursada=4, mp.idmateriaplan, NULL)) as mp_cuarto
                    , COUNT(DISTINCT IF( mp.anodecursada=4 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_cuarto_aprobadas
                    , COUNT(DISTINCT IF(mp.anodecursada=5, mp.idmateriaplan, NULL)) as mp_quinto
                    , COUNT(DISTINCT IF( mp.anodecursada=5 AND a.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4), mp.idmateriaplan, NULL)) as mp_quinto_aprobadas
                FROM materias_planes mp
                JOIN catedras cat ON mp.idmateriaplan = cat.idmateriaplan
                LEFT JOIN mesas_examenes me ON me.idcatedra = cat.idcatedra
                LEFT JOIN examenes e on me.idmesaexamen = e.idmesaexamen
                LEFT JOIN alumnos a on e.idalumno = a.idalumno
                LEFT JOIN personas p on a.idpersona = p.idpersona
                LEFT JOIN tipos_documentos t on p.idtipodoc = t.idtipodoc
                WHERE 
                    mp.idplanestudio = ".$idplanestudio." AND 
                    mp.anodecursada > 0 AND 
                    mp.obligatoria = 1  
                GROUP BY mp.anodecursada 
            ) as info           
            ;"
        );


        $max_anio_aprobado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        $max_anio_materia = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT mp.anodecursada FROM materias_planes mp WHERE mp.idmateriaplan = ".$idmateriaplan.";");
        
        return ((($max_anio_materia[0]["anodecursada"] - $max_anio_aprobado[0]["tieneaprobado"])<=2) || ($max_anio_materia[0]["anodecursada"] < 3) ? true : false);              
    }   */










     // parameters: idplanestudio
    public static function getPlanCorrelatividades($idplanestudio)
    {
        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
                "SELECT 
                      mp.idmateriaplan
                    , m.nombre 
                    , mp.anodecursada
                    , mp.orden
                    , GROUP_CONCAT(IF(c.situacion='C' AND c.condicion='R', c.idmateriaplanc, NULL)) AS 'para_cursar_tener_regular'
                    , GROUP_CONCAT(IF(c.situacion='C' AND c.condicion='A', c.idmateriaplanc, NULL)) AS 'para_cursar_tener_aprobada'
                    , GROUP_CONCAT(IF(c.situacion='R' AND c.condicion='R', c.idmateriaplanc, NULL)) AS 'para_rendir_tener_regular'
                    , GROUP_CONCAT(IF(c.situacion='R' AND c.condicion='A', c.idmateriaplanc, NULL)) AS 'para_rendir_tener_aprobada'
                    FROM materias m JOIN materias_planes mp ON m.idmateria = mp.idmateria
                    LEFT JOIN correlatividades c ON mp.idmateriaplan = c.idmateriaplan
                    WHERE mp.idplanestudio= ".$idplanestudio." AND mp.anodecursada > 0 AND c.condicion <>'E'
                    GROUP BY mp.idmateriaplan
                    ORDER BY mp.orden;"
                );
                    
        return $resultado;              
    }   
 


    // parameters: idalumno, idplanestudio, situacion  (C o R)   tipomesa = (L, P o R) libre regular y Equivalencia
    public static function getCorrelativasAlumno($idalumno, $idplanestudio, $situacion, $tipomesa='')
    {


        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT m.nombre as materia, info.idmateriaplan, info.total_correlativas_materia_aprobar, info.total_correlativas_materia_aprobado, info.total_correlativas_regular, info.materias_correlativas_regular, info.total_correlativas_materia_regular
FROM
(
SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan,
                COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='A', 1, null )) as total_correlativas_materia_aprobar,
                COUNT(DISTINCT c.idmateriaplanc * IF(me.idcatedra IS NOT NULL AND c.condicion='A', 1, null )) as total_correlativas_materia_aprobado,
                COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='".$tipomesa."' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='".$situacion."')), 1, null )) as total_correlativas_regular,
                GROUP_CONCAT(DISTINCT c.idmateriaplanc * IF(c.condicion='".$tipomesa."' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='".$situacion."')), 1, null )) as materias_correlativas_regular,
                COUNT(DISTINCT c.idmateriaplanc * IF((me.idcatedra IS NOT NULL OR alumat.idcatedra IS NOT NULL) AND c.condicion='".$tipomesa."' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='".$situacion."')), 1, null )) as total_correlativas_materia_regular
                FROM correlatividades c 
                INNER JOIN materias_planes mp ON c.idmateriaplanc = mp.idmateriaplan AND c.situacion = '".$situacion."' 
                INNER JOIN catedras cat ON cat.idmateriaplan = mp.idmateriaplan
                LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
                LEFT JOIN
                ( 
                    SELECT me.idcatedra 
                    FROM mesas_examenes me 
                    INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
                    WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
                ) me ON cat.idcatedra = me.idcatedra

            LEFT JOIN
            (
                SELECT am.idcatedra 
                FROM alu_mat am 
                INNER JOIN
                (
                    SELECT idcatedra, MAX(id) as maxidalumat
                    FROM alu_mat 
                    WHERE idalumno = ".$idalumno." GROUP BY idcatedra
                ) as alumat_alumno ON am.idcatedra = alumat_alumno.idcatedra AND am.id = alumat_alumno.maxidalumat
                WHERE am.idalumno = ".$idalumno." and am.idestadomateria =3 and am.fechavencimiento >=DATE(NOW())
               ) alumat ON cat.idcatedra = alumat.idcatedra
            WHERE mp.idplanestudio = ".$idplanestudio." 
            GROUP BY IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) 
     ) AS info
     JOIN materias_planes mp ON info.idmateriaplan = mp.idmateriaplan
     JOIN materias m ON mp.idmateria = m.idmateria;       "
        );
        			
        return $resultado;			    
    }	

    // parameters: idalumno, idplanestudio, situacion  (C o R)   tipomesa = (L, P o R) libre regular y Equivalencia
    public static function getMateriasDisponiblesCursarRendirNuevo($idalumno, $idplanestudio, $situacion, $tipomesa='', $idsede=1)
    { 
        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT materias.idmateriaplan,c.idcatedra,m.nombre as materia,mp.anodecursada,mp.generica
         FROM
        (
	        SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan 
	        FROM correlatividades c
    	    INNER JOIN materias_planes mp ON c.idmateriaplan = mp.idmateriaplan AND mp.idplanestudio = ".$idplanestudio."
        	INNER JOIN catedras cat ON mp.idmateriaplan = cat.idmateriaplan
            LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
        	LEFT JOIN 
        	( 
        		SELECT me.idcatedra 
        		FROM mesas_examenes me  
        		INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
        		WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        	) me ON cat.idcatedra = me.idcatedra
        	WHERE c.condicion='E' AND c.situacion='".$situacion."' and me.idcatedra IS NULL

        	UNION

        	SELECT plan.idmateriaplan
        	FROM 
        	(
        		SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan,
        		COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='A', 1, null )) as total_correlativas_materia_aprobar,
        		COUNT(DISTINCT c.idmateriaplanc * IF(me.idcatedra IS NOT NULL AND c.condicion='A', 1, null )) as total_correlativas_materia_aprobado,
        		COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_regular,
        		COUNT(DISTINCT c.idmateriaplanc * IF((me.idcatedra IS NOT NULL OR alumat.idcatedra IS NOT NULL) AND c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_materia_regular
        		FROM correlatividades c 
        		INNER JOIN materias_planes mp ON c.idmateriaplanc = mp.idmateriaplan AND c.situacion = '".$situacion."' 
        		INNER JOIN catedras cat ON cat.idmateriaplan = mp.idmateriaplan
        		LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
        		LEFT JOIN
        		( 
        			SELECT me.idcatedra 
        			FROM mesas_examenes me 
        			INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
        			WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        		) me ON cat.idcatedra = me.idcatedra

        	LEFT JOIN
        	(
        		SELECT am.idcatedra 
        		FROM alu_mat am 
        		INNER JOIN
        		(
        			SELECT idcatedra, MAX(id) as maxidalumat
        			FROM alu_mat 
        			WHERE idalumno = ".$idalumno." GROUP BY idcatedra
        		) as alumat_alumno ON am.idcatedra = alumat_alumno.idcatedra AND am.id = alumat_alumno.maxidalumat
        		WHERE am.idalumno = ".$idalumno." and am.idestadomateria =3 and am.fechavencimiento >=DATE(NOW())
       		) alumat ON cat.idcatedra = alumat.idcatedra
        	WHERE mp.idplanestudio = ".$idplanestudio." 
        	GROUP BY IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) 
        ) as plan 
        WHERE plan.total_correlativas_materia_aprobar=plan.total_correlativas_materia_aprobado
        AND plan.total_correlativas_regular=plan.total_correlativas_materia_regular

		) materias 
        INNER JOIN catedras c ON materias.idmateriaplan = c.idmateriaplan
        INNER JOIN comisiones com ON c.idcatedra=com.idcatedra 
        INNER JOIN materias_planes mp ON materias.idmateriaplan = mp.idmateriaplan
        INNER JOIN materias m ON mp.idmateria = m.idmateria
        LEFT JOIN 
        ( 
        	SELECT me.idcatedra 
        	FROM mesas_examenes me 
        	INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
        	WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        ) examenesaprobados ON c.idcatedra = examenesaprobados.idcatedra
        WHERE com.idestadocomision=1 and examenesaprobados.idcatedra IS NULL AND mp.generica=0
        AND c.idsede = ".$idsede." 
        ORDER BY mp.anodecursada ASC, mp.orden ASC;"
        );
        			
        return $resultado;			    
    }	

    public static function getMateriasDisponiblesCursarRendir($idalumno, $idplanestudio, $situacion, $tipomesa='', $idsede=1)
    {

        // Obtencion de caso de que los alumnos no pierdan regularidad por cursar   
		$datoscarrerasede = array();
		$datoscarrerasede = Doctrine_Core::getTable('CarrerasSede')->cursandopierderegularidad($idplanestudio, $idsede);

		$valor=$datoscarrerasede->getCursapierderegular();

		if($valor==1){ $sinperdidarelugaridad=''; } else { $sinperdidarelugaridad='idestadomateria=3 and';} ;

        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT materias.idmateriaplan, cat.idcatedra, m.nombre as materia,mp.anodecursada,mp.periododecursada,mp.generica
        FROM
        (
              -- exentas
              SELECT c.idmateriaplan as idmateriaplan 
                FROM correlatividades c
                        JOIN materias_planes mp ON c.idmateriaplan = mp.idmateriaplan AND mp.idplanestudio = ".$idplanestudio."
                    LEFT JOIN 
                     ( 
                        SELECT me.idmateria 
                        FROM mesas_examenes me  
                        JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
                        WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
                    ) me ON mp.idmateria = me.idmateria
                     WHERE c.condicion='E' AND c.situacion='R' and me.idmateria IS NULL

                   UNION

             -- materias no exentas
                  SELECT plan.idmateriaplan
                FROM 
                     (
                        SELECT c.idmateriaplan as idmateriaplan,
                        COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='A', 1, null )) as total_correlativas_materia_aprobar,
                        COUNT(DISTINCT c.idmateriaplanc * IF(me.idmateria IS NOT NULL AND c.condicion='A', 1, null )) as total_correlativas_materia_aprobado,
                        COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_regular,
                        COUNT(DISTINCT c.idmateriaplanc * IF((me.idmateria IS NOT NULL OR alumat.idmateria IS NOT NULL) AND c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_materia_regular
                        FROM correlatividades c 
                        JOIN materias_planes mp ON c.idmateriaplanc = mp.idmateriaplan AND c.situacion = '".$situacion."' 
                        LEFT JOIN
                        ( 
                            SELECT me.idmateria 
                            FROM mesas_examenes me 
                            INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
                            WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
                        ) me ON mp.idmateria = me.idmateria
                        LEFT JOIN
                        (
                            SELECT am.idmateria 
                            FROM alu_mat am 
                            JOIN
                            (
                                SELECT idmateria, MAX(id) as maxidalumat
                                FROM alu_mat 
                                WHERE ".$sinperdidarelugaridad." idalumno = ".$idalumno." GROUP BY idmateria
                            ) as alumat_alumno ON am.idmateria = alumat_alumno.idmateria AND am.id = alumat_alumno.maxidalumat
                            WHERE am.idalumno = ".$idalumno." and am.idestadomateria =3 and am.fechavencimiento >=DATE(NOW())
                        ) alumat ON mp.idmateria = alumat.idmateria
                        WHERE mp.idplanestudio = ".$idplanestudio." 
                        GROUP BY c.idmateriaplan
                    ) as plan 
                    WHERE plan.total_correlativas_materia_aprobar=plan.total_correlativas_materia_aprobado
                    AND plan.total_correlativas_regular=plan.total_correlativas_materia_regular
     
     ) materias -- cierro FROM inicial
      
      JOIN materias_planes mp ON materias.idmateriaplan = mp.idmateriaplan 
      JOIN catedras cat ON mp.idmateriaplan = cat.idmateriaplan 
      JOIN materias m ON mp.idmateria = m.idmateria
      LEFT JOIN 
      ( 
            SELECT me.idmateria 
            FROM mesas_examenes me 
            INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
            WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
      ) examenesaprobados ON m.idmateria = examenesaprobados.idmateria
        WHERE examenesaprobados.idmateria IS NULL AND cat.idsede = ".$idsede." 
        ORDER BY mp.anodecursada ASC, mp.orden ASC;"
        );
                    
        return $resultado;              
    }   


    // parameters: idalumno, idplanestudio, situacion  (C o R)   tipomesa = (L, P o R) libre regular y Equivalencia
    public static function getMateriasDisponiblesCursarRendirAuto($idalumno, $idplanestudio, $situacion, $tipomesa='', $idsede=1)
    {

//echo $idalumno.'-'.$idplanestudio.'-'.$situacion.'-'.$tipomesa.'-'.$idsede; die;
        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT materias.idmateriaplan,c.idcatedra,m.nombre as materia,mp.anodecursada,mp.generica
         FROM
        (
	        SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan 
	        FROM correlatividades c
    	    INNER JOIN materias_planes mp ON c.idmateriaplan = mp.idmateriaplan AND mp.idplanestudio = ".$idplanestudio."
        	INNER JOIN catedras cat ON mp.idmateriaplan = cat.idmateriaplan
            LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
        	LEFT JOIN 
        	( 
        		SELECT me.idcatedra 
        		FROM mesas_examenes me  
        		INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
        		WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        	) me ON cat.idcatedra = me.idcatedra
        	WHERE c.condicion='E' AND c.situacion='".$situacion."' and me.idcatedra IS NULL

        	UNION

        	SELECT plan.idmateriaplan
        	FROM 
        	(
        		SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan,
        		COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='A', 1, null )) as total_correlativas_materia_aprobar,
        		COUNT(DISTINCT c.idmateriaplanc * IF(me.idcatedra IS NOT NULL AND c.condicion='A', 1, null )) as total_correlativas_materia_aprobado,
        		COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_regular,
        		COUNT(DISTINCT c.idmateriaplanc * IF((me.idcatedra IS NOT NULL OR alumat.idcomision IS NOT NULL) AND c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_materia_regular
        		FROM correlatividades c 
        		INNER JOIN materias_planes mp ON c.idmateriaplanc = mp.idmateriaplan AND c.situacion = '".$situacion."' 
        		INNER JOIN catedras cat ON cat.idmateriaplan = mp.idmateriaplan
        		INNER JOIN comisiones com ON cat.idcatedra = com.idcatedra
                LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
        		LEFT JOIN
        		( 
        			SELECT me.idcatedra 
        			FROM mesas_examenes me 
        			INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
        			WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        		) me ON cat.idcatedra = me.idcatedra

        	LEFT JOIN
        	(
        		SELECT am.idcomision 
        		FROM alu_mat am 
        		INNER JOIN
        		(
        			SELECT idcomision, MAX(fecha) as maxfecha 
        			FROM alu_mat 
        			WHERE idalumno = ".$idalumno." GROUP BY idcomision
        		) as alumat_alumno ON am.idcomision = alumat_alumno.idcomision AND am.fecha = alumat_alumno.maxfecha
        		WHERE am.idalumno = ".$idalumno." and am.idestadomateria =3 and am.fechavencimiento >=DATE(NOW())
       		) alumat ON com.idcomision = alumat.idcomision
        	WHERE mp.idplanestudio = ".$idplanestudio." 
        	GROUP BY IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) 
        ) as plan 
        WHERE plan.total_correlativas_materia_aprobar=plan.total_correlativas_materia_aprobado
        AND plan.total_correlativas_regular=plan.total_correlativas_materia_regular

		) materias 
        INNER JOIN catedras c ON materias.idmateriaplan = c.idmateriaplan
        INNER JOIN comisiones com ON c.idcatedra=com.idcatedra 
        INNER JOIN materias_planes mp ON materias.idmateriaplan = mp.idmateriaplan
        INNER JOIN materias m ON mp.idmateria = m.idmateria
        LEFT JOIN 
        ( 
        	SELECT me.idcatedra 
        	FROM mesas_examenes me 
        	INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
        	WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        ) examenesaprobados ON c.idcatedra = examenesaprobados.idcatedra
        WHERE com.idestadocomision=1 and examenesaprobados.idcatedra IS NULL AND mp.generica=0
        AND c.idsede = ".$idsede." 
        ORDER BY mp.anodecursada ASC, mp.orden ASC;"
        );
        			
        return $resultado;			    
    }	


    // parameters: idalumno, idplanestudio, situacion  (C o R)   tipomesa = (L, P o R) libre regular y Equivalencia
    public static function getMateriasDisponiblesCursarRendirAutogestion($idalumno, $idplanestudio, $situacion, $tipomesa='', $idsede=1, $cursoDesde, $cursoHasta, $arregloMaterias)
    {


	$condicionMaterias="";

	//if(is_array($arregloMaterias)){
	if(count($arregloMaterias) > 0) {
		$mat=""; $primero=true;
		foreach($arregloMaterias as $materia){
			if($primero){
				$mat="'".$materia."'";
				$primero=false;
			} else {
			$mat="'".$materia."',".$mat;
			}
		};
		$condicionMaterias="and mp.idmateriaplan in (".$mat.") ";
	};

	//Si Situacion es cursar se buscan las materias permitidas para cursar dependiendo de las configuraciones
	if($situacion=='C'){
		$modoinscripcion=" and mp.idmodoinscripcioncursada>2";
	}
	

        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
        "SELECT materias.idmateriaplan,c.idcatedra,m.nombre as materia,mp.anodecursada,mp.generica
         FROM
        (
            SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan 
            FROM correlatividades c
            INNER JOIN materias_planes mp ON c.idmateriaplan = mp.idmateriaplan AND mp.idplanestudio = ".$idplanestudio."
            INNER JOIN catedras cat ON mp.idmateriaplan = cat.idmateriaplan
            LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
            LEFT JOIN 
            ( 
                SELECT me.idcatedra 
                FROM mesas_examenes me  
                INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
                WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
            ) me ON cat.idcatedra = me.idcatedra
            WHERE c.condicion='E' AND c.situacion='".$situacion."' and me.idcatedra IS NULL

            UNION

            SELECT plan.idmateriaplan
            FROM 
            (
                SELECT IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) as idmateriaplan,
                COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='A', 1, null )) as total_correlativas_materia_aprobar,
                COUNT(DISTINCT c.idmateriaplanc * IF(me.idcatedra IS NOT NULL AND c.condicion='A', 1, null )) as total_correlativas_materia_aprobado,
                COUNT(DISTINCT c.idmateriaplanc * IF(c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_regular,
                COUNT(DISTINCT c.idmateriaplanc * IF((me.idcatedra IS NOT NULL OR alumat.idcatedra IS NOT NULL) AND c.condicion='R' and (('R'='".$tipomesa."') OR not(c.idmateriaplan = c.idmateriaplanc and c.situacion='R')), 1, null )) as total_correlativas_materia_regular
                FROM correlatividades c 
                INNER JOIN materias_planes mp ON c.idmateriaplanc = mp.idmateriaplan AND c.situacion = '".$situacion."' 
                INNER JOIN catedras cat ON cat.idmateriaplan = mp.idmateriaplan
                LEFT JOIN materias_genericas mg ON c.idmateriaplan = mg.idmateriaplangenerica
                LEFT JOIN
                ( 
                    SELECT me.idcatedra 
                    FROM mesas_examenes me 
                    INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
                    WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
                ) me ON cat.idcatedra = me.idcatedra

            LEFT JOIN
            (
                SELECT am.idcatedra 
                FROM alu_mat am 
                INNER JOIN
                (
                    SELECT idcatedra, MAX(id) as maxidalumat
                    FROM alu_mat 
                    WHERE idalumno = ".$idalumno." GROUP BY idcatedra
                ) as alumat_alumno ON am.idcatedra = alumat_alumno.idcatedra AND am.id = alumat_alumno.maxidalumat
                WHERE am.idalumno = ".$idalumno." and am.idestadomateria =3 and am.fechavencimiento >=DATE(NOW())
            ) alumat ON cat.idcatedra = alumat.idcatedra
            WHERE mp.idplanestudio = ".$idplanestudio." 
            GROUP BY IF(mg.idmateriaplan IS NOT NULL, mg.idmateriaplan, c.idmateriaplan) 
        ) as plan 
        WHERE plan.total_correlativas_materia_aprobar=plan.total_correlativas_materia_aprobado
        AND plan.total_correlativas_regular=plan.total_correlativas_materia_regular

        ) materias 
        INNER JOIN catedras c ON materias.idmateriaplan = c.idmateriaplan
        INNER JOIN comisiones com ON c.idcatedra=com.idcatedra 
        INNER JOIN materias_planes mp ON materias.idmateriaplan = mp.idmateriaplan
        INNER JOIN materias m ON mp.idmateria = m.idmateria
        LEFT JOIN 
        ( 
            SELECT me.idcatedra 
            FROM mesas_examenes me 
            INNER JOIN examenes e ON me.idmesaexamen = e.idmesaexamen
            WHERE e.idalumno = ".$idalumno." AND me.idestadomesaexamen=4 AND (e.promedio >=4 OR me.idtipoexamen = 4)
        ) examenesaprobados ON c.idcatedra = examenesaprobados.idcatedra
        WHERE com.idestadocomision=1 and examenesaprobados.idcatedra IS NULL AND mp.generica=0
        AND c.idsede = ".$idsede." 
        ORDER BY mp.anodecursada ASC, mp.orden ASC;"
        );
        		
        return $resultado;			    
    }	


		/* NO BORRAR GUILLE
			INSERTAR EN LINEA 74 VER POR UN PARTICULARIDAD EN MATERIA QUE NO PIERDE REGULARIDAD SI RECURSA
				UNION
        			SELECT idcomision, MAX(fecha) as maxfecha 
        			FROM alu_mat 
        			WHERE idalumno = ".$idalumno." AND idestadomateria=3 GROUP BY idcomision
		*/
}
