<?php

/**
 * DepartamentosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartamentosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartamentosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Departamentos');
    }
}