<?php

/**
 * DesignacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DesignacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DesignacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Designaciones');
    }

    // Obtener designaciones por persona, filtrando tambien por area y sede
    public static function obtenerDesignacionesPorPersona($idpersona, $idarea, $idsede, $idplanestudio='', $idcategoriadesignacion='', $idtipodesignacion='', $idestadodesignacion='', $fechadesde='', $fechahasta='', $orderby='1')
    {
    	$sql ="SELECT 
				DATE_FORMAT(des.inicio, '%d/%m/%Y') AS inicioformat, DATE_FORMAT(des.fin, '%d/%m/%Y') AS finformat, CONCAT(car.nombre,' - ',pe.nombre) as carreraplan, cat.idsede, des.adhonorem, des.licencia, des.iddesignacion, des.visibleensede, m.nombre as materia, td.descripcion as tipo, cd.descripcion as categoria, des.inicio, des.fin, des.visibleensede, des.adhonorem, des.fechaaprobacion, ded.descripcion as dedicacion, des.activo, edes.idestadodesignacion, edes.descripcion as estadodesignacion, cat.idsede, sed.nombre as sede, sed.abreviacion as sedeabv  
				FROM designaciones des 
                JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
				JOIN profesores prof ON des.idprofesor = prof.idprofesor
				JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
				JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                JOIN sedes sed ON cat.idsede = sed.idsede 
				JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
				JOIN materias m ON mp.idmateria = m.idmateria
				JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
				JOIN carreras car ON pe.idcarrera = car.idcarrera
				JOIN (SELECT DISTINCT idcarrera from areas_carrera WHERE idarea = ".$idarea.") ac ON car.idcarrera = ac.idcarrera 
				JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
				JOIN categoria_designaciones cd ON td.idcategoriadesignacion= cd.idcategoriadesignacion
				WHERE prof.idpersona = ".$idpersona." ";
        
        if ($idsede<>'' AND $idsede > 0)
            $sql .=" AND cat.idsede = ".$idsede." ";

        if ($idestadodesignacion<>'' AND $idestadodesignacion > 0)
            $sql .=" AND des.idestadodesignacion IN (".$idestadodesignacion.") ";

        if ($idsede=='' OR $idsede <= 1 )
            $sql .=" AND des.visibleensede = 1 ";

        if ($idplanestudio<>'' AND $idplanestudio > 0)
        	$sql .=" AND pe.idplanestudio = ".$idplanestudio." ";

        if ($idcategoriadesignacion<>'' AND $idcategoriadesignacion > 0)
        	$sql .=" AND cd.idcategoriadesignacion = ".$idcategoriadesignacion." ";

        if ($idtipodesignacion<>'' AND $idtipodesignacion > 0)
        	$sql .=" AND td.idtipodesignacion = ".$idtipodesignacion." ";

        if ($fechadesde<>'')
        	$sql .=" AND des.inicio >= '".$fechadesde."' ";

        // Sacado por solicitud de Yamil 06/07/2016
        //if ($fechahasta<>'')
        //	$sql .=" AND des.fin <= '".$fechahasta."' ";

        switch ($orderby) {
            case '1':
                $sql .=" ORDER BY sed.idsede, car.nombre ASC, per.apellido ASC, per.nombre ASC, des.inicio DESC;"; 
                break;
            case '2':
                $sql .=" ORDER BY des.inicio DESC, m.nombre ASC;";
                break;
            default:
                $sql .=" ORDER BY des.inicio, m.nombre; ";
                break;
        }

		$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
    	
    	return $q;
    }

    // Obtener reporte de estados de designaciones del ciclo actual
    public static function reporteEstadosDesignaciones()
    {
        $sql ="SELECT sed.abreviacion as sede, fac.nombre as facultad, edes.descripcion as estado, COUNT(DISTINCT des.iddesignacion) as cantidad
                  FROM designaciones des 
                                JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
                                JOIN profesores prof ON des.idprofesor = prof.idprofesor
                                JOIN personas per ON prof.idpersona = per.idpersona 
                                JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
                                JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                                JOIN sedes sed ON cat.idsede = sed.idsede 
                                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                                JOIN materias m ON mp.idmateria = m.idmateria
                                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                                JOIN carreras car ON pe.idcarrera = car.idcarrera 
                                JOIN facultades fac ON car.idfacultad = fac.idfacultad 
                                JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
                                JOIN categoria_designaciones cd ON td.idcategoriadesignacion= cd.idcategoriadesignacion
                                WHERE YEAR(des.inicio)= YEAR(now()) 
                                GROUP BY car.idfacultad, sed.idsede, edes.idestadodesignacion
                                ORDER BY sed.idsede, car.nombre; ";
        
      
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    }

    // Obtener fecha de resolucion CSU para una designacion especifica
    public static function obtenerFechaResolucionCsuPorDesignacion($iddesignacion)
    {
        $sql ="SELECT pr.fecha FROM designaciones des JOIN resoluciones_profesores pr ON des.idresolucioncsu = pr.idresolucionprofesor 
                WHERE des.iddesignacion =5428; ";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    }

    // Obtener designaciones por persona, filtrando tambien por area y sede
    public static function obtenerInfoDesignacion($iddesignacion)
    {
        $sql ="SELECT 
                mp.idplanestudio, DATE_FORMAT(des.inicio, '%d/%m/%Y') AS inicioformat, DATE_FORMAT(des.fin, '%d/%m/%Y') AS finformat, des.horas, des.adhonorem, des.licencia, des.idprofesor, prof.idpersona, td.idcategoriadesignacion, 
                des.iddesignacion, des.idcatedra, ifnull(des.observaciones,'') as observaciones, ifnull(des.motivonuevadesignacion,'') as motivonuevadesignacion, des.idprofesor, des.idtipodesignacion, des.inicio, des.fin, des.idresolucionprofesor, des.idresolucioncsu, des.iddedicacion, des.idestadodesignacion, cat.idsede, sed.nombre as sede, sed.abreviacion as sedeabv, 
                CONCAT(per.apellido, ', ', per.nombre) as persona, td.descripcion as tipodesignacion, cd.descripcion as categoriadesignacion, m.nombre as materia, concat(car.nombre, ', ', pe.nombre) as carreraplan 
                FROM designaciones des 
                JOIN tipos_designaciones td on des.idtipodesignacion= td.idtipodesignacion
                JOIN categoria_designaciones cd ON td.idcategoriadesignacion = cd.idcategoriadesignacion
                JOIN profesores prof ON des.idprofesor = prof.idprofesor
                JOIN personas per ON prof.idpersona = per.idpersona
                JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                JOIN sedes sed ON cat.idsede = sed.idsede 
                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan 
                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                JOIN carreras car on pe.idcarrera = car.idcarrera
                JOIN materias m ON mp.idmateria = m.idmateria
                WHERE des.iddesignacion = ".$iddesignacion." ";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    }

    // Obtener designaciones por persona, filtrando tambien por area y sede
    public static function listaSabana($idsede, $idfacultad, $anio)
    {
        $sql ="SELECT sed.nombre as sede, CONCAT(car.nombre,' - ',pe.nombre) as carreraplan, car.nombre as carrera, fac.nombre as facultad, CONCAT(per.apellido,', ',per.nombre) as persona,
       per.apellido, per.nombre,
       tp.descripcion as tipodocumento, 
       per.numerodoc,
       m.nombre as materia,
       td.descripcion as tipodesignacion,
       cd.descripcion as categoria, 
       cd.idcategoriadesignacion,
       edes.descripcion as estadodesignacion,
       mp.anodecursada,
       IFNULL(des.horas, 0 ) as horas,
       td.descripcion as tipo, 
       if(des.adhonorem,'AD HONOREM','') as adhonorem, 
       if(des.licencia,'EN LICENCIA','') as licencia, 
       ded.descripcion as dedicacion,
       sed.abreviacion as sedeabreviada,
       car.idcarrera,
       YEAR(des.inicio) as ciclolectivo,
       DATE_FORMAT(des.inicio, '%d/%m/%Y') AS inicioformat, DATE_FORMAT(des.fin, '%d/%m/%Y') AS finformat,
       des.idresolucionprofesor,
       rp.resolucion,
       des.iddesignacion 
  FROM designaciones des 
                JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
                JOIN profesores prof ON des.idprofesor = prof.idprofesor
                JOIN personas per ON prof.idpersona = per.idpersona 
                JOIN tipos_documentos tp ON per.idtipodoc = tp.idtipodoc
                JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
                JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                JOIN sedes sed ON cat.idsede = sed.idsede 
                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                JOIN materias m ON mp.idmateria = m.idmateria
                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                JOIN carreras car ON pe.idcarrera = car.idcarrera 
                JOIN facultades fac ON car.idfacultad = fac.idfacultad 
                JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
                JOIN categoria_designaciones cd ON td.idcategoriadesignacion= cd.idcategoriadesignacion 
                LEFT JOIN resoluciones_profesores rp ON des.idresolucionprofesor = rp.idresolucionprofesor
                WHERE des.idestadodesignacion = 4 AND YEAR(des.inicio)= ".$anio." AND car.idfacultad = ".$idfacultad." AND sed.idsede= ".$idsede." 
                ORDER BY car.nombre, per.apellido; ";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }

    // Obtener designaciones por persona, filtrando tambien por area y sede
    public static function obtenerNuevasDesignaciones($idsede, $anio, $idarea)
    {
        
        $anioanterior =  $anio - 1;

        $sql ="SELECT sed.nombre as sede, CONCAT(car.nombre,' - ',pe.nombre) as carreraplan, car.nombre as carrera, fac.nombre as facultad, CONCAT(per.apellido,', ',per.nombre) as persona,
       per.apellido, per.nombre,
       tp.descripcion as tipodocumento, 
       per.numerodoc,
       m.nombre as materia,
       td.descripcion as tipodesignacion,
       cd.descripcion as categoria, 
       cd.idcategoriadesignacion,
       edes.descripcion as estadodesignacion,
       mp.anodecursada,
       IFNULL(des.horas, 0 ) as horas,
       td.descripcion as tipo, 
       if(des.adhonorem,'AD HONOREM','') as adhonorem, 
       if(des.licencia,'EN LICENCIA','') as licencia, 
       ded.descripcion as dedicacion,
       sed.abreviacion as sedeabreviada,
       car.idcarrera,
       YEAR(des.inicio) as ciclolectivo,
       DATE_FORMAT(des.inicio, '%d/%m/%Y') AS inicioformat, DATE_FORMAT(des.fin, '%d/%m/%Y') AS finformat
       FROM designaciones des 
                JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
                JOIN profesores prof ON des.idprofesor = prof.idprofesor
                JOIN personas per ON prof.idpersona = per.idpersona 
                JOIN tipos_documentos tp ON per.idtipodoc = tp.idtipodoc
                JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
                JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                JOIN sedes sed ON cat.idsede = sed.idsede 
                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                JOIN materias m ON mp.idmateria = m.idmateria
                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                JOIN carreras car ON pe.idcarrera = car.idcarrera ";
        
       // se filtra por area solo si el area existe
        if ($idarea<>'')
            $sql .=" JOIN areas_carrera ar ON car.idcarrera= ar.idcarrera AND ar.idarea = ".$idarea." ";        

                
        $sql .="JOIN facultades fac ON car.idfacultad = fac.idfacultad 
                JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
                JOIN categoria_designaciones cd ON td.idcategoriadesignacion= cd.idcategoriadesignacion 
                LEFT JOIN (SELECT designaciones.idcatedra, designaciones.idprofesor FROM designaciones JOIN catedras ON designaciones.idcatedra = catedras.idcatedra WHERE YEAR(designaciones.inicio) = ".$anioanterior." AND catedras.idsede = ".$idsede." AND designaciones.idcatedra IS NOT NULL AND designaciones.idprofesor IS NOT NULL GROUP BY designaciones.idcatedra, designaciones.idprofesor) as anioanterior ON des.idprofesor = anioanterior.idprofesor AND des.idcatedra = anioanterior.idcatedra 
                WHERE YEAR(des.inicio)= ".$anio." AND sed.idsede = ".$idsede." AND anioanterior.idprofesor IS NULL
                ORDER BY car.nombre, per.apellido; ";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }

    // Obtener designaciones aplicando diferentes filtros
    public static function obtenerDesignacionesAplicandoFiltros($idsede='', $idarea='', $idfacultad='', $idplanestudio='', $idpersona='', $fechadesde='', $fechahasta='', $estadodesignacion='', $idresolucion='', $idcategoriadesignacion='', $idtipodesignacion='', $idcatedra='', $orderby='1')
    {
        $sql ="SELECT DATE_FORMAT(des.inicio, '%d/%m/%Y') AS inicioformat, DATE_FORMAT(des.fin, '%d/%m/%Y') AS finformat, CONCAT(per.apellido,', ',per.nombre) as persona, per.apellido, per.nombre, cd.descripcion as categoria, edes.idestadodesignacion, edes.descripcion as estadodesignacion,
                CONCAT(car.nombre,' - ',pe.nombre) as carreraplan, m.nombre as materia, des.horas, td.descripcion as tipo, des.inicio, des.fin, des.fechaaprobacion, des.adhonorem, des.licencia, ded.descripcion as dedicacion, des.activo, des.iddesignacion, fac.nombre as facultad, cat.idsede, sed.nombre as sede, sed.abreviacion as sedeabv, des.visibleensede, tp.descripcion as tipodocumento, mp.anodecursada,
                des.observaciones, des.motivonuevadesignacion  
                FROM designaciones des 
                JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
                JOIN profesores prof ON des.idprofesor = prof.idprofesor
                JOIN personas per ON prof.idpersona = per.idpersona 
                JOIN tipos_documentos tp ON per.idtipodoc = tp.idtipodoc
                JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
                JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                JOIN sedes sed ON cat.idsede = sed.idsede 
                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                JOIN materias m ON mp.idmateria = m.idmateria
                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                JOIN carreras car ON pe.idcarrera = car.idcarrera ";

        if ($idarea<>'')        
                $sql .="JOIN (SELECT DISTINCT idcarrera from areas_carrera WHERE idarea = ".$idarea.") ac ON car.idcarrera = ac.idcarrera ";

        $sql .="JOIN facultades fac on car.idfacultad = fac.idfacultad
        JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
        JOIN categoria_designaciones cd ON td.idcategoriadesignacion= cd.idcategoriadesignacion
        WHERE 1=1 ";
        
        if ($idsede<>'' AND $idsede > 0)
            $sql .=" AND cat.idsede = ".$idsede." ";

        if ($idsede=='' OR $idsede <= 1 )
            $sql .=" AND des.visibleensede = 1 ";

        if ($idfacultad<>'' AND $idfacultad > 0)
            $sql .=" AND fac.idfacultad = ".$idfacultad." ";

        if ($estadodesignacion<>'' AND $estadodesignacion > 0)
            $sql .=" AND edes.idestadodesignacion IN (".$estadodesignacion.") ";

        if ($idplanestudio<>'' AND $idplanestudio > 0)
            $sql .=" AND mp.idplanestudio = ".$idplanestudio." ";

        if ($idresolucion<>'' AND $idresolucion > 0)
            $sql .=" AND des.idresolucionprofesor = ".$idresolucion." ";

        if ($idpersona<>'' AND $idpersona > 0)
            $sql .=" AND per.idpersona = ".$idpersona." ";

        if ($idcatedra<>'' AND $idcatedra > 0)
            $sql .=" AND cat.idcatedra = ".$idcatedra." ";

        if ($idcategoriadesignacion<>'' AND $idcategoriadesignacion > 0)
            $sql .=" AND cd.idcategoriadesignacion = ".$idcategoriadesignacion." ";

        if ($idtipodesignacion<>'' AND $idtipodesignacion > 0)
            $sql .=" AND td.idtipodesignacion = ".$idtipodesignacion." ";

        if ($fechadesde<>'')
            $sql .=" AND des.inicio >= '".$fechadesde."' ";

        if ($fechahasta<>'')
            $sql .=" AND des.fin <= '".$fechahasta."' ";

        switch ($orderby) {
            case '1':
                $sql .=" ORDER BY sed.idsede, car.nombre ASC, per.apellido ASC, per.nombre ASC, des.inicio DESC;"; 
                break;
            case '2':
                $sql .=" ORDER BY des.inicio, m.nombre ";
                break;
            default:
                $sql .=" ORDER BY des.inicio, m.nombre ";
                break;
        }

        //echo $sql;exit;

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    }
    
    // Obtener estadisticas Anexo cuadro 3
    public static function estadisticasDesignacionesDetalladas($ciclo)
    {
        $sql ="SELECT  sed.abreviacion as Sede, car.nombre as Carrera, 
        CONCAT(per.apellido,', ',per.nombre) as persona,
        IF(per.idsexo=1,'M','F') as sexo, 
        DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(per.fechanac)), '%Y')+0 AS edad,
        CONCAT(td.descripcion,' (', cd.descripcion,')') as tipo_designacion,
        m.nombre as materia, des.iddesignacion,
        IFNULL((SELECT CONCAT(descripcion, IF(concluyo=2 AND ne.idnivelestudio NOT IN (2,3),' (En Curso)','')) FROM niveles_estudios WHERE idordenimportancia = MAX(ne.idordenimportancia)),' ') as nivel_educativo, 
        GROUP_CONCAT(DISTINCT est.descripcion  SEPARATOR ',') as titulo,
        rp.resolucion, ciu.descripcion as ciudad 
        FROM designaciones des
                            JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
                            JOIN profesores prof ON des.idprofesor = prof.idprofesor
                            JOIN personas per ON prof.idpersona = per.idpersona
                            LEFT JOIN contactos cont ON per.idpersona = cont.idpersona
                            LEFT JOIN ciudades ciu ON cont.idciudadt = ciu.idciudad
                            JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
                            JOIN catedras cat ON des.idcatedra = cat.idcatedra
                            JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                            JOIN materias m ON mp.idmateria = m.idmateria
                            JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                            JOIN carreras car ON pe.idcarrera = car.idcarrera
                            JOIN sedes sed ON cat.idsede = sed.idsede 
                            JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
                            JOIN categoria_designaciones cd ON td.idcategoriadesignacion = cd.idcategoriadesignacion
                            LEFT JOIN estudios est ON per.idpersona = est.idpersona
                            LEFT JOIN niveles_estudios ne ON est.idnivelestudio = ne.idnivelestudio
                            LEFT JOIN resoluciones_profesores rp ON des.idresolucioncsu = rp.idresolucionprofesor
                    WHERE YEAR(des.inicio)= ".$ciclo." AND des.idestadodesignacion = 5
                    GROUP BY per.idpersona, des.iddesignacion; ";

        //echo $sql;exit;

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    }

    // Obtener estadisticas Anexo cuadro 3
    public static function estadisticasDesignaciones($ciclo)
    {
        $sql ="SELECT  sed.abreviacion as Sede, car.nombre as Carrera
            , COUNT( DISTINCT per.idpersona) as total
            , COUNT( DISTINCT IF(per.idsexo = 1, per.idpersona, NULL)) as varones
            , COUNT( DISTINCT IF(per.idsexo = 2 , per.idpersona, NULL)) as mujeres
            , td.idtipodesignacion, ded.iddedicacion, td.descripcion as tipo_designacion
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=0, per.idpersona, NULL)) as NivelESinDefinir
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=1, per.idpersona, NULL)) as NivelEPrimario
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=2, per.idpersona, NULL)) as NivelESecundario
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=3, per.idpersona, NULL)) as NivelETerciario
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=4, per.idpersona, NULL)) as NivelEUnivesitarioPreGr
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=5, per.idpersona, NULL)) as NivelEUniversitarioGr
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=6, per.idpersona, NULL)) as NivelEMaestria
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=7, per.idpersona, NULL)) as NivelEDoctorado
            , COUNT(DISTINCT IF(maxnivelinfo.idnivelestudio=8, per.idpersona, NULL)) as NivelEEspecializacion
            , COUNT(DISTINCT IF(des.idtipodesignacion IN ( 1,7), des.iddesignacion, NULL)) as Profesor_Titular
            , COUNT(DISTINCT IF(des.idtipodesignacion IN (2,8), des.iddesignacion, NULL)) as Profesor_Asociado
            , COUNT(DISTINCT IF(des.idtipodesignacion IN ( 3,9), des.iddesignacion, NULL)) as Profesor_Adjunto
            , COUNT(DISTINCT IF(des.idtipodesignacion IN (4,10), des.iddesignacion, NULL)) as JTP
            , COUNT(DISTINCT IF(des.idtipodesignacion = 5, des.iddesignacion, NULL)) as Ayudante_Diplomado
            , COUNT(DISTINCT IF(des.idtipodesignacion IN (6,12), des.iddesignacion, NULL)) as Ayudante_Alumno
            , COUNT(DISTINCT IF(des.idtipodesignacion = 11, des.iddesignacion, NULL)) as Auxiliar_Docente
            , COUNT(DISTINCT IF(des.idtipodesignacion = 13, des.iddesignacion, NULL)) as Profesor_Emerito
            , COUNT(DISTINCT IF(des.idtipodesignacion = 14, des.iddesignacion, NULL)) as Profesor_Honorario
            , COUNT(DISTINCT IF(des.idtipodesignacion = 15, des.iddesignacion, NULL)) as Profesor_Consulto
            , COUNT(DISTINCT IF(des.idtipodesignacion = 16, des.iddesignacion, NULL)) as Profesor_Invitado
            , COUNT(DISTINCT IF(des.iddedicacion = 1, des.iddesignacion, NULL)) as Sin_Dedicacion
            , COUNT(DISTINCT IF(des.iddedicacion = 2, des.iddesignacion, NULL)) as Dedicacion_Simple
            , COUNT(DISTINCT IF(des.iddedicacion = 3, des.iddesignacion, NULL)) as Dedicacion_Completa
            , COUNT(DISTINCT IF(des.iddedicacion = 4, des.iddesignacion, NULL)) as Dedicacion_Parcial
            , COUNT(DISTINCT IF(des.iddedicacion = 5, des.iddesignacion, NULL)) as Dedicacion_Semi_Exclusiva
            , COUNT(DISTINCT IF(des.iddedicacion = 6, des.iddesignacion, NULL)) as Dedicacion_Exclusiva
                           FROM designaciones des 
                            JOIN estados_designaciones edes ON des.idestadodesignacion = edes.idestadodesignacion
                            JOIN profesores prof ON des.idprofesor = prof.idprofesor
                            JOIN personas per ON prof.idpersona = per.idpersona
                            LEFT JOIN (SELECT info.idestudio, info.idpersona, info.idnivelestudio FROM (SELECT e.idestudio, e.idpersona, e.idnivelestudio FROM estudios e JOIN niveles_estudios niv ON e.idnivelestudio= niv.idnivelestudio ORDER BY e.idpersona, niv.idordenimportancia DESC) as info GROUP BY info.idpersona) as maxnivelinfo ON per.idpersona = maxnivelinfo.idpersona
                            JOIN dedicaciones ded ON des.iddedicacion = ded.iddedicacion
                            JOIN catedras cat ON des.idcatedra = cat.idcatedra
                            JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                            JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                            JOIN carreras car ON pe.idcarrera = car.idcarrera
                            JOIN sedes sed ON cat.idsede = sed.idsede 
                            JOIN tipos_designaciones td ON des.idtipodesignacion = td.idtipodesignacion
                            JOIN categoria_designaciones cd ON td.idcategoriadesignacion = cd.idcategoriadesignacion
                            LEFT JOIN estudios est ON maxnivelinfo.idestudio = est.idestudio 
                    WHERE YEAR(des.inicio)= ".$ciclo." AND des.idestadodesignacion = 5
                    GROUP BY sed.idsede, car.idcarrera;";

        //echo $sql;exit;

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    }            


    // Contar designaciones que no podran actualizarse por no tener asignada la resolucion de CSU
    public static function contarDesignacionesSinActualizar($arrDesignaciones)
    {
        
        // Definir elemenos para filtrar por IN
        $datos=''; $cantidad=0;
        foreach($arrDesignaciones as $info)
            $datos .= $info.', ';
        
        $datos = substr($datos, 0, strlen($datos)-2);

        // COnsulta para contar las designaciones a actualizar
        $sql ="SELECT COUNT(DISTINCT des.iddesignacion) AS cantidad
                FROM designaciones des
                JOIN catedras cat ON des.idcatedra = cat.idcatedra
                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                JOIN carreras car ON pe.idcarrera = car.idcarrera
                JOIN facultades fac ON car.idfacultad = fac.idfacultad
                JOIN resoluciones_profesores rp ON cat.idsede = rp.idsede AND fac.idfacultad = rp.idfacultad AND resolucion_csu = 1
                WHERE des.iddesignacion IN (".$datos.");";

        $elementos = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        foreach($elementos as $info)
           $cantidad = $info['cantidad']; 
        
        return $cantidad;
    }

    // Elevar designaciones por iddesignacion (arreglo)
    public static function elevarDesignaciones($arrDesignaciones)
    {
        
        // Definir elemenos para filtrar por IN
        $datos=''; $cantidad=0;
        foreach($arrDesignaciones as $info)
            $datos .= $info.', ';
        
        $datos = substr($datos, 0, strlen($datos)-2);

        // actualizar designaciones
        $sql ="UPDATE designaciones set idestadodesignacion = 2, fechaaprobacion = DATE(NOW()) WHERE iddesignacion IN (".$datos.");";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        return $q->execute($sql);
    }

    // Asignar numero de resolucion a designaciones
    public static function asignarresolucionDesignaciones($arrDesignaciones, $idresolucion)
    {
        
        // Definir elemenos para filtrar por IN
        $datos=''; $cantidad=0;
        foreach($arrDesignaciones as $info)
            $datos .= $info.', ';
        
        $datos = substr($datos, 0, strlen($datos)-2);

        // actualizar designaciones
        $sql ="UPDATE designaciones set idresolucionprofesor = ".$idresolucion." WHERE iddesignacion IN (".$datos.");";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        return $q->execute($sql);
    }

    // Elevar designaciones por iddesignacion (arreglo)
    public static function confirmarfincargaDesignaciones($arrDesignaciones)
    {
        
        // Definir elemenos para filtrar por IN
        $datos=''; $cantidad=0;
        foreach($arrDesignaciones as $info)
            $datos .= $info.', ';
        
        $datos = substr($datos, 0, strlen($datos)-2);

        // actualizar designaciones
        $sql ="UPDATE designaciones set visibleensede = 1 WHERE iddesignacion IN (".$datos.");";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        return $q->execute($sql);
    }

    // Activar Designaciones
    public static function activarDesignaciones($arrDesignaciones)
    {
        
        // Definir elemenos para filtrar por IN
        $datos=''; $cantidad=0;
        foreach($arrDesignaciones as $info)
            $datos .= $info.', ';
        
        $datos = substr($datos, 0, strlen($datos)-2);

        // Actualizar designaciones
        $sql ="UPDATE designaciones des
                JOIN catedras cat ON des.idcatedra = cat.idcatedra
                JOIN materias_planes mp ON cat.idmateriaplan = mp.idmateriaplan
                JOIN planes_estudios pe ON mp.idplanestudio = pe.idplanestudio
                JOIN carreras car ON pe.idcarrera = car.idcarrera
                JOIN facultades fac ON car.idfacultad = fac.idfacultad
                JOIN resoluciones_profesores rp ON cat.idsede = rp.idsede AND fac.idfacultad = rp.idfacultad AND resolucion_csu = 1
                SET des.activo = 1, des.idresolucioncsu = rp.idresolucionprofesor
                WHERE des.iddesignacion IN (".$datos.");";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        return $q->execute($sql);
    
    }

    // Activar Designaciones
    public static function cambiarestadoDesignaciones($arrDesignaciones, $nuevoestado)
    {
        
        // Definir elemenos para filtrar por IN
        $datos=''; $cantidad=0;
        foreach($arrDesignaciones as $info)
            $datos .= $info.', ';
        
        $datos = substr($datos, 0, strlen($datos)-2);

        // Actualizar designaciones
        $sql ="UPDATE designaciones des JOIN catedras cat ON des.idcatedra = cat.idcatedra 
                SET des.idestadodesignacion = ".$nuevoestado.", des.visibleensede = IF(cat.idsede = '1', 1, 0) WHERE des.iddesignacion IN (".$datos.");";
    
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        return $q->execute($sql);
    
    }
}
