<?php

/**
 * DesignacionesEmpleadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DesignacionesEmpleadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DesignacionesEmpleadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DesignacionesEmpleados');
    }

    public function obtenerAutoridad($idcarrera, $idtipocargo, $idsede)
    {
    	// Rector o Sec General
    	if($idtipocargo == 1 or $idtipocargo == 2) {
	    	$q = Doctrine_Query::create()
		  		->select("*")
		 		->from("DesignacionesEmpleados de")
		 		->innerjoin('de.Empleados e on de.idempleado=e.idempleado')
		 		->where("de.idtipocargo = ".$idtipocargo)
		 		->andWhere("de.inicio<CURRENT_TIMESTAMP()")
		    	->andWhere("(de.fin>CURRENT_TIMESTAMP() or de.fin='0000-00-00')")
		    	->andWhere("de.activo = 1")   	
		    	->fetchOne();  
		// Director	    		
	    } elseif ($idtipocargo == 19) {
	    	$q = Doctrine_Query::create()
	    		->select("*")
	    		->from("DesignacionesEmpleados de")
	    		->innerjoin('de.Empleados e on de.idempleado=e.idempleado')
	    		->where("de.idtipocargo = ".$idtipocargo)
	    		->andWhere("de.inicio<CURRENT_TIMESTAMP()")
	    		->andWhere("de.fin>CURRENT_TIMESTAMP() or de.fin='0000-00-00'")
	    		->andWhere("de.activo = 1")
	    		->andWhere('de.idempleado IN (
		    				SELECT es.idempleado
		    				FROM EmpleadosSede es
		    				WHERE es.idsede = '.$idsede.')')
	    		->andWhere('de.idarea IN (
		    				SELECT ac.idarea
		    				FROM AreasCarrera ac
	    					INNER JOIN ac.Areas ar ON ac.idarea=ar.idarea
		    				WHERE (ar.idtipoarea = 5 or ar.idtipoarea = 7) and ac.idcarrera = '.$idcarrera.')')
	    		->fetchOne();	
		// Decano o Sec Academico	    		
    	} else {
	    	$q = Doctrine_Query::create()
		  		->select("*")
		 		->from("DesignacionesEmpleados de")
		 		->innerjoin('de.Empleados e on de.idempleado=e.idempleado')
		 		->where("de.idtipocargo = ".$idtipocargo)
		 		->andWhere("de.inicio<CURRENT_TIMESTAMP()")
		    	->andWhere("de.fin>CURRENT_TIMESTAMP() or de.fin='0000-00-00'")
		    	->andWhere("de.activo = 1")
	    		->andWhere('de.idarea IN (
		    				SELECT ac.idarea 
		    				FROM AreasCarrera ac
		    				WHERE ac.idcarrera = '.$idcarrera.')')	    		    	
		    	->fetchOne();    	
    	}
	       
        return $q;
    }
    
    public function obtenerAutoridades()
    {
    	$q = Doctrine_Query::create()
    		->select("*")
    		->from("DesignacionesEmpleados de")
    		->innerjoin("de.Empleados e on de.idempleado=e.idempleado")
    		->innerjoin("e.Personas p on e.idpersona=p.idpersona")
    		->innerjoin("de.Areas a on de.idarea=a.idarea")
    		->where("de.inicio<CURRENT_TIMESTAMP()")
    		->andWhere("(de.fin>CURRENT_TIMESTAMP() or de.fin='0000-00-00')")
    		->andWhere("de.activo = 1")
    		->orderBy("p.apellido ASC, p.nombre ASC")
    		->execute();

    	return $q;
    }    
}
