<?php

/**
 * DetalleNotaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleNotaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleNotaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleNota');
    }
}