<?php

/**
 * DocumentacionPlanesEstudiosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentacionPlanesEstudiosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentacionPlanesEstudiosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentacionPlanesEstudios');
    }
    
    // Obtener las documentaciones por Tipo
    public function obtenerDocumentacionesPlanesPorTipo($idtipodocumentacion)
    {
    	$q = Doctrine_Query::create()
    		->select('dp.*')
    		->from('DocumentacionPlanesEstudios dp')
    		->innerjoin('dp.Documentacion do on dp.iddocumentacion=do.iddocumentacion')
    		->where('do.idtipodocumentacion = '.$idtipodocumentacion);
    
    	return $q->execute();
    }
        
    // Obtener los datos especificos de una documantecion
    public function obtenerDocumentacionPlan($idplanestudio, $idtipodocumentacion)
    {
    	$q = Doctrine_Query::create()
    		->select('dp.*')
    		->from('DocumentacionPlanesEstudios dp')
    		->innerjoin('dp.Documentacion do on dp.iddocumentacion=do.iddocumentacion')
    		->where('dp.idplanestudio = '.$idplanestudio)
    		->andWhere('do.idtipodocumentacion = '.$idtipodocumentacion);
    
    	return $q->fetchOne();
    }    
    
    // Obtener las documentaciones por Plan
    public function obtenerDocumentacionesPlanesPorPlan($idplanestudio)
    {
    	$q = Doctrine_Query::create()
    		->select('dp.*')
    		->from('DocumentacionPlanesEstudios dp')
    		->innerjoin('dp.Documentacion do on dp.iddocumentacion=do.iddocumentacion')
    		->innerjoin('do.TiposDocumentacion td on do.idtipodocumentacion=td.idtipodocumentacion')
    		->where('dp.idplanestudio = '.$idplanestudio)
    		->orderBy('td.orden ASC, do.orden ASC');
    
    	return $q->execute();
    }  
}