<?php

/**
 * EmpleadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpleadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpleadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empleados');
    }
    
    // Busca todas los empleados segun los criterios
    public static function buscarEmpleados($tipocriterio, $criterio)
    {
    	if ($tipocriterio == 1) {
    		$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
    			SELECT DISTINCT * 
    				FROM personas pe
    				WHERE
    					((pe.apellido LIKE '%".$criterio."%') OR (pe.nombre LIKE '%".$criterio."%'))
    				ORDER BY pe.apellido ASC, pe.nombre ASC
    		");
		}else{
    		$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
    			SELECT DISTINCT * 
    				FROM personas pe
    				WHERE
    					(pe.nrodoc LIKE '%".$criterio."%')
    				ORDER BY pe.apellido ASC, pe.nombre ASC
    		");
		}		

		return $q;
    }  

    // Obtener empleados activos
    public static function obtenerEmpleadosActivos()
    {
        $sql ="SELECT se.abreviacion as uacademica, per.idpersona, CONCAT(per.apellido,', ',per.nombre) as empleado,
                      IF(per.idsexo=1,'M','F') as sexo, DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(per.fechanac)), '%Y')+0 AS edad,
                      tp.descripcion as cargo, (SELECT descripcion FROM niveles_estudios WHERE idnivelestudio = MAX(IFNULL(ne.idnivelestudio,8)) ) as nivel_educativo, GROUP_CONCAT(DISTINCT est.descripcion  SEPARATOR ',') as titulo
              FROM personas per 
              JOIN empleados emp ON per.idpersona = emp.idpersona
              LEFT JOIN designaciones_empleados de ON emp.idempleado=de.idempleado
              LEFT JOIN tipos_cargos tp ON de.idtipocargo = tp.idtipocargo
              LEFT JOIN sedes se ON de.idsede = se.idsede
              LEFT JOIN estudios est ON per.idpersona = est.idpersona
              LEFT JOIN niveles_estudios ne ON est.idnivelestudio = ne.idnivelestudio
              WHERE emp.activo GROUP BY per.idpersona ORDER BY per.apellido; ";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q;
    } 

    // Obtener empleados activos
    public static function obtenerEmpleadosActivosCantidad()
    {
        $sql ="SELECT COUNT(*) AS cantidad
              FROM personas per 
              JOIN empleados emp ON per.idpersona = emp.idpersona
              LEFT JOIN empleados_sede es ON emp.idempleado=es.idempleado 
              LEFT JOIN designaciones_empleados de ON es.idempleado=de.idempleado
              LEFT JOIN tipos_cargos tp ON de.idtipocargo = tp.idtipocargo
              LEFT JOIN sedes se ON es.idsede = se.idsede
              WHERE emp.activo; ";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        
        return $q[0]["cantidad"];
    }      

}