<?php

/**
 * EquivalenciasAlumnosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquivalenciasAlumnosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquivalenciasAlumnosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquivalenciasAlumnos');
    }
}