<?php

/**
 * EstadosEquivalenciasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosEquivalenciasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosEquivalenciasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadosEquivalencias');
    }
}