<?php

/**
 * EstadosMesasExamenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosMesasExamenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosMesasExamenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadosMesasExamenes');
    }
}