<?php

/**
 * EstadosAlumnoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosAlumnoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosAlumnoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadosAlumno');
    }
    
	public function obtenerAlumnosPorEstado($idplanestudio, $idestado, $inicio, $fin) {
    	$resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
    		SELECT ea.idalumno, ea.idestadoalumno, ea.fecha
    			FROM estados_alumno_historial ea 
    			INNER JOIN alumnos al ON ea.idalumno=al.idalumno
    			INNER JOIN personas pe ON al.idpersona=pe.idpersona
    			INNER JOIN ( 
					SELECT * FROM (
    					SELECT * 
    					FROM estados_alumno_historial
    					ORDER BY fecha DESC, id DESC
					) AS eah
					GROUP BY eah.idalumno
    			) AS maxestadoporalumno 
    			ON ea.idalumno = maxestadoporalumno.idalumno 
    			WHERE ea.fecha = maxestadoporalumno.fecha
    			AND ea.idestadoalumno=".$idestado."
    			AND DATE(ea.fecha) BETWEEN '".$inicio."' AND '".$fin."'
    			AND al.idplanestudio=".$idplanestudio."
    			ORDER BY pe.apellido ASC, pe.nombre ASC"					    	
    	);

		return $resultado;
	}   


	public function obtenerEstados()
	{
		$q = Doctrine_Query::create()
			->from('EstadosAlumno ea');
	
		return $q->execute();    
	}	
	
     
}
