<?php

/**
 * EstadosPlanesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosPlanesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosPlanesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadosPlanes');
    }
}