<?php

/**
 * EstadosMateriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosMateriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosMateriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadosMateria');
    }


    public static function obtenerEstadosMateria() {
    	$q = Doctrine_Query::create()
			->select('em.*')
			->from("EstadosMateria em")
		->orderBy('em.descripcion ASC');

		return $q->execute();  	
    } 

    public static function obtenerEstadosFichaAlumno() {
	$arreglo = array(
	3 => 'Regular',
	9 => 'Aprobado',
	1 => 'Cursando'
	);

	return $arreglo;  	
    } 


}
