<?php

/**
 * ExamenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Examenes');
    }
        
    // Devuelve si el alumno tiene aprobada o no la materia
    public function puedeAprobar($idalumno, $idmesaexamen) 
    {  
    	$resultado = 0;
    	/*$q = Doctrine_Query::create()
			->select('e.*')
			->from('Examenes e')
			->innerJoin('e.MesasExamenes m ON e.idmesaexamen = m.idmesaexamen')
	    	->where('
	    		(e.idalumno = '.$idalumno.') AND 
	    		(e.idmesaexamen = '.$idmesaexamen.') AND 
	    		(
	    			((m.idcondicion=1 OR m.idcondicion=2 OR m.idcondicion=4) AND e.promedio>='.NOTAAPROBACION.') OR 
	    			(m.idcondicion=5 OR m.idcondicion=6) OR
	    			(m.idcondicion=3 AND e.promedio>='.NOTAPROMOCION.')
				)')
	    	->execute();*/
    	
    	// Obtener materias a visualizar en pantalla
    	$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
			SELECT e.* 
    		FROM examenes e
			INNER JOIN mesas_examenes m ON e.idmesaexamen = m.idmesaexamen
    		WHERE
    			(e.idalumno = ".$idalumno.") AND 
	    		(e.idmesaexamen = ".$idmesaexamen.") AND 
	    		(
	    			((m.idcondicion=1 OR m.idcondicion=2 OR m.idcondicion=4) AND (e.promedio>=4 OR e.promedio like 'A%')) OR 
	    			(m.idcondicion=5 OR m.idcondicion=6) OR
	    			(m.idcondicion=3 AND e.promedio>=4)
				)");
  	
		/*foreach($q as $item){
			$resultado = 1;
		}*/
		if (count($q)>0){
			$resultado = 1;
		}
		
        return $resultado;
    }
    
  	// Obtiene las mesas de examenes inscriptas de un alumno
    public function getMesasInscripto($idalumno) 
    {
    	$q = Doctrine_Query::create()
			->select('e.*')
			->from('Examenes e')
			->innerJoin('e.MesasExamenes m ON e.idmesaexamen = m.idmesaexamen')
	    	->where('e.idalumno = '.$idalumno)
	    	->andWhere('(m.idestadomesaexamen = 1) or (m.idestadomesaexamen = 2)')
	    	->groupBy('e.idmesaexamen');
		
		return $q->execute();
    }
    
    // Obtiene la calificacion de un alumno
    public function getExamen($idalumno, $idmesaexamen) 
    {
    	$q = Doctrine_Query::create()
			->select('e.*')
			->from('Examenes e')
	    	->where('(e.idalumno = '.$idalumno.') AND (e.idmesaexamen = '.$idmesaexamen.')');
 	
		return $q->fetchOne();
    }        

    // Obtiene ultimo examen rendido de esa materia
    public function getUltimoExamen($idalumno, $idcatedra) 
    {
    	$q = Doctrine_Query::create()
			->select('e.*')
			->from('Examenes e')
			->innerJoin('e.MesasExamenes m ON e.idmesaexamen = m.idmesaexamen')
	    	->where('(e.idalumno = '.$idalumno.') AND (m.idcatedra = '.$idcatedra.')')
	    	->orderBy('m.fecha DESC');
 	
		return $q->fetchOne();
    }    

    // Obtiene el historial de examenes de esa materia
    public function getHistorialExamenes($idalumno, $idcatedra)
    {
    	$q = Doctrine_Query::create()
    	->select('e.*, m.fecha as fecha, m.hora as hora, m.folio as folio, l.descripcion as libro, c.condicion as condicion')
    	->from('Examenes e')
    	->innerJoin('e.MesasExamenes m ON e.idmesaexamen = m.idmesaexamen')
    	->innerJoin('m.LibrosActas l ON m.idlibroacta = l.idlibroacta')
    	->innerJoin('m.CondicionesMesas c ON m.idcondicion = c.idcondicion')
    	->where('(e.idalumno = '.$idalumno.') AND (m.idcatedra = '.$idcatedra.')')
    	->orderBy('m.fecha DESC');
    
    	return $q->execute();
    } 


    // Obtiene la calificacion de un alumno
    public function borrarExamen($idalumno, $idmesaexamen) 
    {
    	$q = Doctrine_Query::create()
			->delete('Examenes e')
	    	->where('(e.idalumno = '.$idalumno.') AND (e.idmesaexamen = '.$idmesaexamen.')');
 	
		return $q->execute();
    }        



   
}
