<?php

/**
 * Examenes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Examenes extends BaseExamenes
{
    public function __toString() {
        return $this->getCalificacion();
    }		
}
