<?php

/**
 * ExpedientesDerivaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExpedientesDerivaciones extends BaseExpedientesDerivaciones
{
	// Obtiene el area de origen
	public function obtenerAreaOrigen()
	{
		$q = Doctrine_Query::create()
		->select('*')
		->from('Areas a')
		->where('a.idarea = '.$this->getIdareaorigen());
	
		return $q->fetchOne();
	}	
	
	// Obtiene el area de destino
	public function obtenerAreaDestino()
	{
		$q = Doctrine_Query::create()
		->select('*')
		->from('Areas a')
		->where('a.idarea = '.$this->getIdareadestino());
	
		return $q->fetchOne();
	}	
}
