<?php

/**
 * Facultades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Facultades extends BaseFacultades
{
    public function __toString() {
        return $this->getNombre();
    }	
    
    // Busca si otra persona tiene ese legajo en la facultad
    public function buscarLegajo($legajo, $idpersona) 
    {
	   	$q = Doctrine_Query::create()
			->select('a.*')
			->from('Alumnos a')
			->innerJoin('a.PlanesEstudios p ON a.idplanestudio = p.idplanestudio')
			->innerJoin('p.Carreras c ON p.idcarrera = c.idcarrera')
    		->where('c.idfacultad = '.$this->idfacultad)    		
    		->andWhere('((a.legajo like "'.$legajo.'" AND a.idpersona != '.$idpersona.'))');
		
		//return "SQL: ".$q->getSqlQuery();
		return $q->execute();
    }      

    // Busca si existe la persona tiene legajo en la facultad
    public function buscarLegajoPorPersona($idpersona) 
    {
	   	$q = Doctrine_Query::create()
			->select('a.*')
			->from('Alumnos a')
			->innerJoin('a.PlanesEstudios p ON a.idplanestudio = p.idplanestudio')
			->innerJoin('p.Carreras c ON p.idcarrera = c.idcarrera')
	   		->where('c.idfacultad = '.$this->idfacultad)
	   		->andWhere('a.idpersona = '.$idpersona);
   
		return $q->execute();
    }      

    // Obtiene facultades por area
    public function obtenerCarrerasSedes($idsede)
    {
    	$q = Doctrine_Query::create()
    		->select('cs.*')
    		->from('CarrerasSede cs')
    		->innerJoin('cs.Carreras ca ON cs.idcarrera = ca.idcarrera')
    		->where('ca.idfacultad = '.$this->idfacultad)
    		->andWhere('cs.idsede = '.$idsede);
    	 
    	return $q->execute();    
    }    
}
