<?php

/**
 * FichaCargaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FichaCargaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FichaCargaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FichaCarga');
    }
}