<?php

/**
 * FichaAlumnosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FichaAlumnosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FichaAlumnosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FichaAlumnos');
    }
}