<?php

/**
 * HistoricoConsultasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoricoConsultasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoricoConsultasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistoricoConsultas');
    }
       
    // Obtiene el historico por usuario
    public static function obtenerHistorico($usuario)
    {
		if ($usuario == "") {
			$q = Doctrine_Query::create()
  				->select('h.*')
    			->from('HistoricoConsultas h');			
		} else {	
			$q = Doctrine_Query::create()
  				->select('h.*')
    			->from('HistoricoConsultas h')
    			->where('h.usuario like "'.$usuario.'%"');
		}

		return $q->execute();
    }         
}