<?php

/**
 * InscripcionesCicloLectivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InscripcionesCicloLectivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InscripcionesCicloLectivoTable
     */
  public static function getInstance()
  {
	return Doctrine_Core::getTable('InscripcionesCicloLectivo');
  }

  public function getControlActivo($idciclo,$idalumno)
  {
	$q = Doctrine_Query::create()
		->from('InscripcionesCicloLectivo i')
		->where('i.idciclolectivo  = ?' , $idciclo)
		->andWhere('i.idalumno = ?' , $idalumno);

	if(count($q->fetchOne())!=1) {
		return true;
	} else {
		return false;
	}	 
   }		

}