<?php

/**
 * InscripcionesMesasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InscripcionesMesasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InscripcionesMesasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InscripcionesMesas');
    }



    // Obtiene los alumnos inscriptos a mesas
  	public static function getAlumnosInscriptosMesas($idcatedra, $idllamado, $idcondicion=0)
 	{
	    $arreglo = array();
 		$q = Doctrine_Query::create()
	  		->select('im.*')
	 		->from('InscripcionesMesas im')		
	 		->innerJoin('im.Alumnos al on im.idalumno=al.idalumno')
	 		->innerJoin('al.Personas pe on al.idpersona=pe.idpersona')
	    	->where('im.idcatedra = '.$idcatedra)
	    	->andWhere('im.idllamado = '.$idllamado)
	    	->orderBy('pe.apellido ASC, pe.nombre ASC')
	    	->execute();

		foreach($q as $item) {
			$arreglo[$item->getIdalumno()]=$item->getAlumnos();
		} 

	return $arreglo;
    } 


    // Obtiene inscripcion de alumno
    public function getInscripcionMesa($idalumno,$idcatedra,$idllamado) 
    {
  
    	
    	$q = Doctrine_Query::create()
			->from("InscripcionesMesas")
	    	->where("idalumno = ".$idalumno)
		->andWhere("idcatedra = ".$idcatedra);
		//->andWhere("idllamado =".$idllamado);


	return $q->fetchOne();
    }  

    // Obtiene inscripcion de alumno
    public function actualizarDatosInscripcionMesa($idalumno,$idcatedra,$idmesa) 
    {
    	$q = Doctrine_Query::create()
		  ->update('InscripcionesMesa im')
		  ->set('im.idmesa', '?', $idmesa)
	    	->where("idalumno = ".$idalumno)
		->andWhere("idcatedra = ".$idcatedra)->execute();
    }  


  	// Obtiene las mesas de examenes inscriptas de un alumno
    public function getMesasInscripto($idalumno) 
    {
    	$q = Doctrine_Query::create()
			->select('*')
			->from('InscripcionesMesas im')
	    	->where('im.idalumno = '.$idalumno);
		
		return $q->execute();
    }

    // Obtiene la calificacion de un alumno
    public function getInscripcion($idinscripcion) 
    {
    	$q = Doctrine_Query::create()
			->select('*')
			->from('InscripcionesMesas im')
	    	->where('im.idinscripcion = '.$idinscripcion);

		return $q->fetchOne();
    }  

    // Obtiene inscripcion de alumno
   /* public function getInscripcionAlumnoMesa($idalumno,$idcatedra,$idllamado=1) 
    {
  
    	
    	$q = Doctrine_Query::create()
			->select('im.*')
			->from("InscripcionesMesas im")
	    	->where("(im.idalumno = ".$idalumno.") AND (im.idcatedra = ".$idcatedra." AND im.llamado=".$idllamado.")")->execute();

		foreach($q as $item) {
			$arreglo[$item->getIdalumno()]=$item->getAlumnos();
		}

	return $item;
    }     */

}


