<?php

/**
 * LibredeudaTramitesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibredeudaTramitesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibredeudaTramitesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibredeudaTramites');
    }
}