<?php

/**
 * ListaHorariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListaHorariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListaHorariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListaHorarios');
    }

    // ACTUALIZAR LISTA ACTIVA segun corresponda
    public static function activarLista($idlistahorario)
    {
        
        // activar lista de horarios
        $sql ="UPDATE lista_horarios SET activa = if(id= ".$idlistahorario.",true,false);";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        return $q->execute($sql);
    }
}