<?php

/**
 * MateriasGenericas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MateriasGenericas extends BaseMateriasGenericas
{
    public function getMateriasComponentes()
    {   	
		$oMateriaPlan = Doctrine_Core::getTable('MateriasPlanes')->find($this->getIdmateriaplan());
		
        return $oMateriaPlan;
    }	
}
