<?php

/**
 * MateriasGenericasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MateriasGenericasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MateriasGenericasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MateriasGenericas');
    }
    
    // Obtener catedra
    public function obtenerValorMateriaOptativa($idmateriaplangenerica, $idmateriaplan)
    {
    	$q = Doctrine_Query::create()
    		->select('mg.*')
    		->from('MateriasGenericas mg')
   			->where('mg.idmateriaplangenerica = '.$idmateriaplangenerica)
   			->andWhere('mg.idmateriaplan = '.$idmateriaplan)
    		->fetchOne();
    	 
    	return $q->valormateria;    	
    }    
}