<?php

/**
 * MotivosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MotivosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MotivosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Motivos');
    }

    // Obtener todos los motivos
    public function obtenerMotivos()
    {
    	$q = Doctrine_Query::create()
    	->select('m.*')
    	->from('Motivos m');
    	 
    	return $q->execute();
    }    
}