<?php

/**
 * NivelesEstudiosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelesEstudiosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelesEstudiosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NivelesEstudios');
    }

    public function obtenerNivelesEstudios($formacion_docente)
	{
		$estado = false;
        if ($formacion_docente=='true') $estado=true;

        $q = Doctrine_Query::create()
			->from('NivelesEstudios ne')
			->where('formaciondocente = ?', $estado)
			->orderBy('idordenimportancia ASC');
	
		return $q->execute();    
	}	
}