<?php

/**
 * NoticiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoticiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Noticias');
    }   
    
    // Obtiene las noticias vigente por area
    public function obtenerNoticiasPorArea($idarea, $idsede, $activo) {
    	$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
			SELECT DISTINCT N.*
				FROM noticias N
				INNER JOIN profile PR
					ON N.idusuario = PR.sf_guard_user_id
				WHERE N.is_active ='". $activo."' AND PR.idarea=".$idarea." AND PR.idsede=".$idsede."
    			ORDER BY N.orden DESC"
    	);
    	    
    	return $q;
    }
        
	// Obtiene las noticias vigente por usuario
	public function obtenerNoticiasPorUsuario($idusuario, $activo) {
		$q = Doctrine_Query::create()
  			->select('n.*')
    		->from('Noticias n')
    		->where('n.idusuario = '. $idusuario)
    		->andWhere('n.is_active = '. $activo)
    		->execute();
		
		return $q;  
	} 

	// Obtiene las noticias vigente por usuario
	public function obtenerNoticiasPrivadasPorUsuario($idusuario, $activo) {
		$q = Doctrine_Query::create()
  			->select('n.*')
    		->from('Noticias n')
    		->where('n.idusuario = '. $idusuario)
    		->andWhere('n.is_active = '. $activo)
    		->andWhere('n.privada = 1')
    		->execute();
		
		return $q;  
	} 
	
	// Obtiene las noticias vigente para una persona
	public function obtenerNoticiasPorCarrera($idCarrera) {
		$fecha = date('Y-m-d');
		// Obtener materias a visualizar en pantalla
		$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
			SELECT DISTINCT N.* 
				FROM noticias N	
				INNER JOIN noticias_carrera NC 
					ON N.id = NC.idnoticia				
				INNER JOIN planes_estudios P 
					ON NC.idcarrera = P.idcarrera				
				INNER JOIN alumnos A 
					ON P.idplanestudio = A.idplanestudio					
				WHERE   ('". $fecha."' BETWEEN N.inicio AND N.fin) AND (P.idcarrera = ".$idCarrera.") AND (N.is_active = 1)
				ORDER BY N.orden DESC"
		);
		//('". $fecha."' BETWEEN N.inicio AND N.fin) AND (P.idcarrera = ".$idCarrera.") AND
		return $q;  

	}  	

	// Obtiene las noticias vigente para una persona
	public function obtenerNoticiasPrivadasPorCarrera($idCarrera,$idsede) {
		$fecha = date('Y-m-d');
		// Obtener materias a visualizar en pantalla
		$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
			SELECT DISTINCT N.* 
				FROM noticias N	
				INNER JOIN noticias_carrera NC 
					ON N.id = NC.idnoticia				
				INNER JOIN planes_estudios P 
					ON NC.idcarrera = P.idcarrera				
				INNER JOIN alumnos A 
					ON P.idplanestudio = A.idplanestudio					
				WHERE   ('". $fecha."' BETWEEN N.inicio AND N.fin) AND (P.idcarrera in (".$idCarrera.")) AND (N.is_active = 1) AND (privada = 1)
				ORDER BY N.orden DESC"
		);
		//('". $fecha."' BETWEEN N.inicio AND N.fin) AND (P.idcarrera = ".$idCarrera.") AND
		return $q;  
	}  		
}