<?php

/**
 * PacientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pacientes');
    }

     // Obtener obras sociales
    public static function obtenerPacientesActivos($estado=NULL)
    {
        $sql ="SELECT id, apellido, nombre FROM pacientes WHERE 1 = 1 ";

      //  if($estado !== NULL)
        //    $sql .=  " AND activo = ".$estado." "; 

        $sql .= " ORDER BY apellido;";
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    } 
}