<?php

/**
 * PeriodosCursadasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodosCursadasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeriodosCursadasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PeriodosCursadas');
    }
}