<?php

/**
 * PeriodosCiclosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodosCiclosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeriodosCiclosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PeriodosCiclos');
    }
}