<?php

/**
 * PlanesDependientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanesDependientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanesDependientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanesDependientes');
    }
}