<?php

/**
 * Planilla TP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlanillaTP extends PDF 
{
  //********** Funcion Esquema Planilla TP*************
  public function EsquemaPlanillaTP1eraHoja($bucles)
  {  
	//	ESQUEMA GRÁFICO
	// Define un alias para el número de páginas del documento pdf
	$this->AliasNbPages();
	// Asigna el ancho a las lineas verticales
	$this->SetLineWidth(0);
	// Linea vertical que divide los datos de la asignatura con las firmas
	$this->Line(70,36,70,63);
	// Linea vertical que divide las firmas con las conceptos
	$this->Line(175,36,175,63);
	// Linea vertical que divide los conceptos con las condiciones
	$this->Line(250,36,250,63);
	// Lineas verticales que marca las columnas de la planilla
	$this->Line(12,63,12,188);
	$this->Line(70,63,70,188);
	$this->Line(95,63,95,188);
	$this->Line(120,63,120,188);
	$this->Line(145,63,145,188);
	$this->Line(175,63,175,188);
	$this->Line(195,63,195,188);
	$this->Line(225,63,225,188);
	$this->Line(250,63,250,188);
	// Linea horizontal que separa la Asignatura
	$this->Line(5,50,70,50);
	// Linea horizontal que separa la Fecha
	$this->Line(5,67,350,67);
	// Asigna el ancho a la linea
	$this->SetLineWidth(1);
	// Linea horizontal que separa la cabecera del listado
	$this->Line(6,63,349,63);
	
	// ESQUEMA DE CONTENIDO
	// Muestra la Asignatura
	$this->SetFont('Times','',10);
	$this->SetXY(6,36.5);
	$this->Cell(70,5,"MATERIA:",0,1,'L');
	$this->SetXY(72,36.5);
	$this->Cell(65,5,"PROFESORES:",0,1,'L');
	$this->SetXY(75,42);
	$this->Cell(65,5,"Prof. Titular:",0,1,'L');
	$this->SetXY(97,42);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	$this->SetXY(75,47);
	$this->Cell(65,5,"Prof. Adjunto:",0,1,'L');
	$this->SetXY(97,47);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	$this->SetXY(75,52);
	$this->Cell(65,5,"J.T.P.:",0,1,'L');
	$this->SetXY(97,52);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	$this->SetXY(75,57);
	$this->Cell(65,5,"Ayudante:",0,1,'L');
	$this->SetXY(97,57);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	// Conceptos
	$this->SetXY(177,36.5);
	$this->Cell(65,5,"CONCEPTO:",0,1,'L');
	$this->SetXY(180,42);
	$this->Cell(65,5,"0 Reprobado",0,1,'L');
	$this->SetXY(180,46);
	$this->Cell(65,5,"1 Desaprobado",0,1,'L');
	$this->SetXY(180,50);
	$this->Cell(65,5,"2 y 3 Insuficiente",0,1,'L');
	$this->SetXY(180,54);
	$this->Cell(65,5,"4 y 5 Aprobado",0,1,'L');
	$this->SetXY(215,42);
	$this->Cell(65,5,"6 y 7 Bueno",0,1,'L');
	$this->SetXY(215,46);
	$this->Cell(65,5,"8 y 9 Distinguido",0,1,'L');
	$this->SetXY(215,50);
	$this->Cell(65,5,"10 Sobresaliente",0,1,'L');
	// Condiciones
	$this->SetXY(252,36.5);
	$this->Cell(65,5,"CONDICION FINAL:",0,1,'L');
	$this->SetXY(255,42);
	$this->Cell(75,5,"REGULAR: 80% Asist. y 75% Práct. Aprobados",0,1,'L');
	$this->SetXY(255,46);
	$this->Cell(75,5,"LIBRE: 50% y 80% Asist., 50% y 75% Práct. Aprobados",0,1,'L');
	$this->SetXY(255,50);
	$this->Cell(75,5,"RECURSA: Menos de 50% Asist. y Práct. Aprobados",0,1,'L');
	$this->SetXY(305,57);
	$this->Cell(20,5,"Fecha: ____/____/________",0,1,'L');
	// Muestra la cabecera de la lista
	$this->SetFont('Times','',9);
	$this->SetXY(6,63);
	$this->Cell(6,5,"Nro.",0,1,'C');
	$this->SetXY(12,63);
	$this->Cell(58,5,"ALUMNOS",0,1,'C');
	$this->SetXY(70,63);
	$this->Cell(25,5,"T.P. Aprobados",0,1,'C');
	$this->SetXY(95,63);
	$this->Cell(25,5,"T.P. Desaprobados",0,1,'C');
	$this->SetXY(120,63);
	$this->Cell(25,5,"T.P. a Recuperar",0,1,'C');
	$this->SetXY(145,63);
	$this->Cell(30,5,"Parciales Aprobados",0,1,'C');
	$this->SetXY(175,63);
	$this->Cell(20,5,"CONCEPTO",0,1,'C');
	$this->SetXY(195,63);
	$this->Cell(30,5,"Parciales a Recuperar",0,1,'C');
	$this->SetXY(225,63);
	$this->Cell(25,5,"Condición Final",0,1,'C');
	$this->SetXY(250,63);
	$this->Cell(100,5,"Observaciones",0,1,'C');  	
  }  


  public function EsquemaPlanillaRegularidades($bucles)
  {  
	//	ESQUEMA GRÁFICO
	// Define un alias para el número de páginas del documento pdf
	$this->AliasNbPages();
	// Asigna el ancho a las lineas verticales
	$this->SetLineWidth(0);
	// Linea vertical que divide los datos de la asignatura con las firmas
	$this->Line(70,36,70,63);
	// Linea vertical que divide las firmas con las conceptos
	$this->Line(175,36,175,63);
	// Linea vertical que divide los conceptos con las condiciones
	//$this->Line(250,36,250,63);
	// Lineas verticales que marca las columnas de la planilla
	$this->Line(12,63,12,188);
	$this->Line(70,63,70,188);
	$this->Line(95,63,95,188);
	$this->Line(120,63,120,188);
	$this->Line(145,63,145,188);
	$this->Line(175,63,175,188);
	$this->Line(195,63,195,188);
	$this->Line(225,63,225,188);
	$this->Line(250,63,250,188);
	// Linea horizontal que separa la Asignatura
	$this->Line(5,50,70,50);
	// Linea horizontal que separa la Fecha
	$this->Line(5,67,350,67);
	// Asigna el ancho a la linea
	$this->SetLineWidth(1);
	// Linea horizontal que separa la cabecera del listado
	$this->Line(6,63,349,63);
	
	// ESQUEMA DE CONTENIDO
	// Muestra la Asignatura
	$this->SetFont('Times','',10);
	$this->SetXY(6,36.5);
	$this->Cell(70,5,"MATERIA:",0,1,'L');
	$this->SetXY(72,36.5);
	$this->Cell(65,5,"PROFESORES:",0,1,'L');
	$this->SetXY(75,42);
	$this->Cell(65,5,"Prof. Titular:",0,1,'L');
	$this->SetXY(97,42);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	$this->SetXY(75,47);
	$this->Cell(65,5,"Prof. Adjunto:",0,1,'L');
	$this->SetXY(97,47);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	$this->SetXY(75,52);
	$this->Cell(65,5,"J.T.P.:",0,1,'L');
	$this->SetXY(97,52);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);
	$this->SetXY(75,57);
	$this->Cell(65,5,"Ayudante:",0,1,'L');
	$this->SetXY(97,57);
	$this->MultiCell(75,3,"________________________________________",0,'C',0);

	// Condiciones
	$this->SetXY(180,36.5);
	$this->Cell(65,5,"* REGULAR: 80% Asistencia",0,1,'L');
	$this->SetXY(180,42);
	$this->Cell(75,5,"* LIBRE:",0,1,'L');
	$this->SetXY(180,46);
	$this->Cell(75,5,"* PROMOCIÓN: aquellos casos que hayan sido autorizados por Decanato o por Coordinación y estén especificado ",0,1,'L');
	$this->SetXY(180,50);
	$this->Cell(75,5,"en el programa de la asignatura (asistencia 80 %) y 8 (ocho) o más en todos los parciales.",0,1,'L');

	$this->SetXY(180,57);
	$this->Cell(20,5," Sr. Profesor queda terminantemente prohibido agregar alumnos a las listas.",0,1,'L');
//  
	$this->SetXY(305,57);
	$this->Cell(20,5,"Fecha: ____/____/________",0,1,'L');
	// Muestra la cabecera de la lista
	$this->SetFont('Times','',9);
	$this->SetXY(6,63);
	$this->Cell(6,5,"Nro.",0,1,'C');
	$this->SetXY(12,63);
	$this->Cell(58,5,"ALUMNOS",0,1,'C');
	$this->SetXY(70,63);
	$this->Cell(25,5,"Parcial 1",0,1,'C');
	$this->SetXY(95,63);
	$this->Cell(25,5,"Recuperatorio",0,1,'C');
	$this->SetXY(120,63);
	$this->Cell(25,5,"Parcial 2",0,1,'C');
	$this->SetXY(145,63);
	$this->Cell(30,5,"Recuperatorio",0,1,'C');
	$this->SetXY(175,63);
	$this->Cell(20,5,"Parcial 3",0,1,'C');
	$this->SetXY(195,63);
	$this->Cell(30,5,"Recuperatorio",0,1,'C');
	$this->SetXY(225,63);
	$this->Cell(25,5,"% Asistencia",0,1,'C');
	$this->SetXY(250,63);
	$this->Cell(100,5,"* Situación Final",0,1,'C');  	
  }  
  

  

  //********** Funcion Esquema Planilla TP*************
  public function EsquemaPlanillaRegularidades2daHoja($bucles)
  {  
	// Agrega una nueva pagina
	$this->AddPage('L');
	// Asigna el ancho a la linea
	$this->SetLineWidth(1);
	// Linea horizontal que separa las Fechas y la cabecera del listado
	$this->Line(6,9.5,349,9.5);
	// Muestra la cabecera de la lista
	$this->SetFont('Times','',9);
	$this->SetXY(6,5);
	$this->Cell(6,5,"Nro.",0,1,'C');
	$this->SetXY(12,5);
	$this->Cell(58,5,"ALUMNOS",0,1,'C');
	$this->SetXY(70,5);
	$this->Cell(25,5,"Parcial 1",0,1,'C');
	$this->SetXY(95,5);
	$this->Cell(25,5,"Recuperatorio",0,1,'C');
	$this->SetXY(120,5);
	$this->Cell(25,5,"Parcial 2",0,1,'C');
	$this->SetXY(145,5);
	$this->Cell(30,5,"Recuperatorio",0,1,'C');
	$this->SetXY(175,5);
	$this->Cell(20,5,"Parcial 3",0,1,'C');
	$this->SetXY(195,5);
	$this->Cell(30,5,"Recuperatorio",0,1,'C');
	$this->SetXY(225,5);
	$this->Cell(25,5,"% Asistencia",0,1,'C');
	$this->SetXY(250,5);
	$this->Cell(100,5,"* Situación Final",0,1,'C');
	
	$this->SetXY(120,3);  	
  }  


  //********** Funcion Esquema Planilla TP*************
  public function EsquemaPlanillaTP2daHoja($bucles)
  {  
	// Agrega una nueva pagina
	$this->AddPage('L');
	// Asigna el ancho a la linea
	$this->SetLineWidth(1);
	// Linea horizontal que separa las Fechas y la cabecera del listado
	$this->Line(6,9.5,349,9.5);
	// Muestra la cabecera de la lista
	$this->SetFont('Times','',9);
	$this->SetXY(6,5);
	$this->Cell(6,5,"Nro.",0,1,'C');
	$this->SetXY(12,5);
	$this->Cell(58,5,"ALUMNOS",0,1,'C');
	$this->SetXY(70,5);
	$this->Cell(25,5,"T.P. Aprobados",0,1,'C');
	$this->SetXY(95,5);
	$this->Cell(25,5,"T.P. Desaprobados",0,1,'C');
	$this->SetXY(120,5);
	$this->Cell(25,5,"T.P. a Recuperar",0,1,'C');
	$this->SetXY(145,5);
	$this->Cell(30,5,"Parciales Aprobados",0,1,'C');
	$this->SetXY(175,5);
	$this->Cell(20,5,"CONCEPTO",0,1,'C');
	$this->SetXY(195,5);
	$this->Cell(30,5,"Parciales a Recuperar",0,1,'C');
	$this->SetXY(225,5);
	$this->Cell(25,5,"Condición Final",0,1,'C');
	$this->SetXY(250,5);
	$this->Cell(100,5,"Observaciones",0,1,'C');
	
	$this->SetXY(120,3);  	
  }  
}
