<?php

/**
 * ProfesionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profesiones');
    }
}