<?php

/**
 * PDF
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class profPDF extends sfTCPDF
{
   
    	
   public function Header(){

	    $direccion = '8 de Junio 522'; $localidad='Concepcion del Uruguay - ER - Argentina ';
	    $telefono='Tel./Fax: 00 54 3442 425606 / 427721';

	    switch (sfContext::getInstance()->getUser()->getAttribute('id_sede','')) {
	    case '1':
	        $direccion ='8 de Junio 522';
	        $localidad = 'E3260ANJ Concepción del Uruguay - ER - Argentina ';
	        $telefono = 'Tel./Fax: 00 54 3442 425606 / 427721';
	        break;
	    case '2':
	        $direccion ='Luis N. Palma 1125';
	        $localidad = 'E2820AJK Gualeguaychú - ER - Argentina ';
	        $telefono = 'Tel./Fax: 00 54 3446-426852 / 435312';
	        break;
	    case '3':
	        $direccion ='25 de Mayo 339';
	        $localidad = 'E3240ABG Villaguay - ER - Argentina ';
	        $telefono = 'Tel./Fax: 00 54 3455-424830';
	        break;
	    case '4':
	        $direccion ='Avenida Pellegrini 1556';
	        $localidad = 'S2000BUP Rosario - SF - Argentina ';
	        $telefono = 'Tel./Fax: 00 54 0341-4484430 / 4484433';
	        break;
	    case '5':
	        $direccion ='Tucumán 2721 (1º Piso)';
	        $localidad = 'S3000CAI Santa Fe - SF - Argentina ';
	        $telefono = 'Tel.: 00 54 342-4558371/ 4525658';
	        break;
	    case '6':
	        $direccion ='25 de mayo 46';
	        $localidad = 'E3100AND Paraná - ER - Argentina ';
	        $telefono = 'Tel./Fax: 00 54 343-4231547';
	        break;
	    default:
	        $direccion ='8 de Junio 522';
	        $localidad = 'E3260ANJ Concepción del Uruguay - ER - Argentina ';
	        $telefono = 'Tel./Fax: 00 54 3442 425606 / 427721';
	        break;
	    }

	   	parent::Header();
	   	$this->SetFont("Times", "", 10);
	    $this->SetXY(110,2);
	    $this->Write (20, $direccion); //1° Write
	    $this->SetXY(110,4);
	    $this->Write (25, $localidad); //1° Write
	    $this->SetXY(110,6);
	    $this->Write (30, $telefono); //1° Write
	    $this->SetFont("Times", "", 12);
   }

  //********** Funcion Cabecera*************  
  public function Cabecera($facultad,$carrera,$titulo)
  {
	// Configura el auto-salto de pagina
	$this->SetAutoPageBreak(1, 0);
	// Agrega una nueva página al documento pdf
	$this->AddPage();
	
  	if($this->PageNo()==1){
		// Muestra la imagen del Logo de la UCU
		$this->Image('images/CabeceraSIG-UCU.jpg',10,5,192);
		$this->SetXY(35,7);
		// Establece la fuente: Times Negrita 14
		$this->SetFont('Times','B',13);
		// Asigna el ancho al borde
		$this->SetLineWidth(0);
		// Rectangulo Superior
		$this->Rect(10,5,190,31);
		//Asigna el ancho de la linea
		$this->SetLineWidth(0);
		// Linea horizontal que separa la cabecera y el nombre del documento
		$this->Line(10,30,200,30);
		// Asigna la posicion del eje Y
		$this->SetXY(58,15);
		// Muestra el Nombre de la Facultad
		$this->MultiCell(140,5,$facultad,0,'R');
		// Asigna la posicion del eje Y e X
		$this->SetXY(58,20);
		// Asigna el tamaño de la Fuente
		$this->SetFontSize(12);
		// Muestra la carrera
		$this->MultiCell(140,5,$carrera,0,'R');
		// Asigna la posicion del eje Y
		$this->SetY(28);
		// Muestra el titulo
		$this->Cell(0,10,$titulo,0,1,'C');
	}else{
		// Asigna el ancho al borde
		$this->SetLineWidth(0);
		// Asigna la posicion del eje Y
		$this->SetXY(88,6);
	}
  }   

  //********** Funcion Cabecera Oficio*************
  public function CabeceraOficio($facultad,$carrera,$titulo)
  {
	// Configura el auto-salto de pagina
	$this->SetAutoPageBreak(1 , 0);
	// Agrega una nueva página al documento pdf
	$this->AddPage('P','Legal');

	if($this->PageNo()==1){
		// Muestra la imagen del Logo de la UCU
		$this->Image('images/CabeceraSIG-UCU.jpg',11,5,190);
		$this->SetXY(35,7);
		// Establece la fuente: Times Negrita 13
		$this->SetFont('Times','B',13);
		// Asigna el ancho al borde
		$this->SetLineWidth(0);
		// Rectangulo Superior
		$this->Rect(10,5,195,31);
		//Asigna el ancho de la linea
		$this->SetLineWidth(0);
		// Linea horizontal que separa la cabecera y el nombre del documento
		$this->Line(10,30.5,205,30.5);
		// Asigna la posicion del eje Y
		$this->SetXY(55,15);
		// Muestra el Nombre de la Facultad
		$this->MultiCell(150,5,$facultad,0,'R');
		// Asigna la posicion del eje Y e X
		$this->SetXY(55,20);
		// Asigna el tamaño de la Fuente
		$this->SetFontSize(12);
		// Muestra la carrera
		$this->MultiCell(150,5,$carrera,0,'R');
		// Asigna la posicion del eje Y
		$this->SetY(28.5);
		// Muestra el titulo
		$this->Cell(0,10,$titulo,0,1,'C');
	}else{
		// Asigna el ancho al borde
		$this->SetLineWidth(0);
		// Asigna la posicion del eje Y
		$this->SetXY(88,6);
	}
  }

  //********** Funcion Cabecera Apaisada*************
  public function CabeceraApaisada($facultad,$carrera,$titulo)
  {
	// Configura el auto-salto de pagina
	$this->SetAutoPageBreak(1 , 0);
	// Agrega una nueva página al documento pdf
	$this->AddPage('L');
	
  	if($this->PageNo()==1){
		// Muestra la imagen del Logo de la UCU
		$this->Image('images/CabeceraSIG-UCU2.jpg',6,5,342,25);
		$this->SetXY(35,7);
		// Establece la fuente: Times Negrita 14
		$this->SetFont('Times','B',13);
		// Asigna el ancho al borde
		$this->SetLineWidth(0);
		// Rectangulo Superior
		$this->Rect(5,5,345,31);
		//Asigna el ancho de la linea
		$this->SetLineWidth(0);
		// Linea horizontal que separa la cabecera y el nombre del documento
		$this->Line(5,30.5,350,30.5);
		// Asigna la posicion del eje Y
		$this->SetXY(148,15);
		// Muestra el Nombre de la Facultad
		$this->MultiCell(200,5,$facultad,0,'R');
		// Asigna la posicion del eje Y e X
		$this->SetXY(198,20);
		// Asigna el tamaño de la Fuente
		$this->SetFontSize(12);
		// Muestra la carrera
		$this->MultiCell(150,5,$carrera,0,'R');
		// Asigna la posicion del eje Y
		$this->SetY(28.5);
		// Muestra el titulo
		$this->Cell(0,10,$titulo,0,1,'C');
	}else{
		// Asigna el ancho al borde
		$this->SetLineWidth(0);
		// Asigna la posicion del eje Y
		$this->SetXY(88,6);
	}
  }

  //********** Funcion Pie Apaisada *************
  public function PieApaisada($idsede)
  {
	// Rectangulo Página completa
	$this->Rect(5,5,345,200);
	// Asigna el ancho de la linea
	$this->SetLineWidth(0);
	// Linea horizontal que separa el pie y el documento
	$this->Line(5,188,350,188);
	// Muestra la imagen del Logo de la UCU con direccion dependientdo de parametro 
	if ($idsede==2) {
		$this->Image('images/PieSIG-UCU-GCHU.jpg',6,189,342,15);
	} elseif ($idsede==3) {
		$this->Image('images/PieSIG-UCU-VGUAY.jpg',6,189,342,15);
	} else {
		$this->Image('images/PieSIG-UCU.jpg',6,189,342,15);
	}
	$this->SetXY(8,-19);

	// Formato del pie de pagina: Times Italic 8
	$this->SetFont('Times','',8);
	 // Muestra el número de página
	$this->Cell(5,0,'Página '.$this->PageNo().'/{nb}',0,0,'L');
  }

  //********** Funcion Pie Oficio *************
  public function PieOficio($idsede)
  {
	// Rectangulo Página completa
	//$this->Rect(10,5,195,346);
	//Asigna el ancho de la linea
	$this->SetLineWidth(0);
	// Linea horizontal que separa el pie y el documento
	$this->Line(10,340,205,340);
	// Muestra la imagen del Logo de la UCU con direccion dependientdo de parametro 
	if ($idsede==2) {
		$this->Image('images/PieSIG-UCU-GCHU.jpg',11,341,193);
	} elseif ($idsede==3) {
		$this->Image('images/PieSIG-UCU-VGUAY.jpg',11,340.5,193);	
	} else {
		$this->Image('images/PieSIG-UCU.jpg',11,340.5,193);
	}
	$this->SetXY(11,-10);

	// Formato del pie de pagina: Times Italic 8
	$this->SetFont('Times','',8);
	// Muestra el número de página
	//$this->Cell(5,0,'Página '.$this->PageNo().'/{nb}',0,0,'L');
  }
  
  //********** Funcion Pie*************
  public function Pie($idsede)
  {
	// Rectangulo Página completa
	$this->Rect(10,5,190,290);
	//Asigna el ancho de la linea
	$this->SetLineWidth(0);
	// Linea horizontal que separa el pie y el documento
	$this->Line(10,284,200,284);
	// Muestra la imagen del Logo de la UCU con direccion dependientdo de parametro 
	if ($idsede==2) {
		$this->Image('images/PieSIG-UCU-GCHU.jpg',11,285,188);
	} elseif ($idsede==3) {
		$this->Image('images/PieSIG-UCU-VGUAY.jpg',11,285,188);
	} else {
		$this->Image('images/PieSIG-UCU.jpg',11,285,188);
	}
	$this->SetXY(11,-10);
	
	// Formato del pie de pagina: Times Italic 8
	$this->SetFont('Times','',8);
	// Muestra el número de página
	$this->Cell(5,0,'Página '.$this->PageNo().'/{nb}',0,0,'L');
  }  
	
//********** Funcion Justify *************
function Justify($text,$w,$h)
{
	$tab_paragraphe = explode("\n", $text);
	$nb_paragraphe = count($tab_paragraphe);
	$j=0;

	while ($j<$nb_paragraphe) {
		$paragraphe = $tab_paragraphe[$j];
		$tab_mot = explode(' ', $paragraphe);
		$nb_mot = count($tab_mot);

		// *** Handle strings longer than paragraph width
		$k=0;
		$l=0;
		while ($k<$nb_mot) {

			$len_mot = strlen ($tab_mot[$k]);
			if ($len_mot< ($w-5) ) {
				$tab_mot2[$l] = $tab_mot[$k];
				$l++;	
			} else {
				$m=0;
				$chaine_lettre='';
				while ($m<$len_mot) {
					$lettre = substr($tab_mot[$k], $m, 1);
					$len_chaine_lettre = $this->GetStringWidth($chaine_lettre.$lettre);

					if ($len_chaine_lettre>($w-7)) {
						$tab_mot2[$l] = $chaine_lettre . '-';
						$chaine_lettre = $lettre;
						$l++;
					} else {
						$chaine_lettre .= $lettre;
					}
					$m++;
				}
				if ($chaine_lettre) {
					$tab_mot2[$l] = $chaine_lettre;
					$l++;
				}
			}
			$k++;
		}

		// *** Justified lines
		$nb_mot = count($tab_mot2);
		$i=0;
		$ligne = '';
		while ($i<$nb_mot) {
			$mot = $tab_mot2[$i];
			$len_ligne = $this->GetStringWidth($ligne . ' ' . $mot);
			if ($len_ligne>($w-5)) {
				$len_ligne = $this->GetStringWidth($ligne);
				$nb_carac = strlen ($ligne);
				$ecart = (($w-2) - $len_ligne) / $nb_carac;
				$this->_out(sprintf('BT %.3f Tc ET',$ecart*$this->k));
				$this->MultiCell($w,$h,$ligne);
				$ligne = $mot;
			} else {
				if ($ligne) {
					$ligne .= ' ' . $mot;
				} else {
					$ligne = $mot;
				}
			}
			$i++;
		}
		// *** Last line
		$this->_out('BT 0 Tc ET');
		$this->MultiCell($w,$h,$ligne);
		$tab_mot = '';
		$tab_mot2 = '';
		$j++;
	}
}  
}