<?php

/**
 * RecibosGeneradosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecibosGeneradosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecibosGeneradosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RecibosGenerados');
    }
}