<?php

/**
 * ResolucionesProfesoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResolucionesProfesoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResolucionesProfesoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResolucionesProfesores');
    }

    // Obtiene resoluciones de profesores por sede y planestudio
    public static function obtenerResolucionesxSedePlanEstudio($idsede, $idplanestudio)
    {
		$resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
					SELECT rp.idresolucionprofesor, rp.resolucion, concat(rp.resolucion, ' - ', rp.fecha) as resolucionfecha 
                    FROM resoluciones_profesores rp
                    JOIN facultades fac ON rp.idfacultad = fac.idfacultad
                    JOIN carreras car ON fac.idfacultad = car.idfacultad
                    JOIN planes_estudios pe on car.idcarrera = pe.idcarrera
                    WHERE rp.idsede = ".$idsede." AND pe.idplanestudio = ".$idplanestudio." AND resolucion_csu = 0 AND YEAR(rp.fecha) >= YEAR(now())
                    ORDER BY is_default DESC "
				);

		return $resultado;		
    }  

    // Obtiene resoluciones academicas (de facultad) de profesores filtrado por sede y facultad
    public static function obtenerResolucionesAcademicasxSedeFacultad($idsede, $idfacultad)
    {
        $resultado = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
                    SELECT rp.idresolucionprofesor, rp.resolucion, concat(rp.resolucion, ' (', rp.fecha, ') ') as resolucionfecha 
                    FROM resoluciones_profesores rp
                    JOIN facultades fac ON rp.idfacultad = fac.idfacultad
                    WHERE rp.idsede = ".$idsede." AND rp.idfacultad = ".$idfacultad." AND rp.resolucion_csu = 0 AND rp.activa 
                    ORDER BY is_default DESC, rp.fecha DESC "
                );

        return $resultado;      
    }       
}
