<?php

/**
 * TiposSedesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposSedesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposSedesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposSedes');
    }
}