<?php

/**
 * TiposAreasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposAreasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposAreasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposAreas');
    }
}