<?php

/**
 * TiposInscriptosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposInscriptosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposInscriptosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposInscriptos');
    }
}