<?php

/**
 * TiposPlanesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposPlanesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposPlanesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposPlanes');
    }
}