<?php

/**
 * TiposCargosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposCargosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposCargosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposCargos');
    }
}