<?php

/**
 * TiposExamenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposExamenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposExamenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposExamenes');
    }
}