<?php

/**
 * TransicionesMaterias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TransicionesMaterias extends BaseTransicionesMaterias
{
  // Obtiene la materia origen 
  public function getMateriaOrigen() 
    {	   		    
    	$oMateriaPlan = Doctrine_Core::getTable('MateriasPlanes')->find($this->getIdmateriaorigen());

		return $oMateriaPlan;		
    }	

  // Obtiene la materia destino 
  public function getMateriaDestino() 
    {	   		    
    	$oMateriaPlan = Doctrine_Core::getTable('MateriasPlanes')->find($this->getIdmateriadestino());

		return $oMateriaPlan;			
    }		
	
}
