<?php

/**
 * TransicionesMateriasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransicionesMateriasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransicionesMateriasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TransicionesMaterias');
    }
}