<?php

/**
 * TransicionesPlanes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TransicionesPlanes extends BaseTransicionesPlanes
{
  // Obtiene el plan de estudios origen 
  public function getPlanOrigen() 
    {	   		    
    	$oPlanEstudio = Doctrine_Core::getTable('PlanesEstudios')->find($this->getIdplanorigen());

		return $oPlanEstudio;		
    }	

  // Obtiene el plan de estudios destino 
  public function getPlanDestino() 
    {	   		    
    	$oPlanEstudio = Doctrine_Core::getTable('PlanesEstudios')->find($this->getIdplandestino());

		return $oPlanEstudio;		
    }	   

  // Obtiene la carrera 
  public function getCarrera() 
    {	   		    
    	$oPlanEstudio = Doctrine_Core::getTable('PlanesEstudios')->find($this->getIdplandestino());

		return $oPlanEstudio->getCarreras();		
    }	     
}
