<?php

/**
 * UnidadesDeTiempoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadesDeTiempoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadesDeTiempoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadesDeTiempo');
    }
}