<?php

/**
 * ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends PluginProfileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profile');
    }
    
    // Obtiene el perfil de un usuario
    public function obtenerPerfil($idusuario)
    {
    	$q = Doctrine_Query::create()
    	->select("*")
    	->from("Profile p")
    	->where("p.sf_guard_user_id = ".$idusuario)
    	->fetchOne();
    
    	return $q;
    }    
}