<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
        
  	// Busca si el email ya existe
  	public function buscarEmail($email)
    {
    	$q = Doctrine_Query::create()
	  		->select("*")
	 		->from("sfGuardUser u")
	 		->where("u.email_address LIKE '".$email."'")
	 		->orWhere("u.username LIKE '".$email."'")
	    	->fetchOne();
	       
        return $q['id'];
    } 	

  	// Busca si el perfil  ya existe
  	public function buscarPerfil($idtipodoc, $nrodoc)
    {
    	$q = Doctrine_Query::create()
	  		->select("p.*, u.id as userid")
	 		->from("Profile p, sfGuardUser u")
	 		->where("p.tipodoc = ".$idtipodoc)
	 		->andWhere("p.nrodoc = ".$nrodoc)
	 		->andWhere("p.sf_guard_user_id = u.id")
	 		->fetchOne();

	    return $q['userid'];
    }       
}