<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/22 14:55:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=elsolar',
  'username' => 'root',
  'password' => 'root911',
  'name' => 'doctrine',
)),);
