<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property integer $tipodoc
 * @property string $nrodoc
 * @property integer $idarea
 * @property string $perfil
 * @property integer $idsede
 * @property sfGuardUser $User
 * 
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer     getTipodoc()          Returns the current record's "tipodoc" value
 * @method string      getNrodoc()           Returns the current record's "nrodoc" value
 * @method integer     getIdarea()           Returns the current record's "idarea" value
 * @method string      getPerfil()           Returns the current record's "perfil" value
 * @method integer     getIdsede()           Returns the current record's "idsede" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method Profile     setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Profile     setTipodoc()          Sets the current record's "tipodoc" value
 * @method Profile     setNrodoc()           Sets the current record's "nrodoc" value
 * @method Profile     setIdarea()           Sets the current record's "idarea" value
 * @method Profile     setPerfil()           Sets the current record's "perfil" value
 * @method Profile     setIdsede()           Sets the current record's "idsede" value
 * @method Profile     setUser()             Sets the current record's "User" value
 * 
 * @package    sig
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('tipodoc', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nrodoc', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('idarea', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('perfil', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('idsede', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));
    }
}