<?php

class autogestionConfiguration extends sfApplicationConfiguration
{
  public function configure()
  {
  	DEFINE("MESASCREADAS",1); // SON MESAS CREADAS QUE A LAS CUALES LOS ALUMNOS NO SE PUEDEN INSCRIBIR EN AUTOGESTION
  	DEFINE("MESASPUBLICADAS",2); // SON MESAS CREADAS DISPONIBLE POR LOS ALUMNOS EN EL AUTOGESTION
  	DEFINE("MESASCERRADAS",3); // SON MESAS CERRADAS (ACTA VOLANTE)
  	DEFINE("LIBROMATRIZ",4); // SON MESAS QUE SE ENCUENTRAN EN EL LIBRO MATRIZ
  	DEFINE("MESASANULADAS",5); // SON MESAS ANULADAS
  	DEFINE("MESASELIMINADAS",6); // SON MESAS ELIMINADAS
  	
  	DEFINE("TIPOMESAREGULAR",1); // SON MESAS DE TIPO REGULAR
  	DEFINE("TIPOMESALIBRE",2); // SON MESAS DE TIPO LIBRE
  	DEFINE("TIPOMESAPROMOCION",3); // SON MESAS DE TIPO PROMOCION
  	DEFINE("TIPOMESAREGULARP",4); // SON MESAS DE TIPO REGULAR PUNTO
  	DEFINE("TIPOMESAEQUIVALENCIA",5); // SON MESAS DE TIPO EQUIVALENCIA
  	DEFINE("TIPOMESAEQUIVALENCIAC",6); // SON MESAS DE TIPO EQUIVALENCIA CALIFICACION
  	
  	DEFINE("NOTAAPROBACION",4); // NOTA CON QUE SE APRUEBAN LAS MATERIAS
  	DEFINE("NOTAPROMOCION",4); // NOTA CON QUE SE PROMOCIONAN LAS MATERIAS
  	
  	DEFINE("ESTADOACTIVO",1); // SON MESAS ELIMINADAS
  	
  	DEFINE("MATERIASNOGENERICAS",0); // SON MATERIAS NO GENERICAS
  	DEFINE("MATERIASOPTATIVAS",4); // SON MATERIAS OPTATIVAS
  	DEFINE("MATERIASSUBESPACIOS",2); // SON MATERIAS SUBESPACIOS 
  }
}
