<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/30 21:22:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=circulo',
  'username' => 'root',
  'password' => 'root911',
  'name' => 'doctrine',
)),);
