<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/29 17:45:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=circulo',
  'username' => 'root',
  'password' => 'root911',
  'name' => 'doctrine',
)),);
