<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/09/22 14:55:50
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrador',
      ),
    ),
  ),
);
